### ISSUE TITLE
steamclient.so problem

### ISSUE THREAD

**Issue by armyboylegend** [callofduty4x/CoD4x_Server#100]
I have just updated the server with 16.2 release but while starting the server i encountered this and server doesnt start

`Sys_Error: [S_API FAIL] SteamGameServer_Init() failed; unable to locate a local steamclient.so.`

while the cod4 directory contains all files

Kindly guide how to start the server. i am using ubuntu server 16.04 32 bit and latest cod4x server release 16.2

**Comment by IceNinjaman** [comment]
Can pay attention to console messages please? It is possible steamclient.so fails to load because of unmet dependencies.

**Comment by armyboylegend** [comment]
this is first line after issuing server start command

`./cod4_lnxded: ./libstdc++.so.6: no version information available (required by ./cod4_lnxded)`

i have renamed cod4x18_dedrun to cod4_lnxded

**Comment by armyboylegend** [comment]
same is the case while starting with cod4x18_dedrun

`root@ubuntu:/home/umair/OGP_User_Files/1/cod4# ./cod4x18_dedrun +set dedicated 2 +set net_port 28960 +set sv_punkbuster 1 +set fs_game mods/^2greens^0gaming^1pml-220 +exec greens.cfg +set rcon_password icecream +map_rotate
./cod4x18_dedrun: ./libstdc++.so.6: no version information available (required by ./cod4x18_dedrun)
********************************************************
***** RUNNING SERVER AS A ROOT IS GENERALLY UNSAFE *****
********************************************************`

**Comment by D4edalus** [comment]
looks like you failed to install the c++ standard library correctly. did you install it yourself, how did you install that library? ldd shows you what shared libraries are loaded, are those paths correct? are any files missing at all?

**Comment by D4edalus** [comment]
from seeing the path ./libstdc++.so.6 i would assume that you have not installed it but copied the file from somewhere?

**Comment by armyboylegend** [comment]
i didnt installed any c++ standard library.  just extracted game files and overwrited with cod4x files and issued game server start command and this happaned. i deployed at least 5 different versions of ubuntu and 1 centos 6 servers from vultr and DO but all gave same result.

**Comment by armyboylegend** [comment]
this is the file `libstdc++.so.6` which came bundled with steam server files of linux. and i have not installed any library. i just extracted the cod4x files in cod4 root directory and started the server with 16.1 non-steam because steam also had issue of different type. with 16.2 files, this issue has arised. kindly guide what should i do. thanks

**Comment by D4edalus** [comment]
try this then, and i think you should remove that local version of libstdc++.so.6
sudo apt-get install libstdc++6

**Comment by armyboylegend** [comment]
Thx for solution. I just did before your reply..thanks a lot for your guidance. Mark thread solved.

**Comment by SinnerX96** [comment]
./cod4_lnxded: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
