### ISSUE TITLE
"Call Vote" not working

### ISSUE THREAD

**Issue by Kianda** [callofduty4x/CoD4x_Server#104]
The default "Call Vote" always fail if I try to change gametype; I get "Invalid gametype." as response.

Any ideas on how to fix this? Thanks!

**Comment by Kingwolf123** [comment]
Yup second that. Invalid gametype is invoked if gametype is to be changed.

**Comment by T-Maxxx** [comment]
There must be names of gametypes and its localized versions but for some unknown reason memory of (at least my) server is empty. The server thinks there's no maps\gametypes with requested name and denies your vote request. Sad. I will remove check from callvote code and you will be able to call votes again.
![image](https://cloud.githubusercontent.com/assets/7836454/21021494/c74f2062-bd89-11e6-8c88-a216b71fe9c5.png)

**Comment by D4edalus** [comment]
how does voting work exactly? 

i tried to make a vote yesterday with \callvote map_rotate
the vote was started, but when the timer ran out nothing happened

also when i tried to call the \vote command on a second client nothing happened. also pressing F1, F2 to vote yes or no respectively did nothing.

**Comment by D4edalus** [comment]
another bug i noticed with \callvote was that in the right bottom a message gets displayed about starting the vote: "&&1 has started a vote" ( or something along that lines )
&&1 doesnt get translated to the playername for some reason

**Comment by bykidi** [comment]
@D4edalus p.s.: do not put that in your name. ever :D

**Comment by D4edalus** [comment]
@bykidi tell me more

**Comment by T-Maxxx** [comment]
@D4edalus
1) Read vote string.
2) Tokenize it, set voting flags (Who, what, when, etc.)
3) Set "vote" configstrings so it'll be syncronized on each connected client.
4) Wait for vote ends and receive "yes"\"no" commands, update configstring so clients will be notified when something changed.
5) If succeeded, check passed parameters and execute result command (eg. "map mp_voted_map").
I've noticed it fails at checking passed parameters.

**Comment by IceNinjaman** [comment]
\callvote g_gametype sab
Worked for me when I tried it. Maybe it works only if I am alone on server?

**Comment by iznogod** [comment]
Clients need to have the gametype.gsc in their maps/mp/gametypes folder, so you should include it (or a stub of it) in your .ff

**Comment by D4edalus** [comment]
was not a modded server where i tested that. gametype.gsc also is not overwritten by a custom version. would that still matter?

**Comment by Kingwolf123** [comment]
Close this issue? It is solved, voting gametype works correctly
