### ISSUE TITLE
Exceeded limit of 2400 'image' assets

### ISSUE THREAD

**Issue by EncryptorX** [callofduty4x/CoD4x_Server#107]
Hello!
This problem is old but still persists...
[Server Side] - ok
+set r_xassetnum "material=2560 xmodel=1200 xanim=3200 image=3000"

If the server is set with  above (+set) the server run with no problems. all the custom maps. like the new Dust2 and big ones run ok. 
but clients cannot enter.

[Client Side]
All clients get this error.
-Exceeded limit of 2400 'image' assets.-

if somehow the client receive the same command/update from the server always...

Sorry for my rusty english.
Thanks for the time and work.

**Comment by D4edalus** [comment]
it would be great having that. but it involves some heavy reverse engineering which nobody was yet interested in doing.

**Comment by IceNinjaman** [comment]
Well @D4edalus it should work already but doesn't work as it should.

**Comment by D4edalus** [comment]
Too bad :/ 

@IceNinjaman I've added the wontfix label for now so that we dont forget about it.

**Comment by IceNinjaman** [comment]
Issue is solved with current server code base.

**Comment by veteri** [comment]
Im still having this issue 5 years later on 21.1

**Comment by PureTryOut** [comment]
Same here. An example to reproduce this is loading the map `mp_mw3resistance` in combination with the OpenWarfare2 mod. The server loads the map fine but the client keeps crashing with the message that the limit of 2048 'material' assets has been exceeded.

Could the issue be reopened?

**Comment by IceNinjaman** [comment]
This issue is very difficult to fix, that why it never have been fixed.

**Comment by ThiagoScheffer** [comment]
But it was working around version 17.5.5

https://old.cod4x.ovh/index.php?/forums/topic/3382-exceeded-limit-of-2048-material-assets/

I don't remember what changed it
but I did many testing with 3x more times the limit and never crashed that time.

after 1.7.6 ever worked again
