### ISSUE TITLE
I don't have a steam copy of the game, I run it through wine/Linux. How do I get this to work?

### ISSUE THREAD

**Issue by fr1tzz** [callofduty4x/CoD4x_Server#110]
Not sure if this is the right place to get help, there is a forum but the registration wouldn't work for me so here I am.
Long story short is I switched to Linux 2 years ago and wanted to play come cod4 and everyone uses this new community patch. Thats great, it installed fine when I tried to join a server after updating to patch 1.7. Then I tried to rejoin after restarting. I asked me to install steam. This is really my main issue.
I've had this copy of cod4 since 2007 and I don't own it on steam. Not sure if I just had steam running in the background on windows it would work but I cant try that since I'm running wine.
thats about it really. Would totally suck if I cant play or have to buy a new copy and run steam through wine. :c

Any input is appreciated

**Comment by wkuzma** [comment]
I run steam and don't own  a steam copy  of cod4
I just added cod4 as a non steam game in the library and everything runs fine

**Comment by D4edalus** [comment]
cod4x isn't fully compatible with wine. dualbooting windows is probably the easiest solution. as wukzuma said you don't need to own it on steam. it is enough for steam to be running in the background, but also steam won't be necessary with windows anyways as that's a matter of compatibility between wine and cod4x.
i don't believe we have ever tested if the steam parts of cod4x work through wine.

**Comment by PureTryOut** [comment]
A note, CoD4X works fine in Wine. It might not be officially supported, but it's definitely compatible.

Just run the Windows version of Steam in Wine alongside CoD4 in Wine, you don't need them connected or anything, and CoD4X will run fine.

**Comment by D4edalus** [comment]
nice!
