### ISSUE TITLE
nvconfig_v2.dat loads but nothing change in the server.

### ISSUE THREAD

**Issue by thamidu** [callofduty4x/CoD4x_Server#111]
**nvconfig_v2.dat**
`//Autogenerated non volatile config settings

//Minimum power settings
\power\95\cmd\AdminRemoveAdmin\type\cmdMinPower\
\power\1\cmd\cmdlist\type\cmdMinPower\
\power\1\cmd\Login\type\cmdMinPower\
\power\95\cmd\AdminAddAdminWithPassword\type\cmdMinPower\
\power\80\cmd\AdminListAdmins\type\cmdMinPower\
\power\60\cmd\dumpbanlist\type\cmdMinPower\
\power\100\cmd\which\type\cmdMinPower\
\power\100\cmd\path\type\cmdMinPower\
\power\60\cmd\map_rotate\type\cmdMinPower\
\power\60\cmd\say\type\cmdMinPower\
\power\35\cmd\status\type\cmdMinPower\
\power\85\cmd\tell\type\cmdMinPower\
\power\35\cmd\kick\type\cmdMinPower\
\power\35\cmd\ministatus\type\cmdMinPower\
\power\50\cmd\tempban\type\cmdMinPower\
\power\60\cmd\unban\type\cmdMinPower\
\power\1\cmd\serverinfo\type\cmdMinPower\
\power\1\cmd\systeminfo\type\cmdMinPower\
\power\98\cmd\set\type\cmdMinPower\
\power\70\cmd\screensay\type\cmdMinPower\
\power\100\cmd\clientkick\type\cmdMinPower\
\power\70\cmd\map\type\cmdMinPower\
\power\60\cmd\permban\type\cmdMinPower\
\power\100\cmd\seta\type\cmdMinPower\
\power\100\cmd\sets\type\cmdMinPower\
\power\98\cmd\exec\type\cmdMinPower\
\power\100\cmd\XAssetUsage\type\cmdMinPower\
\power\50\cmd\record\type\cmdMinPower\
\power\50\cmd\stoprecord\type\cmdMinPower\
\power\100\cmd\scriptUsage\type\cmdMinPower\
\power\100\cmd\stringUsage\type\cmdMinPower\
\power\100\cmd\dumpuser\type\cmdMinPower\
\power\70\cmd\screentell\type\cmdMinPower\
\power\100\cmd\contell\type\cmdMinPower\
\power\100\cmd\consay\type\cmdMinPower\
\power\100\cmd\banClient\type\cmdMinPower\
\power\100\cmd\banUser\type\cmdMinPower\
\power\100\cmd\btempban\type\cmdMinPower\
\power\100\cmd\bpermban\type\cmdMinPower\
\power\100\cmd\unbanUser\type\cmdMinPower\
\power\100\cmd\onlykick\type\cmdMinPower\
\power\100\cmd\heartbeat\type\cmdMinPower\
\power\1\cmd\rules\type\cmdMinPower\
\power\100\cmd\fast_restart\type\cmdMinPower\
\power\95\cmd\map_restart\type\cmdMinPower\
\power\100\cmd\setPerk\type\cmdMinPower\
\power\100\cmd\killserver\type\cmdMinPower\
\power\10\cmd\ChangePassword\type\cmdMinPower\
\power\98\cmd\AdminChangeCommandPower\type\cmdMinPower\
\power\95\cmd\AdminChangePassword\type\cmdMinPower\
\power\95\cmd\AdminAddAdmin\type\cmdMinPower\
\power\95\cmd\gametype\type\cmdMinPower\
\power\100\cmd\downloadmap\type\cmdMinPower\
\power\100\cmd\addCommand\type\cmdMinPower\
\power\100\cmd\writenvcfg\type\cmdMinPower\
\power\100\cmd\clearAllMsg\type\cmdMinPower\
\power\100\cmd\addRuleMsg\type\cmdMinPower\
\power\100\cmd\addAdvertMsg\type\cmdMinPower\
\power\100\cmd\net_restart\type\cmdMinPower\
\power\100\cmd\pluginInfo\type\cmdMinPower\
\power\100\cmd\plugins\type\cmdMinPower\
\power\100\cmd\unloadPlugin\type\cmdMinPower\
\power\100\cmd\loadPlugin\type\cmdMinPower\
\power\100\cmd\writeconfig\type\cmdMinPower\
\power\100\cmd\quit\type\cmdMinPower\
\power\98\cmd\cvarlist\type\cmdMinPower\
\power\100\cmd\setu\type\cmdMinPower\
\power\100\cmd\reset\type\cmdMinPower\
\power\100\cmd\setcvartotime\type\cmdMinPower\
\power\100\cmd\setfromcvar\type\cmdMinPower\
\power\100\cmd\toggle\type\cmdMinPower\
\power\100\cmd\wait\type\cmdMinPower\
\power\100\cmd\echo\type\cmdMinPower\
\power\100\cmd\vstr\type\cmdMinPower\
\power\95\cmd\AdminListCommands\type\cmdMinPower\

//Admins authorization data
\username\phw\salt\e4479edb6b19b6f08faf19d21844577551c232cf844065672ba7a139ccf11b22\password\9e63a624a603f0ccb494bec97f788e0c804949470ab9e1e5f23685a7d48c9baa\uid\300000003\power\100\type\authAdmin\
`

I use this nvconfig_v2.dat in order to setup admin logins and admin powers in the server. When running COD4x18, the nvconfig_v2.dat file successfully loads. But it doesn't makes any changes in $cmdlist. It doesnt show $login as a command.

So how can I fix it?

**Comment by wkuzma** [comment]
I run the windows version of cod4x and
the new version uses nvconfig_v3.dat  not nvconfig_v2,dat
cod4x build 1711 version 1.8

**Comment by thamidu** [comment]
So is the syntax same? I mean will it work if I rename it to nvconfig_v3.dat . If not can you give me a piece of code of that.

**Comment by IceNinjaman** [comment]
This part will maybe not be handled:

//Admins authorization data
\username\phw\salt\e4479edb6b19b6f08faf19d21844577551c232cf844065672ba7a139ccf11b22\password\9e63a624a603f0ccb494bec97f788e0c804949470ab9e1e5f23685a7d48c9baa\uid\300000003\power\100\type\authAdmin

Otherwise it should get read. Try to rename it.
