### ISSUE TITLE
Screenshot evasion hack?

### ISSUE THREAD

**Issue by TacTicToe66** [callofduty4x/CoD4x_Server#112]
I have seen players that I suspect may be cheating with a wallhack. When I pull a screenshot it looks clean, however there is a message in the lower right indicating a "snapshot" was taken. I think this hack is somehow allowing them to evade wallhack detection and alerts them that a screenshot was taken. 

Any fix for for this? I can post a screenshot of what I( am referring to if need be.

**Comment by D4edalus** [comment]
sharing the screenshots would be a good point to start

**Comment by TacTicToe66** [comment]
In this same evening, I suspected 2 players of using wallhacks while spectating Tamer and Amy. Tamer was busted, Amy seemed to be using a screenshot evasion hack as well. I'm like 99% sure Amy was wallhacking, but nothing showed in the screenshots other that the word "snapshot" in the lower right. 

Tamer:

http://www.thekillingcrew.com/hackers/Tamer0000.jpg

Amy:

http://www.thekillingcrew.com/hackers/Amy0000.jpg
http://www.thekillingcrew.com/hackers/Amy0001.jpg
http://www.thekillingcrew.com/hackers/Amy0002.jpg

**Comment by D4edalus** [comment]
http://i.imgur.com/7SGsdBW.png
what you see is the output of cg_drawsnapshots probably

**Comment by thamidu** [comment]
Hey I found a esp called ArtificialAiming-Radar-v2.7. A friend of mine told me about this. Here ill share it with you. 

https://1drv.ms/u/s!Av6M3scryzQzjGAyzRkck8J490v-

@D4edalus

**Comment by D4edalus** [comment]
thanks, we will have a look at breaking it

**Comment by D4edalus** [comment]
invalid as the original request shows no proof of screenshot evasion.

**Comment by D4edalus** [comment]
note to myself: look at ArtificialAiming-Radar-v2.7

**Comment by Koajakins** [comment]
Couldn't get the above hack to work, no crashes or anything but the ESP doesnt seem to load.

**Comment by D4edalus** [comment]
@thamidu did you find this hack working? if so please post your system specs and os. from our view this hack is not functional.

**Comment by thamidu** [comment]
I think this hack only works on windows 7.
