### ISSUE TITLE
Linux CoD4x_Server LAN/Local Browser not replying to broadcasts

### ISSUE THREAD

**Issue by togenshi** [callofduty4x/CoD4x_Server#113]
Server: Ubuntu 16.04 64-bit
Install process: As per https://gameservermanagers.com/lgsm/cod4server/
Issue: Cannot see local linux Dedicated Server in client local browser.
 
Issue is not present in Windows. 

Client can connect and update using connect console command. Game works as it should if I used console -> connect <ip>.

Also tried http://superuser.com/questions/900726/cod4-linux-game-server-doesnt-send-udp-packets-as-response-to-broadcast

Set dedicated to 1 in start up script and cod4-server.cfg. Tried various net_ip from 0.0.0.0, <ip addr>, localhost and omit the variable altogether. Disabled IPv6 from kernel. Tried various ports as well. LDD is not missing any libraries, etc. Still not working.

Same with net_qport and every quake option I can find. No go. 

-------- Plugins initialization completed --------
IP: 127.0.0.1
IP: 192.168.1.22
Warning: Couldn't bind to a v6 ip address.
Opening IP socket: 127.0.0.1:28960 UDP
Opening IP socket: 192.168.1.22:28960 UDP
Opening IP socket: 0.0.0.0:28960 TCP
Opening IP socket: [::]:0 UDP
QUERY LIMIT: Querylimiting is enabled
[S_API] Initialization completed
--- Common Initialization Complete ---
--- Game binary initialization ---

-----------------------------
 CoD4X Auto Update
 Current version: 1.8
 Current subversion: 16.2
 Current build: 1711
-----------------------------

Listening through TCPDUMP confirms I am getting good ole quake 3 broadcast packets on 28960-28633 however the dedicated server isn't sending out a reply to the client.

17:33:29.195088 IP (tos 0x0, ttl 128, id 9100, offset 0, flags [none], proto UDP (17), length 43)
    192.168.1.2.28960 > 255.255.255.255.28960: UDP, length 15
E..+#.....U.........q q!........getinfo xxx...

192.168.1.2 being the CoD4 Client.

I have also got a CoD4 1.7 Linux Dedicated Server that has the same issue so I believe the issue is to do with the actual binary.

Is it possible to create a fix for this?

**Comment by D4edalus** [comment]
that is just a problem with the serverbrowser set to "local" right? so adding the server to the "favorites" would show it correctly for you?

**Comment by togenshi** [comment]
I run a 864 player LAN (rflan.org) and I can't expect 30-50 players to add individual servers to their favourites. But can confirm favourites does work. Might be able to direct people to add dns names to their favourites list but a reply will be helpful. 

For example, if we have to move to a NAT'd network, we can have a caching lan browser server running as a intermediary.

**Comment by IceNinjaman** [comment]
Well that problem exists for years now and I did never really care enough to actually want fix it.

**Comment by IceNinjaman** [comment]
Shall be fixed now.

**Comment by themegabyte** [comment]
@IceNinjaman hello, what was the issue here? Because cod2 has the same issue and I wonder if I can fix that too!

**Comment by AlexanderCurl** [comment]
Set the net_ip variable correctly in the startup command line, will be fine. like not 0.0.0.0, add your fix ip address instead.
