### ISSUE TITLE
Missing outgoing interface. Can not send data to updateserver

### ISSUE THREAD

**Issue by shahriar-shojib** [callofduty4x/CoD4x_Server#114]
Here is the full startup log:

CoD4 X 1.8 win_mingw-x86 build 1711 Nov 16 2016
--- Crypto Initializing ---
Testing sha1 hash function - positive.
Testing sha256 hash function - positive.
Testing tiger hash function - positive.
--- Crypto Initialization Complete ---
----- FS_Startup -----
Current language: english
Current fs_basepath: c:/games/call of duty modern warfare
Current fs_homepath: c:/games/call of duty modern warfare
Current search path:
c:\games\call of duty modern warfare\mods\pml220_skynet\z_sky_01.iwd (7 files)
c:\games\call of duty modern warfare\mods\pml220_skynet\z_c_r.iwd (4 files)
c:\games\call of duty modern warfare\mods\pml220_skynet\pml220.iwd (47 files)
c:/games/call of duty modern warfare/mods/pml220_skynet
c:\games\call of duty modern warfare\main\xbase_00.iwd (5 files)
c:\games\call of duty modern warfare\main\iw_nosteam.iwd (2 files)
c:\games\call of duty modern warfare\main\iw_13.iwd (265 files)
c:\games\call of duty modern warfare\main\iw_12.iwd (33 files)
c:\games\call of duty modern warfare\main\iw_11.iwd (448 files)
c:\games\call of duty modern warfare\main\iw_10.iwd (230 files)
c:\games\call of duty modern warfare\main\iw_09.iwd (447 files)
c:\games\call of duty modern warfare\main\iw_08.iwd (66 files)
c:\games\call of duty modern warfare\main\iw_07.iwd (34 files)
c:\games\call of duty modern warfare\main\iw_06.iwd (416 files)
c:\games\call of duty modern warfare\main\iw_05.iwd (716 files)
c:\games\call of duty modern warfare\main\iw_04.iwd (765 files)
c:\games\call of duty modern warfare\main\iw_03.iwd (670 files)
c:\games\call of duty modern warfare\main\iw_02.iwd (1296 files)
c:\games\call of duty modern warfare\main\iw_01.iwd (1456 files)
c:\games\call of duty modern warfare\main\iw_00.iwd (1054 files)
c:/games/call of duty modern warfare/main
c:/games/call of duty modern warfare/main_shared
c:/games/call of duty modern warfare/players
c:\games\call of duty modern warfare\main\localized_english_iw06.iwd (7 files)
    localized assets iwd file for english
c:\games\call of duty modern warfare\main\localized_english_iw05.iwd (1338 files)
    localized assets iwd file for english
c:\games\call of duty modern warfare\main\localized_english_iw04.iwd (1730 files)
    localized assets iwd file for english
c:\games\call of duty modern warfare\main\localized_english_iw03.iwd (3705 files)
    localized assets iwd file for english
c:\games\call of duty modern warfare\main\localized_english_iw02.iwd (3483 files)
    localized assets iwd file for english
c:\games\call of duty modern warfare\main\localized_english_iw01.iwd (3181 files)
    localized assets iwd file for english
c:\games\call of duty modern warfare\main\localized_english_iw00.iwd (2903 files)
    localized assets iwd file for english

File Handles:
----------------------
24308 files in iwd files
execing default_mp.cfg
execing default_mp_controls.cfg
execing default_mp_gamesettings.cfg
execing server_map.cfg
couldn't exec q3config_server.cfg
fs_game is write protected.
dedicated is write protected.
-------- Plugins initialization completed --------
Winsock Initialized
Hostname: *
IP6: fe80::c0d1:43f9:27f:62f5%7
IP6: fe80::2cb2:208d:e46c:19a5%17
IP: 192.168.1.100
IP6: 2001:0:9d38:6ab8:2cb2:208d:e46c:19a5
Opening IP6 socket: [fe80::c0d1:43f9:27f:62f5%7]:28960 UDP
Opening IP6 socket: [fe80::2cb2:208d:e46c:19a5%17]:28960 UDP
Opening IP6 socket: [2001:0:9d38:6ab8:2cb2:208d:e46c:19a5]:28960 UDP
Opening IP6 socket: [::]:28960 TCP
Opening IP socket: 192.168.1.100:28960 UDP
Opening IP socket: 0.0.0.0:28960 TCP
Opening IP socket: [::]:0 UDP
QUERY LIMIT: Querylimiting is enabled
[S_API] Initialization completed
--- Common Initialization Complete ---
--- Game binary initialization ---

-----------------------------
 CoD4X Auto Update
 Current version: 1.8
 Current subversion: 16.2
 Current build: 1711
-----------------------------

Server is up to date.

begin $init
end $init 8 ms
Loading fastfile code_post_gfx_mp
Loading fastfile localized_code_post_gfx_mp
Loading fastfile ui_mp
Loading fastfile common_mp
Loading fastfile localized_common_mp
Loading fastfile mod
Loaded zone 'code_post_gfx_mp'
Loaded zone 'localized_code_post_gfx_mp'
Loaded zone 'ui_mp'
Loaded zone 'common_mp'
Loaded zone 'localized_common_mp'
Loaded zone 'mod'
--- Game Binary Initialization Complete ---
Hitch warning: 3482 msec frame time
couldn't exec server.cfg
net_port will be changed upon restarting.
Close UDP socket: 816
Close UDP socket: 588
Close UDP socket: 628
Close UDP socket: 824
Close TCPv4 socket: 828
Close TCPv6 socket: 820
Winsock Initialized
Hostname: 
IP6: fe80::c0d1:43f9:27f:62f5%7
IP6: fe80::2cb2:208d:e46c:19a5%17
IP: 192.168.1.100
IP6: 2001:0:9d38:6ab8:2cb2:208d:e46c:19a5
Opening IP6 socket: [fe80::c0d1:43f9:27f:62f5%7]:28960 UDP
Opening IP6 socket: [fe80::2cb2:208d:e46c:19a5%17]:28960 UDP
Opening IP6 socket: [2001:0:9d38:6ab8:2cb2:208d:e46c:19a5]:28960 UDP
Opening IP6 socket: [::]:28960 TCP
Opening IP socket: 192.168.1.100:28960 UDP
Opening IP socket: 0.0.0.0:28960 TCP
Opening IP socket: [::]:0 UDP
------ Server Initialization ------
Server: mp_crash
----- FS_Startup -----
Current language: english
Current fs_basepath: c:/games/call of duty modern warfare
Current fs_homepath: c:/games/call of duty modern warfare
Current search path:
c:\games\call of duty modern warfare\mods\pml220_skynet\z_sky_01.iwd (7 files)
c:\games\call of duty modern warfare\mods\pml220_skynet\z_c_r.iwd (4 files)
c:\games\call of duty modern warfare\mods\pml220_skynet\pml220.iwd (47 files)
c:/games/call of duty modern warfare/mods/pml220_skynet
c:/games/call of duty modern warfare/usermaps/mp_crash
c:\games\call of duty modern warfare\main\xbase_00.iwd (5 files)
c:\games\call of duty modern warfare\main\iw_nosteam.iwd (2 files)
c:\games\call of duty modern warfare\main\iw_13.iwd (265 files)
c:\games\call of duty modern warfare\main\iw_12.iwd (33 files)
c:\games\call of duty modern warfare\main\iw_11.iwd (448 files)
c:\games\call of duty modern warfare\main\iw_10.iwd (230 files)
c:\games\call of duty modern warfare\main\iw_09.iwd (447 files)
c:\games\call of duty modern warfare\main\iw_08.iwd (66 files)
c:\games\call of duty modern warfare\main\iw_07.iwd (34 files)
c:\games\call of duty modern warfare\main\iw_06.iwd (416 files)
c:\games\call of duty modern warfare\main\iw_05.iwd (716 files)
c:\games\call of duty modern warfare\main\iw_04.iwd (765 files)
c:\games\call of duty modern warfare\main\iw_03.iwd (670 files)
c:\games\call of duty modern warfare\main\iw_02.iwd (1296 files)
c:\games\call of duty modern warfare\main\iw_01.iwd (1456 files)
c:\games\call of duty modern warfare\main\iw_00.iwd (1054 files)
c:/games/call of duty modern warfare/main
c:/games/call of duty modern warfare/main_shared
c:/games/call of duty modern warfare/players
c:\games\call of duty modern warfare\main\localized_english_iw06.iwd (7 files)
    localized assets iwd file for english
c:\games\call of duty modern warfare\main\localized_english_iw05.iwd (1338 files)
    localized assets iwd file for english
c:\games\call of duty modern warfare\main\localized_english_iw04.iwd (1730 files)
    localized assets iwd file for english
c:\games\call of duty modern warfare\main\localized_english_iw03.iwd (3705 files)
    localized assets iwd file for english
c:\games\call of duty modern warfare\main\localized_english_iw02.iwd (3483 files)
    localized assets iwd file for english
c:\games\call of duty modern warfare\main\localized_english_iw01.iwd (3181 files)
    localized assets iwd file for english
c:\games\call of duty modern warfare\main\localized_english_iw00.iwd (2903 files)
    localized assets iwd file for english

File Handles:
----------------------
24308 files in iwd files
Unloaded fastfile ui_mp
Loading fastfile mp_crash
Loaded zone 'mp_crash'
------- Game Initialization -------
gamename: Call of Duty 4
gamedate: Aug  1 2011
fs_ignoreLocalized is cheat protected.
-----------------------------------
g_antilag is read only.
By using this software you agree to the usage conditions you can find at https://github.com/D4edalus/CoD4x_Server#usage-conditions-for-server-hosters
-----------------------------------
Calculate referenced files checksums...
CRC32 for main/iw_11.iwd is e9cf411f Len 151420446
CRC32 for mods/pml220_skynet/z_c_r.iwd is 2c36a844 Len 3004
CRC32 for mods/pml220_skynet/pml220.iwd is 66527acd Len 276308
CRC32 for mods/pml220_skynet/z_sky_01.iwd is b24bef63 Len 5729452
CRC32 for zone/english/code_post_gfx_mp.ff is b144581c Len 89196
CRC32 for zone/english/mp_crash.ff is 9440e82a Len 35287381
CRC32 for zone/english/common_mp.ff is 4ef7a074 Len 13517381
CRC32 for mods/pml220_skynet/mod.ff is 5bd31c15 Len 283714
Steam: Server connected successfully
Hitch warning: 1243 msec frame time
GameServer is not VAC Secure!
GameServer SteamID: [A:1:4233619461]
Resolving cod4master.activision.com
cod4master.activision.com resolved to 185.34.104.231:20800
Have to fix up old client which reports version 6
Going from CS_FREE to CS_ZOMBIE for sK_BaapJaan num 0 from: 192.168.1.160:28960<=>192.168.1.100:28960
Resolving cod4update.cod4x.me
Missing outgoing interface. Can not send data to updateserver
reconnected: 192.168.1.160:28960
Have to fix up old client which reports version 6
Going from CS_FREE to CS_ZOMBIE for sK_BaapJaan num 0 from: 192.168.1.160:28960<=>192.168.1.100:28960
Resolving cod4update.cod4x.me
Missing outgoing interface. Can not send data to updateserver
reconnected: 192.168.1.160:28960
Have to fix up old client which reports version 6
Going from CS_FREE to CS_ZOMBIE for sK_BaapJaan num 0 from: 192.168.1.160:28960<=>192.168.1.100:28960
Resolving cod4update.cod4x.me
Missing outgoing interface. Can not send data to updateserver
reconnected: 192.168.1.160:28960
Have to fix up old client which reports version 6
Going from CS_FREE to CS_ZOMBIE for sK_BaapJaan num 0 from: 192.168.1.160:28960<=>192.168.1.100:28960
Resolving cod4update.cod4x.me
Missing outgoing interface. Can not send data to updateserver
reconnected: 192.168.1.160:28960
Have to fix up old client which reports version 6
Going from CS_FREE to CS_ZOMBIE for sK_BaapJaan num 0 from: 192.168.1.160:28960<=>192.168.1.100:28960
Resolving cod4update.cod4x.me
Missing outgoing interface. Can not send data to updateserver
reconnected: 192.168.1.160:28960
Have to fix up old client which reports version 6
Going from CS_FREE to CS_ZOMBIE for sK_BaapJaan num 0 from: 192.168.1.160:28960<=>192.168.1.100:28960
Resolving cod4update.cod4x.me
Missing outgoing interface. Can not send data to updateserver
reconnected: 192.168.1.160:28960
Have to fix up old client which reports version 6
Going from CS_FREE to CS_ZOMBIE for sK_BaapJaan num 0 from: 192.168.1.160:28960<=>192.168.1.100:28960
Rejected client sK_BaapJaan because updatebackend is unavailable

Here is the ping:
Pinging cod4update.cod4x.me [188.165.57.239] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 188.165.57.239:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

I tried to browse cod4update.cod4x.me on browser and it says hello, which means that ping is disabled on  remote server but the port 80 is open.
What could be the issue?

**Comment by shahriar-shojib** [comment]
It's fixed, I had to start the server with dedicated 2.

**Comment by T-Maxxx** [comment]
For future. Ping - is an ICMP packet which can be filtered out. Sometimes when you can not ping some resource - it doesn't mean its offline.
