### ISSUE TITLE
Cod4x GSC function Not Working

### ISSUE THREAD

**Issue by smvhost** [callofduty4x/CoD4x_Server#115]
backbuttonpressed()
moveleftbuttonpressed()
Above two functions are not working in cod4x18-16.2 build 1711
forwardbuttonpressed()
moverightbuttonpressed()
Are working perfect.  All these function works on cod4x18-16.1 build 1458

Try attatched script for testing.

Thanks

[keypresstest.txt](https://github.com/callofduty4x/CoD4x_Server/files/693382/keypresstest.txt)

**Comment by D4edalus** [comment]
interesting, i am using it for navigation in a menu. but my server version is a little more dated i believe.

**Comment by smvhost** [comment]
Can you confirm that the bug is right ... Or is that with my script or any client side error ?? 
I tested the attatched script with current official 16.2 version downloaded from cod4x.me (I tested both linux and windows server version, in both its not working)..

Please confirm... Thank you

**Comment by D4edalus** [comment]
I will test (and eventually fix) it in the evening with the master branch. your gsc code seems fine to me.

**Comment by leiizko** [comment]
This was already fixed [CoD4x_Server/issues/102](https://github.com/callofduty4x/CoD4x_Server/issues/102)

**Comment by D4edalus** [comment]
@leiizko thanks

I just confirmed that it works normally in the latest build.

@smvhost https://github.com/callofduty4x/CoD4x_Server/releases v16.2.5 and v16.2.1 should work fine for you 😄

**Comment by smvhost** [comment]
Thanks
