### ISSUE TITLE
Menu File Extractor

### ISSUE THREAD

**Issue by D4edalus** [callofduty4x/CoD4x_Server#116]
Extract textual menu definitions from the running server. 
Purpose: Reverseengineering existing menus.

**Comment by T-Maxxx** [comment]
These are actually decompiled and compiled back without any changes ^.^
![shot0000](https://cloud.githubusercontent.com/assets/7836454/21954838/6d4e2e58-da6e-11e6-91e8-b8a4d37dce63.jpg)
![shot0001](https://cloud.githubusercontent.com/assets/7836454/21954840/6d4fa562-da6e-11e6-8842-84c1c5ddeaa5.jpg)
![shot0002](https://cloud.githubusercontent.com/assets/7836454/21954841/6d501e20-da6e-11e6-91b7-57be85170fa0.jpg)
![shot0004](https://cloud.githubusercontent.com/assets/7836454/21954839/6d4f3000-da6e-11e6-9956-fe86007180e1.jpg)

**Comment by icekobrin** [comment]
Хорошая работа. :+1:

**Comment by D4edalus** [comment]
well done :) 👍
