### ISSUE TITLE
Bann error

### ISSUE THREAD

**Issue by Tomtam21** [callofduty4x/CoD4x_Server#118]
bann problem with   build 1730 jan 8. 2017  server file version. When we banned the players, the server banned the players but players haven"t in  the  banlist.dat.tmp and banlist.dat  file, its empty. So the banned players come pack in the server immediately. Please help!
Best regards: TomTam

**Comment by wkuzma** [comment]
did you load the ban plugins by putting these commands in your server config file
loadplugin simplebanlist
loadplugin legacybanlist

**Comment by Tomtam21** [comment]
I see the simplebanlist.so file and legacybanlist.so file in the plugins dirrectory. But i didnt know this two file how must be load. Do you help me?

Thanks your help
Best regards: TomTam

**Comment by IceNinjaman** [comment]
`loadplugin simplebanlist
loadplugin legacybanlist`
