### ISSUE TITLE
Create gsc function to dump keys of a spawnStruct()

### ISSUE THREAD

**Issue by mirko911** [callofduty4x/CoD4x_Server#119]
Atm it's only possible to get the keys of an array, but not of a spawnStruct().

I would like to have a function to dump all existing keys of a spawnStruct/ent. This would be very cool for Mod Development, because you don't have to look through tons of gsc scripts to find out which values were set. You could just call the function on the struct and you can see which things are defined and which not.

An additional step could be a full dump (keys and values) of a spawnStruct, but I see some problems if they contain Arrays or other structs.

Example:
```C
myStruct = SpawnStruct();
myStruct.foo = testA
myStruct.bar = testB

struct_keys = dumpStruct(myStruct);
for(i = 0; i < struct_keys.size; i++)
    iprintlnbold("Struct Key: " + struct_key[i]);

/* 
Would output:
Struct Key: foo
Struct Key: bar

```

**Comment by D4edalus** [comment]
would be useful, yes. 

for a dump function i'd simply ignore the possibility of recursive resolution and just print "[SpawnStruct]" or "[Array]" in such a case. the scripter can then digg deeper easily.

**Comment by T-Maxxx** [comment]
![image](https://cloud.githubusercontent.com/assets/7836454/22100913/32c4fba4-de42-11e6-83ce-c93a0db6d34d.png)
This one looks weird to me. It just changes type and value of passed variable according to some size calculation logic.

**Comment by mirko911** [comment]
any updates here?

**Comment by D4edalus** [comment]
you are welcome to implement it

**Comment by T-Maxxx** [comment]
I have looked into it some time ago and it just makes no sense for me.

**Comment by T-Maxxx** [comment]
I have encountered that entity field variables are stored inside one data buffer with format "<string name>,<word index>, <fieldtype_t as byte type>". I think it's possible to dump all the data. Working on it.

**Comment by T-Maxxx** [comment]
There's a function exist, `Scr_FindAllVariableFields`, 0x08154AF0, looks like it allows to get list of name indexes of struct.

**Comment by T-Maxxx** [comment]
@mirko911 Do you have proof of this feature in some other projects? Looks like its not impossible to extract fields names because when you referencing field of a struct:
* **Get**: VM calculates hash of reference field name, loops through struct's siblings (all fields, can be retrieved with function above), compares hashes and returns value of sibling variable if found one (`undefined` otherwise).
* **Set**: VM calculates hash of referenced field name, sets (or adds new) appropriate sibling to specified value.
