### ISSUE TITLE
Rename players with empty names

### ISSUE THREAD

**Issue by D4edalus** [callofduty4x/CoD4x_Server#12]

**Comment by IceNinjaman** [comment]
They have already NoName as player name. Don't they?

**Comment by PureTryOut** [comment]
I guess this is related to [this](https://cod4x.me/forum/thread-238-post-620.html#pid620) forum thread.

**Comment by T-Maxxx** [comment]
They don't.
With name "" game will show "&&1 connected", with name "^7" game will show " connected".

**Comment by IceNinjaman** [comment]
Are you using the additional library you can download on forum?
I think only with it players getting renamed.

**Comment by T-Maxxx** [comment]
Nothing additional, only latest dev build.

**Comment by T-Maxxx** [comment]
Guys, I don't actually understand how additional authlibrary or whatever affects renaming players and I think this issue has to be resolved or closed, but bug still exist.

**Comment by T-Maxxx** [comment]
Note to myself: sv_client:218, after `Q_strncpyz(nick, Info_ValueForKey( userinfo, "name" ), 33);` call `clientcleanname`
