### ISSUE TITLE
Error when compilation

### ISSUE THREAD

**Issue by 3aTeuHuk** [callofduty4x/CoD4x_Server#121]
Hey. Help with an error. OS linux Debian.
`cod4# make linux32
[Linux] Building specific files...
[Linux] Building ZLib...
[Linux] Building NASM code...
[Linux] Building self-updateable common code...
[Linux] Linking binary...
[Linux] Cleaning up...
make: /sbin/paxctl: Command not found
make: *** [do_paxctl] Error 127`

**Comment by T-Maxxx** [comment]
https://github.com/callofduty4x/CoD4x_Server/blob/master/README.md#compiling-linux
