### ISSUE TITLE
Guide to install cod4x client for Mac / Linux

### ISSUE THREAD

**Issue by D4edalus** [callofduty4x/CoD4x_Server#122]
This is a bit out of place here, but some users on http://cod4x.me would be interested in a guide on how to setup the CoD4x Client on Mac ( https://cod4x.me/forum/thread-1080.html ) 

Some possibilities for guides would be 
* set CoD4x up on Mac with Bootcamp, Windows
* set CoD4x up on Mac with Wine
* set CoD4x up on your Linux distro of choice with Wine

**Comment by T-Maxxx** [comment]
I guess you need a someone who can handle keyboard and have Mac :D

**Comment by D4edalus** [comment]
Runs very poorly on wine. 
Tried with GTX970 (~70fps max) and GTX950. Many visual glitches on both cards ( E.g: Not working alpha on some textures )

https://cod4x.me/index.php?/forums/topic/521-linux-os/&do=findComment&comment=3720

**Comment by Josh-G** [comment]
Hi,
I've written a guide for my community to install CoD4x with wine on Mac and Linux and it works fine for me and the users who have tried it (no visual glitches), with only one issue; the client does not send a guid to the server when it connects, its completely empty in the join log. I was unable to find a workaround and this is the only issue preventing Mac users from running the 1.8 patch, any suggestions?

**Comment by D4edalus** [comment]
@Josh-G 
1) please post the link
2) you probably have to install steam

https://cod4x.me/index.php?/forums/topic/521-linux-os/&do=findComment&comment=3998
