### ISSUE TITLE
bug on makefile

### ISSUE THREAD

**Issue by k4r3l01** [callofduty4x/CoD4x_Server#123]
when i try to build binary via makefile i give this error
paxctl -c ./bin/cod4x18_dedrun
./bin/cod4x18_dedrun: Invalid argument
makefile:125: recipe for target 'do_paxctl' failed
make: *** [do_paxctl] Error 1

**Comment by T-Maxxx** [comment]
Original lines:
```
/sbin/paxctl -c ./bin/cod4x18_dedrun
/sbin/paxctl -em ./bin/cod4x18_dedrun
```

Makefile ones:
```
@/sbin/paxctl -c ./bin/$(COD4XBIN)
@/sbin/paxctl -em ./bin/$(COD4XBIN)
```
where `$(COD4XBIN)` is `cod4x18_dedrun`. So I have no idea why this is not working for you. [And only for you](https://travis-ci.org/callofduty4x/CoD4x_Server#L501). There's no bugs. [RTFM](https://github.com/callofduty4x/CoD4x_Server#compiling-linux).

**Comment by k4r3l01** [comment]
so i tried to use more linux distribution but on every distribution i have same issue i tried ubuntu 12.04 x86 and x64 build next same with version 15.04 and latest i tried to make this under debian and on every distribution i have same issue
i tried this without makefile and still same 
./cod4x18_dedrun: invalid argument

**Comment by k4r3l01** [comment]
and here is log from strace

execve("/sbin/paxctl", ["/sbin/paxctl", "-c", "cod4x18_dedrun"], [/* 19 vars */]) = 0
brk(0)                                  = 0x924f000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap2(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb771c000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=33622, ...}) = 0
mmap2(NULL, 33622, PROT_READ, MAP_PRIVATE, 3, 0) = 0xb7713000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/i386-linux-gnu/i686/cmov/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\3\0\0\0\0\0\0\0\0\3\0\3\0\1\0\0\0\300\233\1\0004\0\0\0"..., 512) = 512
fstat64(3, {st_mode=S_IFREG|0755, st_size=1750780, ...}) = 0
mmap2(NULL, 1755772, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb7566000
mmap2(0xb770d000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1a7000) = 0xb770d000
mmap2(0xb7710000, 10876, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xb7710000
close(3)                                = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb7565000
set_thread_area({entry_number:-1, base_addr:0xb7565940, limit:1048575, seg_32bit:1, contents:0, read_exec_only:0, limit_in_pages:1, seg_not_present:0, useable:1}) = 0 (entry_number:6)
mprotect(0xb770d000, 8192, PROT_READ)   = 0
mprotect(0x804b000, 4096, PROT_READ)    = 0
mprotect(0xb7740000, 4096, PROT_READ)   = 0
munmap(0xb7713000, 33622)               = 0
open("cod4x18_dedrun", O_RDWR|O_LARGEFILE) = 3
fstat64(3, {st_mode=S_IFREG|0770, st_size=2662056, ...}) = 0
mmap2(NULL, 2662056, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0) = -1 EINVAL (Invalid argument)
close(3)                                = 0
dup(2)                                  = 3
fcntl64(3, F_GETFL)                     = 0x402 (flags O_RDWR|O_APPEND)
brk(0)                                  = 0x924f000
brk(0x9270000)                          = 0x9270000
fstat64(3, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb771b000
_llseek(3, 0, 0xbfc7a1b0, SEEK_CUR)     = -1 ESPIPE (Illegal seek)
write(3, "cod4x18_dedrun: Invalid argument"..., 33cod4x18_dedrun: Invalid argument
) = 33
close(3)                                = 0
munmap(0xb771b000, 4096)                = 0
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by AlexanderCurl** [comment]
I pulled the latest release now, and compiled it without errors, but i have paxctl and grsec as well on my system.

**Comment by k4r3l01** [comment]
so i dont know how but now its working
under debian 32bit

**Comment by AlexanderCurl** [comment]
I compiled debian as well, but im using 64 bit, with multiarch, so no difference.
