### ISSUE TITLE
Installation dialog

### ISSUE THREAD

**Issue by somewhatwindy** [callofduty4x/CoD4x_Server#127]
When you attempt to join a CoD4 X 1.8 server with 1.7 client version, a dialog will appear.

It states that you can install the newer patch or just "abort" it, which isn't functional.
However, when you see this dialog it's  already installed without any permission or notification.
Please change the text to something more accurate.

**Comment by AlexanderCurl** [comment]
The reason why the dialog appears is the player can decide to install a 3rd party software in his computer or not. Otherwise we breaking the EULA.

**Comment by IceNinjaman** [comment]
Well I am really sure the install and the abort option have a different effect.

**Comment by somewhatwindy** [comment]
That's the reason for opening this issue. The player has no chance to decide anything. The dialog comes up right after it got installed.

**Comment by IceNinjaman** [comment]
There is no proper or easy way to show a player such a dialog before some files got placed on the players pc. On every mod enabled server you join some files getting installed onto your disk. So you should be aware of it when running cod4.
Still the player can decide on this dialog if the game will restart with CoD4 x18 or if it just disable after he close the game.
So just accept it.
