### ISSUE TITLE
1.7a to 1.8 banlist failure

### ISSUE THREAD

**Issue by shelly1337** [callofduty4x/CoD4x_Server#128]
added
loadplugin simplebanlist
loadplugin legacybanlist
to my server cfg, but the old bans are getting ignored

**Comment by D4edalus** [comment]
1.7a used cdkey based guids, those are useless for 1.8x as the guid system has changed
legacybanlist plugin refers to cod4x1.8 <=15.9, not 1.7a
make a new banlist

https://github.com/callofduty4x/CoD4x_Server/wiki/Banlists-in-version-15.9--and-other-changes read

**Comment by shelly1337** [comment]
ah okay. Thought its also working for 1.7a.
Is there a way to get generate the old guid with a plugin? Because we have ~4000 bans.

**Comment by D4edalus** [comment]
not really, using bans that were issued on cdkey based guids is a bad idea anyways.

read here:
https://cod4x.me/index.php?/forums/topic/470-any-way-to-keep-original-guid/
