### ISSUE TITLE
cannot compile 

### ISSUE THREAD

**Issue by eMaX75** [callofduty4x/CoD4x_Server#129]
this error occurs when running compile_win32.cmd 

F:\path\CoD4x_Server-master\src\tomcrypt>gcc -m32 -Wall -Os -s -c -I. -DLTC_NO_ROLC -DLTC_SOURCE pk\asn1\der\sequence\*.c
gcc: error: pk\asn1\der\sequence\*.c: Invalid argument
gcc: fatal error: no input files
compilation terminated.

**Comment by D4edalus** [comment]
what compiler are you using?
mingw64 works fine
i686-5.3.0-posix-dwarf-rt_v4-rev0

**Comment by ehasaranga** [comment]
Mingw

**Comment by ehasaranga** [comment]
let me check i used https://sourceforge.net/projects/mingw/files/Installer/ this one 32bit one

**Comment by ehasaranga** [comment]
can i know the difference between those 2 compilers? rather than 32 n 64 bits

**Comment by ehasaranga** [comment]
nop it's still the same

**Comment by D4edalus** [comment]
The exact version number is important as mimgw does not support file
Globbing in all of them

ehasaranga <notifications@github.com> schrieb am Fr., 10. Feb. 2017 06:48:

**Comment by T-Maxxx** [comment]
Are you sure you have copied error correctly? Actual compile line:
`gcc %FLAGS% pk\asn1\der\sequence\*.c`
Look at last slash in path.

**Comment by ehasaranga** [comment]
its bunch of this code,

F:\my stuff\games\Call Of Duty 4\online server files\CoD4x_Server-master\src\tomcrypt>SET FLAGS=-m32 -Wall -Os -s -c -I. -DLTC_NO_ROLC -DLTC_SOURCE

F:\my stuff\games\Call Of Duty 4\online server files\CoD4x_Server-master\src\tomcrypt>SET MATHFLAGS=-m32 -Wall -Os -s -c -I. -Imath -DLTC_NO_ROLC -DLTC_SOURCE

F:\my stuff\games\Call Of Duty 4\online server files\CoD4x_Server-master\src\tomcrypt>REM -Wsign-compare -W -Wshadow -Wno-unused-parameter-Wsystem-headers -Wdeclaration-after-statement -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wpointer-arith

F:\my stuff\games\Call Of Duty 4\online server files\CoD4x_Server-master\src\tomcrypt>gcc -m32 -Wall -Os -s -c -I. -DLTC_NO_ROLC -DLTC_SOURCE hashes\*.c
gcc: error: hashes\*.c: Invalid argument
gcc: fatal error: no input files
compilation terminated.

F:\my stuff\games\Call Of Duty 4\online server files\CoD4x_Server-master\src\tomcrypt>gcc -m32 -Wall -Os -s -c -I. -DLTC_NO_ROLC -DLTC_SOURCE misc\crypt\*.c
gcc: error: misc\crypt\*.c: Invalid argument
gcc: fatal error: no input files
compilation terminated.

F:\my stuff\games\Call Of Duty 4\online server files\CoD4x_Server-master\src\tomcrypt>gcc -m32 -Wall -Os -s -c -I. -DLTC_NO_ROLC -DLTC_SOURCE misc\base64\*.c
gcc: error: misc\base64\*.c: Invalid argument
gcc: fatal error: no input files
compilation terminated.


and many more

**Comment by D4edalus** [comment]
https://github.com/callofduty4x/CoD4x_Server/blob/master/src/tomcrypt/compile_win32.cmd
clearly the compile scripts contains backslashes before *.c
your terminal must strip them away somehow .. 

what commandlinetool are you using? this works fine for me on the windows 10 commandline.

**Comment by ehasaranga** [comment]
C:\Users\name>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/Program\ Files\ (x86)/mingw-w64/i686-6.3.0-posix-dwarf-rt_v5-rev1/mingw32/bin/../libexec/gcc/i686-w64-mingw32/6.3.0/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: ../../../src/gcc-6.3.0/configure --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i686-w64-mingw32 --prefix=/mingw32 --with-sysroot=/c/mingw630/i686-630-posix-dwarf-rt_v5-rev1/mingw32 --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --enable-libstdcxx-filesystem-ts=yes --disable-sjlj-exceptions --with-dwarf2 --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=i686 --with-tune=generic --with-libiconv --with-system-zlib --with-gmp=/c/mingw630/prerequisites/i686-w64-mingw32-static --with-mpfr=/c/mingw630/prerequisites/i686-w64-mingw32-static --with-mpc=/c/mingw630/prerequisites/i686-w64-mingw32-static --with-isl=/c/mingw630/prerequisites/i686-w64-mingw32-static --with-pkgversion='i686-posix-dwarf-rev1, Built by MinGW-W64 project' --with-bugurl=http://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -fno-ident -I/c/mingw630/i686-630-posix-dwarf-rt_v5-rev1/mingw32/opt/include -I/c/mingw630/prerequisites/i686-zlib-static/include -I/c/mingw630/prerequisites/i686-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -fno-ident -I/c/mingw630/i686-630-posix-dwarf-rt_v5-rev1/mingw32/opt/include -I/c/mingw630/prerequisites/i686-zlib-static/include -I/c/mingw630/prerequisites/i686-w64-mingw32-static/include' CPPFLAGS=' -I/c/mingw630/i686-630-posix-dwarf-rt_v5-rev1/mingw32/opt/include -I/c/mingw630/prerequisites/i686-zlib-static/include -I/c/mingw630/prerequisites/i686-w64-mingw32-static/include' LDFLAGS='-pipe -fno-ident -L/c/mingw630/i686-630-posix-dwarf-rt_v5-rev1/mingw32/opt/lib -L/c/mingw630/prerequisites/i686-zlib-static/lib -L/c/mingw630/prerequisites/i686-w64-mingw32-static/lib -Wl,--large-address-aware'
Thread model: posix
gcc version 6.3.0 (i686-posix-dwarf-rev1, Built by MinGW-W64 project)

here is the version details gcc

**Comment by D4edalus** [comment]
as i said .. if you suspect the compiler version try the one i'm using
as already posted above: i686-5.3.0-posix-dwarf-rt_v4-rev0

**Comment by D4edalus** [comment]
i dont know why your terminal removes the last backslash only .. maybe try replacing all backslashes with slashes xD ?

**Comment by ehasaranga** [comment]
let me check i think i found the prob, 
if it was success, the cmd should be like this??

F:\path\CoD4x_Server-master\src\tomcrypt>gcc -m32 -Wall -Os -s -c -I. -DLTC_NO_ROLC -DLTC_SOURCE hashes\*.c

F:\path\CoD4x_Server-master\src\tomcrypt>gcc -m32 -Wall -Os -s -c -I. -DLTC_NO_ROLC -DLTC_SOURCE misc\crypt\*.c

F:\path\CoD4x_Server-master\src\tomcrypt>gcc -m32 -Wall -Os -s -c -I. -DLTC_NO_ROLC -DLTC_SOURCE misc\base64\*.c

**Comment by D4edalus** [comment]
yeah, if it doesnt display errors its probably fine. after compilation the <cod4x_server>/bin folder must contain libtomcrypt_win32.a

what was the problem?

**Comment by ehasaranga** [comment]
in compile_win32.cmd , @set path=path=C:\MinGW\bin;%path% this has been set to my old compiler, i install the compiler you told me i just change it ,and works, but i dont get any file on /bin 

F:\path\CoD4x_Server-master\src\tomcrypt>REM -Wsign-compare -W -Wshadow -Wno-unused-parameter-Wsystem-headers -Wdeclaration-after-statement -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wpointer-arith

**Comment by ehasaranga** [comment]
file has created on lib folder, and then i when i run build.cmd on mbedtls folder, i get this

Compiling: release
x509_crl.c: In function 'mbedtls_x509_crl_parse':
x509_crl.c:508:5: warning: this 'else' clause does not guard... [-Wmisleading-indentation]
     else
     ^~~~
x509_crl.c:514:9: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'else'
         if( ret == 0 )
         ^~

**Comment by D4edalus** [comment]
sorry i ment <cod4x_server>/lib before, not <cod4x_server>/bin 

those aren't errors, errors spell "error" :P

**Comment by ehasaranga** [comment]
what about this one? 

Compiling: release
x509_crl.c: In function 'mbedtls_x509_crl_parse':
x509_crl.c:508:5: warning: this 'else' clause does not guard... [-Wmisleading-indentation]
else
^~
x509_crl.c:514:9: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'else'
if( ret == 0 )
^~

**Comment by D4edalus** [comment]
it literally says "warning", not "error"

**Comment by ehasaranga** [comment]
okay i fixed it putting brackets,  after doing those two, what should i do to compile server??

"First enter /src/tomcrypt, and run compile_win32.cmd. Then go to /src/mbedtls, and run build.cmd.

Now compile the server:

**mingw32-make win32**
If compilation was successful the binary will be placed in the /bin/ folder."

**Comment by ehasaranga** [comment]
[Windows] Building NASM code...
[Windows] Building self-updateable common code...
[Windows] Linking binary...
[Windows] Building plugin exports library...
'pexports' is not recognized as an internal or external command,
operable program or batch file.
makefile:110: recipe for target 'pexports' failed
mingw32-make: *** [pexports] Error 1

any fix for these error

**Comment by D4edalus** [comment]
isntall pexports

**Comment by ehasaranga** [comment]
how do i do that?

**Comment by eMaX75** [comment]
got it covered, it compiles but i keep getting these warnings, should i ignore them?? or is there any fix for that

[Windows] Building specific files...
../src/win32/pe32_parser.c: In function 'PE32_GetStrTable':
../src/win32/pe32_parser.c:230:6: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
      if(nstrings < MAX_IMPORT_STRINGS -1)
      ^~
../src/win32/pe32_parser.c:232:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
       nstrings ++;
       ^~~~~~~~
../src/win32/sys_win32.c: In function 'Sys_Dirname':
../src/win32/sys_win32.c:571:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     if (max)
     ^~
../src/win32/sys_win32.c:573:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
  return va("%s", dir);
  ^~~~~~
[Windows] Building ZLib...
../src/zlib/unzip.c:3029:19: warning: 'inflate_copyright' defined but not used [-Wunused-const-variable=]
 static const char inflate_copyright[] =
                   ^~~~~~~~~~~~~~~~~

**Comment by T-Maxxx** [comment]
Where the hell your C compiler was assembled?

**Comment by eMaX75** [comment]
default folder, i didnt change the path when installing, its on program86/mingw-w64

**Comment by eMaX75** [comment]
can you get me link for the compiler???

**Comment by eMaX75** [comment]
hey dude thanks for the support, really appreciate it and there is one more question, is there a way to activate screenshot feature on 1.7a ???

**Comment by AlexanderCurl** [comment]
No, the screenshot feature is came with 1.8 dedicated server and client side integration. Not possible.

**Comment by T-Maxxx** [comment]
This is not forum. Issue section are about problems with whole project but not with some OSs\compilers\configs\FAQs\etc. Please don't forget that.
