### ISSUE TITLE
linux auth libs?

### ISSUE THREAD

**Issue by pvolkv** [callofduty4x/CoD4x_Server#131]
Hi huys,
where can I find auth libs? cuz I got no guids
Thanks

**Comment by pvolkv** [comment]
upd: libs founded, but now I got only old style player id's like 2363857367348575
how can I switch to cod4x Id's ?
thanks!

**Comment by T-Maxxx** [comment]
Sv_legacyguidmode

**Comment by D4edalus** [comment]
wait a second, 2363857367348575 <- thats not the old style, thats the new style

**Comment by T-Maxxx** [comment]
Old GUID is hexadecimal number written as 32 character string. "AB CD EF 00" for 0xAB 0xCD 0xEF 0x00 etc.
New GUID (?) is Steam ID isn't it?
sv_legacyguidmode "1" means old GUID (aka pbguid) will be written to logs.

**Comment by D4edalus** [comment]
it has the same format, as steamids do. the simplest representation is just a 64bit number
https://developer.valvesoftware.com/wiki/SteamID

**Comment by pvolkv** [comment]
D4edalus, thanks for answers and for your 'cod4_new_experience'. Its just hard to sort out which GUIDs are the right ones. Especially for a newcomer
I still dont understand - what is this type of guid? - [32:32:234234]
For ex - I got 1975 build and another server got same, but my GUID can be like
23101230102358423953 or with legacyguid like 2h34g5324h3h43242345h345h345g and steam ids separately
and another server got uid/guid [32:32:234234] without steam ids

**Comment by D4edalus** [comment]
[x : y : z] is just another way to format the 64bit id. see the link to steam above on how convert between the representations. i agree that the switching between formats can be a little confusing.
