### ISSUE TITLE
New build (1994) not getting in activision serverlist

### ISSUE THREAD

**Issue by pvolkv** [callofduty4x/CoD4x_Server#132]
Hi!
 Just tested - build 1711 - its fine and I see my servers in ATVI list
Current build 1994 - nope...

**Comment by T-Maxxx** [comment]
Activision master server dead for few years. Isn't it?

**Comment by D4edalus** [comment]
no, it is working fine. 
i also have a server running on a little over 1711 which is listed as expected

**Comment by IceNinjaman** [comment]
I have repaired it. Sorry for trouble.

**Comment by pvolkv** [comment]
But now its ok with ATVI BUT not visible in COD4X list :) Seems to its not look in mastersvers.txt
