### ISSUE TITLE
nehoscreenshotuploader plugin - Failed to open file screenshots/test0000.jpg 

### ISSUE THREAD

**Issue by pvolkv** [callofduty4x/CoD4x_Server#133]
Hey guys! Got error when nehoscreenshotuploader plugin trying to read just created screenshot
**Error: Failed to open file screenshots/test0000.jpg for reading** 
I can find same problem in google which links to cod4x forum, but link is broken.... And there is no webcache
Ubuntu x64, all read rights are granted

**Comment by D4edalus** [comment]
cod4x stores the screenshots to fs_homepath/screenshots. check if the plugin also expects the screenshots in the set folder. 

might be that you need to set fs_homepath to "."

https://github.com/callofduty4x/CoD4x_Server/blob/master/plugins/screenshotsender/main.c#L401

**Comment by D4edalus** [comment]
also if you found a link to the old forums: all forum content has been migrated to the new forums, so you will be able to still find it.

**Comment by pvolkv** [comment]
@D4edalus thanks a lot, "." worked.
