### ISSUE TITLE
Error: Unable to resolve hostname raw.githubusercontent.com:443

### ISSUE THREAD

**Issue by volkv** [callofduty4x/CoD4x_Server#136]
In a new builds this error appears while server loading.
Is it should be **masterservers.txt** replacement feature?

**Comment by IceNinjaman** [comment]
Well yes it should replace masterservers.txt
But I don't understand why it should fail to resolve...

**Comment by D4edalus** [comment]
thats probably nonsense .. but if the error really is "Error: Unable to resolve hostname raw.githubusercontent.com:443" it maybe tries to resolve "raw.githubusercontent.com:443" instead of "raw.githubusercontent.com"
maybe that could be a problem?

**Comment by IceNinjaman** [comment]
https://github.com/callofduty4x/CoD4x_Server/blob/master/src/sys_net.c#L3758

Here the port gets split off

**Comment by T-Maxxx** [comment]
```
Resolving cod4master.cod4x.me 
cod4master.cod4x.me resolved to 188.165.57.239:20810
Error: Couldn't resolve(IPv6) cod4master.cod4x.me
Error: Couldn't resolve masterserver cod4master.cod4x.me
```
Wut? It's already resolved. Why do this again (IPv6, but its still resolved).

That github fail looks like user-specific problem and had been caused in temporary service offline period.

**Comment by T-Maxxx** [comment]
@volkv If your issue had been resolved somehow, please close the issue.

**Comment by volkv** [comment]
@T-Maxxx nope, I still have to use 
`+set sv_masterservers "*cod4master.cod4x.me"`

**Comment by T-Maxxx** [comment]
nslookup raw.githubusercontent.com / host raw.githubusercontent.com ?

**Comment by volkv** [comment]
Yeah, its probably network-related issue. Now tested on my home PC - no errors.

**Comment by iznogod** [comment]
Github was having issues thanks to Amazon AWS/S3 having issues. I think they resolved it now.
