### ISSUE TITLE
Increse max vehicle count

### ISSUE THREAD

**Issue by volkv** [callofduty4x/CoD4x_Server#138]
Hey huys! Is it possible to increase max vehicle count on the map at the same time which is [8] by default?
And after reaching it server gives fatal error "Hit max vehicle count [8]"
CoD4X source code? some dvars?

**Comment by T-Maxxx** [comment]
Control spawn of helicopters and optimize your mod.

**Comment by volkv** [comment]
It was just a question. Iam I right that answer is 'Its not possible'?

**Comment by D4edalus** [comment]
i dont think it is currently.
are you intending to spawn more than 8 helicopters at once?

**Comment by volkv** [comment]
yeah, to request as many packages as it needed at same time without waiting for previous heli to get out
same with several strafe runs at same time, etc

**Comment by D4edalus** [comment]
what packages? and what does that have to do with strafe running?

**Comment by T-Maxxx** [comment]
@volkv 5 days with no answer so I thought it's not interesting for you anymore. Limit to 2 care packages and 1 strafe at a time (total 7 + helicopter killstreak == 8).
@D4edalus Care packages, http://callofduty.wikia.com/wiki/Strafe_Run

**Comment by volkv** [comment]
so that 8 number is hardcoded somewhere deep?

**Comment by T-Maxxx** [comment]
No, SpawnVehicle in game code. There's place only for 8 vehicles so it shouldn't be too hard to reallocate space.
