### ISSUE TITLE
Is there any possibility of auto updating cod4 v1.7a to cod4x?

### ISSUE THREAD

**Issue by thamidu** [callofduty4x/CoD4x_Server#140]
Hey,
Recently I was running a v1.7a and a v1.8 server simultaneously in my VPS. But after some days the v1.7a server has automatically updated to COD4x version. Then I rollback again to 1.7a. But it updated again to 1.8 after some hours. So is there any possibility of auto updating 1.7a to 1.8? Because still I don't want to move to 1.8 how can I stop updating it?

Just, sorry developers. I still love  old school GUID system and admin login system with password login.  🙂

**Comment by D4edalus** [comment]
https://cod4x.me/index.php?/forums/topic/467-important-update-for-17a-unless-autoupdate-is-already-disabled/#comment-3680
