### ISSUE TITLE
Kick for empty player name

### ISSUE THREAD

**Issue by jNizM** [callofduty4x/CoD4x_Server#141]
My player name is set in config and visible in console before connecting
(cod4-location and cod4x-location -> same .cfg and readonly)
http://image.prntscr.com/image/6eeca8ae2cfe45a5a2e3f16bb6c9c59f.png

After connect to a server I got kicked for empty player name
http://image.prntscr.com/image/61c6256bdcd74a7cbc044477903ac8bd.png

Whatever I do before I connect, I got kicked.
`/name MyName`
`/connect IP:Port; password whatever`
or
`/connect IP:Port; password whatever; name MyName`

When I rename me with /name MyName after I got kicked, I can connect without any porbs.
But the first time fails.

**Comment by IceNinjaman** [comment]
First it is a client problem but this repo is for server.

But to answer your question: Maybe your userinfo string is overflowed?
Which server is it? IP:Port?

**Comment by jNizM** [comment]
Thanks for the reply.
I found out that the config was with an empty Player name (set name ""). The console showed me the name of my Player-Profile-Folder (thats why I was confused) but when I try to connect it used the name from the config and kicked me because of no name set.

Btw. where I can find the repo for the client version of cod4x?

**Comment by T-Maxxx** [comment]
@jNizM Nowhere, it's not for public.
