### ISSUE TITLE
Include player's IP into screenshot meta

### ISSUE THREAD

**Issue by volkv** [callofduty4x/CoD4x_Server#143]
Just a suggestion. To facilitate ban proccess

**Comment by T-Maxxx** [comment]
Mine IP can be changed each time I launch my router. SteamID\GUID obviously better. And it was suggested some time ago on forum or here.

**Comment by volkv** [comment]
But anyways I think it could simplify some admins life.
For example, for Sourcebans its better to fill players IP. At least It will show country flag then :)
And now I have to go to players stats and look there for IP.
So if its not so difficult to include IP info - It would be usefull for some admins

**Comment by icekobrin** [comment]
https://github.com/callofduty4x/CoD4x_Server/issues/58

**Comment by volkv** [comment]
yeah. but no conclusion was reached there...
same as here
ok. whatever. its not so important
