### ISSUE TITLE
sv_hostname with spaces

### ISSUE THREAD

**Issue by bbashy** [callofduty4x/CoD4x_Server#144]
Seems to be an issue when setting the sv_hostname value via console. Can this be fixed so you don't need to wrap the hostname in quotes?

```
]sv_hostname some name
]sv_hostname
"sv_hostname" is: "some" default: "CoD4Host" info: "Host name of the server"
```

**Comment by T-Maxxx** [comment]
OMG.
sv_hostname "some name"

**Comment by T-Maxxx** [comment]
Not an issue. Cmd_Argv[0] == "sv_hostname". [1] == "some". [2] == "name". Command handler just grabs first value and sets dvar to it. That's a default behaviour and will not be changed.

**Comment by bbashy** [comment]
CoD4 1.7 seems to be fine?

```
sv_hostname some name
sv_hostname
"sv_hostname" is: "some name^7" default: "CoD4Host^7"
  Domain is any text
```

**Comment by D4edalus** [comment]
tested on master, works as expected

this is 1.8x not 1.7. i cant make sense of what you are saying.

**Comment by bbashy** [comment]
@T-Maxxx So the expected behaviour is for it to break at a space when not using quotes?

It's just a problem I have with an automated system which resets the hostname if users change it. I can use RCON but won't work if users change that. Was just questioning since it's working in 1.7 but not 1.8x.

If it's never going to be changed, that's fine.

**Comment by T-Maxxx** [comment]
some_awesome_rcon_string_executor("seta sv_hostname \"My default server name\"")
I'm sure there must be any character escape strings to be able to place some unusual characters inside string in each language.

**Comment by bbashy** [comment]
I'll try again seeing as it's default behaviour.

It does go from PHP to Python API on the same server then sends commands in the saved session so hopefully it'll work.
