### ISSUE TITLE
Screenshot feature doesn't work with OGP.

### ISSUE THREAD

**Issue by AlexanderCurl** [callofduty4x/CoD4x_Server#146]
Hi all.

If you guys have some experience with OGP (OpenGamePanel) tell me how can I manage to get the screenshot feature works?

I was able to get it work in my 2 servers, but still I really don't know how.
On the another servers the server after the getss command just waiting the players movement and do nothing.

**Comment by AlexanderCurl** [comment]
Closed, require more people to play on the servers.

**Comment by D4edalus** [comment]
fyi: the screenshots are only triggered if another player is visible in the targetted players field of view.

**Comment by AlexanderCurl** [comment]
I though it's working with 1 player as well, when I was tested. When my wife joined it worked just fine :)
