### ISSUE TITLE
makefile for botlib

### ISSUE THREAD

**Issue by D4edalus** [callofduty4x/CoD4x_Server#147]
@T-Maxxx could you maybe create a makefile for the botlib?

https://github.com/callofduty4x/CoD4x_Server/tree/master/src/botlib

would be nice to have everything built with make instead doing half makefiles and half bash / cmd files

**Comment by T-Maxxx** [comment]
This looks like Copy-Paste from RtcW source code. Is it working properly? I'm not sure.

**Comment by D4edalus** [comment]
ohh ... i assumed you made that because you worked with the bot stuff before. nevermind its just experimental stuff that ninja committed there. and yeah i believe its a copy paste from rctw
