### ISSUE TITLE
Loading plugins from /plugins folder instead .iwd if present

### ISSUE THREAD

**Issue by IceNinjaman** [callofduty4x/CoD4x_Server#149]
Some people got trouble with plugins now as we ship them in .iwd file. However .iwd should not override plugins in /plugins folder. Need to be fixed to work as expected.

**Comment by icekobrin** [comment]
in game => http://puu.sh/v9Qkw/80a45e4f4a.jpg
rcon => http://puu.sh/v9Qpb/aa1b1fe3d6.png
plugins simplebanlist, in .iwd file

**Comment by D4edalus** [comment]
and that text is only scrambled when the plugin is loaded from the iwd?

**Comment by bykidi** [comment]
@D4edalus is that possible that he bans someone with russki name or using russki reason?

**Comment by T-Maxxx** [comment]
In order to make plugins directory override .iwd, can FS directories priorities be changed?
Plugin gets read here:
https://github.com/callofduty4x/CoD4x_Server/blob/master/src/plugin_handler.c#L143

**Comment by IceNinjaman** [comment]
FS_ReadFile() will always load from directory instead .iwd if there exists such a directory with a matching file. However the directory has to be a sub-directory of "fs_game". This is a special case since plugins should be loaded from CoD4-Root/plugins instead fs_game/plugins
So swapping that 2 functions should do the trick I think.

**Comment by IceNinjaman** [comment]
Does it work in 17.5 like expected?
