### ISSUE TITLE
neho screenshot uploader fails with latest build

### ISSUE THREAD

**Issue by D4edalus** [callofduty4x/CoD4x_Server#152]
HELO request at plugin start does not reach the webserver, body is empty

https://cod4x.me/index.php?/forums/topic/1392-174-update/

**Comment by D4edalus** [comment]
was confirmed to work on a windows server
https://cod4x.me/index.php?/forums/topic/1392-174-update/&do=findComment&comment=6261

waiting for logs from stormyy, tbc ..

**Comment by Stormyy** [comment]
I found the issue my application is parsing the data wrong because the contenttype header is wrong.

Did this change? Did work before :S

Anyways as you see here: http://mockbin.org/bin/91ea1646-7ab2-4c3d-9fcd-0cd6e6ceada5/log 
The contenttype header should be named Content-Type instead of contenttype.

**Comment by T-Maxxx** [comment]
@Stormyy Anyways, no idea why it was working before.

**Comment by D4edalus** [comment]
lol, nice bug 🗡

**Comment by Stormyy** [comment]
Apparently it was already fixed in January? https://github.com/callofduty4x/CoD4x_Server/commit/c247f1a600ce5027d65388ebde1279c2a0ef6992

Maybe the last build included a old plugin? idk

**Comment by T-Maxxx** [comment]
Seems not anything was fixed. History of adminplugin's main.cpp says there was no fix since initial commit.

**Comment by D4edalus** [comment]
this is not about the adminplugin, is it?

**Comment by Stormyy** [comment]
Nope (neho?)screenshotuploader plugin

**Comment by D4edalus** [comment]
i was asking / telling that to tmaxx since the commit he was referring to has from that other plugin

**Comment by D4edalus** [comment]
@Stormyy did you try a recent version of the plugin?

**Comment by T-Maxxx** [comment]
@D4edalus Yep, that's not our plugin but I have fixed all I can find in there.
@Stormyy Sorry, but you have to ask neho(?) to update his plugin as it's his fault. Anyway, thanks for finding this out.

**Comment by Stormyy** [comment]
@D4edalus @T-Maxxx I tried compile the screenshot plugin from the source and it works now ;). Don't know why it stopped working earlier but ok :S

Anyways thanks for the help!
