### ISSUE TITLE
Gsc arraySearch function

### ISSUE THREAD

**Issue by MichaelHillcox** [callofduty4x/CoD4x_Server#153]
Would it be possible to get some array functions in cod4x. arraySearch( needle, haystack ) comes straight to mind but things like arrayPush, arrayPop, arrayReverse, arrayReplace, arrayMerge, etc would all be super handy for people working with GSC functions.

**Comment by T-Maxxx** [comment]
```C
for (i = 0; i < arr.size; i++)
    arr[i] = ...
```
At least 10 years people accessing arrays' values by its indexes and everything was fine. Until now.
You have about 5000+-few thousand ticks between each frame. Thats enough for any array operation (+ other game logic). Otherwise, you should refactor your code.
Why you ever need it?

**Comment by MichaelHillcox** [comment]
I knew this would be the most instant reply. I've been working with GSC for more than 10 years now. This is something I knew more than I should. I'm speaking from a point of shit being useful. Yes, every time I want to search an array I could do it like that. Hell, I could even just write my own function in GSC but something thats based on the Core side of the game will always be more efficient that it would be using GSC. You can cause issues with GSC very simply when you've got to much going on in a large loop.

This is purely a quality of life request, as are all of the other functions I put in the first question. Hell, you're a programmer. What would you prefer to do every time you want to search an array:
```C++
// GSC's way 
for( a = 0; a < array.size; a ++ ) {
      if( array[a] == requestedItem ) 
               doLogic();
}
```

Or 

```C++
if( arraySearch( "hi", array ) ) 
    doLogic();
```

**Comment by D4edalus** [comment]
"I could even just write my own function in GSC" - that's exactly what you should do.
Optimizing for the sake of optimizing is not a good idea. You can cause much worse issues with C code. If your implementation runs slow use a better algorithmic approach. Quicksort for example, if you want to sort a whole array. Your argument about code becoming simpler is just wrong, writing a sorting function in gsc abstracts that away just as good.
