### ISSUE TITLE
Missing our server cod4 search

### ISSUE THREAD

**Issue by Tomtam21** [callofduty4x/CoD4x_Server#154]
Hello Ninja!
We have a hungarian sever, name: COD4 Oregek  Ip:37.221.209.130:29012
Our this server and lot of hungarian server haven't find inside the game search.
Join game , join server, source internet cod4x  and refresh and we dont appear in the list. Few days have a update in cod4, since have this problem.
Please help because many players dont search our server.
Thanks for your help.

**Comment by D4edalus** [comment]
your server is not even listed on the cod4x masterserver. so the problem you are describing with your client is actually a problem of your server and maybe our masterserver. did you check the server log for errors?

**Comment by Tomtam21** [comment]
Yes, we was list on the cod4x masterserver but since the autoupdate lot of hungarian server missied, disapper listed on the cod4x masterserver.
We dont changed nothing our server config.

**Comment by D4edalus** [comment]
not changing anything doesnt mean that its still working. the cod4x masterserver and communication to it has evolved alot with the latest updates. check your logs.

**Comment by Tomtam21** [comment]
I found a script error. I corrected . After the map is restarted, I'll see what's in the log

**Comment by Tomtam21** [comment]
No results. We continue on Wednesday. I'm going to Germany

**Comment by AlexanderCurl** [comment]
Add this in your config: set sv_masterservers "cod4master.cod4x.me;cod4master.doszgep.cloud"
After that restart your server and check the results.

**Comment by Tomtam21** [comment]
Hello! We add our config: set sv_masterservers "cod4master.cod4x.me;cod4master.doszgep.cloud" and restart but we didnt appear the the cod4x masterserver list. 
We think the problem dont our config because lot of hungarian server dont appear in the list too.
And have so hungarian team  which one their server appear (TDM)  , another their server (SD) dont appear on the list.

**Comment by AlexanderCurl** [comment]
All of my servers are appeared, and hungarians.

**Comment by Tomtam21** [comment]
Your servers i see, but this another hungarian servers missing on the list:
  COD4 Oregek  37.221.209.130:29012
 Nyaradi & {A.G.T} Lofasz![HC-TDM] |@SLHosting.eu  213.181.201.175:28960
<<[Hungary -[SD]- Gaming Team]>> pwd by SLhosting 213.181.201.175:23008

But the Hungary Gaming Team another server (TDM) appear on the list:
<<[Hungary -[HC]- Gaming Team]>> -NO GL:MD:LS - 213.181.201.175:23004

**Comment by IceNinjaman** [comment]
Well we need complete log from screenoutput when server is running with launchoption "+set developer 1".

**Comment by Tomtam21** [comment]
Hello
The problem was solved. Server build 2040. We updated the server 2050. It works perfectly
Thanks for the help
TomTom
