### ISSUE TITLE
Same slotnumber using ipv4 and ipv6 connection 2 people.

### ISSUE THREAD

**Issue by AlexanderCurl** [callofduty4x/CoD4x_Server#155]
Hi.
I haven't got log yet, but my wife said as well, she didn't find a player with b3.
I spotted yesterday a hacker in my SD and wanted to ban him, I didn't find either.

I went to the gamepanel, checked with $ministatus, I found the hacker uses ipv6 connection and a same slotnumber as an another player. I used a slotnumber to ban him, because it's faster, but I banned a wrong person 👎 .

With the hacker name worked.

Edit might be not the slotnumber caused, That is just guessed thats why the B3 doesn't see some players on the servers. And yes, i'm using b3hide plugin.

**Comment by D4edalus** [comment]
this repository is not covering b3 or b3hide. could very well be that the b3 parser fails on ipv6 addresses, but thats really not a problem to be solved in the cod4x server.

**Comment by IceNinjaman** [comment]
2 times same slotnumber in $ministatus is impossible as it is a 
for(i = 0; i < sv_maxclients->integer; ++i){  printf("slot %d", i);  }

loop. Every slot can appear only once. However the output function which sends printed text to the client is buggy. If there is a problem it is on this part.

**Comment by AlexanderCurl** [comment]
Closed, solved the issue with the noew b3hide plugin.
