### ISSUE TITLE
mach header files

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/CoD4x_Server#157]
Clean Ubuntu i386, out of box, VMWare virtual machine. I have followed installation instructions but there's no "mach" header files so I'm asking to update how-to section.
![image](https://cloud.githubusercontent.com/assets/7836454/26175417/47451a70-3b5b-11e7-9834-2b628fa43a5b.png)

**Comment by D4edalus** [comment]
i believe those headers are to find somewhere on osx machines. dont think you can make that work on ubuntu.

**Comment by T-Maxxx** [comment]
Oh. That might be because I just picked all the .c files in "src/unix". Should recheck that.
