### ISSUE TITLE
ddos?

### ISSUE THREAD

**Issue by icekobrin** [callofduty4x/CoD4x_Server#158]
https://puu.sh/vVm6U/df6ed6c4c4.png
sv_queryIgnoreMegs = 1
sv_queryIgnoreTime = 2000
udp dump http://dropmefiles.com/yfRqe

**Comment by T-Maxxx** [comment]
Yep. Seems, like a fake player DDOS.

**Comment by icekobrin** [comment]
All server slots are blocked.
https://puu.sh/vW6WU/7c5a5d2d3f.png
Can not connect to the server.
https://puu.sh/vW5nA/66e3603103.jpg 
https://puu.sh/vW5o9/eb55fc7aac.jpg
Judging by udp traffic. This is a new version of the fooke player.

fix ddos
https://github.com/callofduty4x/CoD4x_Server/pull/159
One minus. Busy one slot always.
