### ISSUE TITLE
New "official" Cod4X maps

### ISSUE THREAD

**Issue by PureTryOut** [callofduty4x/CoD4x_Server#16]
As suggested by @IceNinjaman in #5, it would be a cool idea to turn some high quality custom made maps to official Cod4X maps, possibly provided in the base client download as well.

I make this issue to make a list of maps that are going to be added. Do note that we need permission by the map makers to use their maps as official Cod4X maps.

First a question @IceNinjaman and @D4edalus, do you guys want ports or remakes from other Call of Duty's (like MW2 and MW3), completely custom maps (not from other games), or a combination of both?

**Comment by PureTryOut** [comment]
I got permission to use [Bakaara](https://www.youtube.com/watch?v=IpsqKQTV8Q0) and [Seatown](https://www.youtube.com/watch?v=Ew7j4_NBVcc) (both MW3 maps) by Izartax, I have proof if needed.

**Comment by IceNinjaman** [comment]
Nice but knowing this maps.
Still what I am not sure about is: How do we distribute them? For many a large download of all maps could be a no go I think.
Also an issue are maps using custom assets which replace stock assets inside their shipped .iwd file.

**Comment by PureTryOut** [comment]
> Also we can not provide for everyone large file downloads as our infrastructure can not handle this

Good call... Would it be possible to setup a batch of servers for this? So the client, when it doesn't find the maps installed, will contact a masterserver which will act as a load balancer. It would divide the downloaders overal several servers, hosted by multiple people. I for one am willing to setup my server to do this, and I guess more people are. This way the load is spread, and it should be possible to handle it better. Not sure if this is possible in anyway though.

> Also an issue are maps using custom assets which replace stock assets inside their shipped .iwd file

Can't these just be downloaded as well?

**Comment by florczakraf** [comment]
> and I guess more people are

Yup. We would be happy to provide mirrors for Europe and North America.

> Also an issue are maps using custom assets which replace stock assets inside their shipped .iwd file.

Can't you force the server to load maps from `./usermaps/` without a mod? So the _\*.iwds_ would be included only if particular map is loaded (in opposite to putting them in `./main/` and _\*.ff_ files in <pre>./zone/<i>language</i>/</pre> -- the oldschool way of adding maps without a mod :wink:)

> How do we distribute them?

On demand. I see it like this:
##### For server side
On server startup there's check for `sv_maprotation`, if there are any maps on the list that are not physically on the server, server gets them from the _Map Repository_.

##### For client side
Just a normal download redirect. (Set default `sv_wwwbaseurl` to the _Map Repository_)

Where _Map Repository_ is a load balancer.

**Comment by PureTryOut** [comment]
So seeing this has no progress whatsoever, I'm not sure if it's a good idea to let Cod4X provide new "official" maps. It's just too much of a hassle (for now anyway) to distribute the maps.

It would be easier to just make a seperate config option (something like `sv_custommaps 1`) to allow servers to run custom maps, without running mods. For now these servers could still show up as modded on the serverlist, but at least they won't require you to upload a mod to the players as well.
Later a new filter could be added to the serverbrowser of the client to filter out modded maps as well.

**Comment by T-Maxxx** [comment]
Mod required for client to download custom maps running on servers as well.

**Comment by PureTryOut** [comment]
Is there any progress on this? To me it looks like adding a cvar to allow custom maps without mods would be the easiest. I guess the client has to be changed so it activates map downloading without a mod as well, but this can probably be done somehow.

**Comment by IceNinjaman** [comment]
Not yet.

**Comment by T-Maxxx** [comment]
Half a month no progress. @IceNinjaman you working on this? If no, please close this issue.

**Comment by PureTryOut** [comment]
Every once and while I come back to CoD4 and think about this again. I would still love to see this. Either new official maps or allowing to run custom maps without mods. There are some very high quality remakes of maps from newer CoD games that I would love more people to play.

I don't think it's a good idea to close issues that have no progress for a while. Issues should be closed only when it's resolved, the issue is invalid or a duplicate. Now people might think that the issue is resolved while it's clearly not.
