### ISSUE TITLE
xbase_00.iwd is not getting downloaded

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/CoD4x_Server#160]
I'm testing makefile for incremental building and all missing files are downloaded except this one which makes it impossible to start server for newcomers.
Latest master. You can try yourself with `make -fmakefile2`

**Comment by icekobrin** [comment]
https://pastebin.com/raw/rgicui0g

**Comment by T-Maxxx** [comment]
@callofduty4x/dev Maybe it's time to include whole dedicated server binary as array of bytes and link it statically?

**Comment by D4edalus** [comment]
xbase contains more than just the server binary (certificates, packaged plugins)

**Comment by T-Maxxx** [comment]
Yea, I know. For now it contains nothing as its not getting downloaded with latest build. (tested just now).
![image](https://cloud.githubusercontent.com/assets/7836454/26645893/6081ad86-4642-11e7-9da7-cd4d4ff67bdd.png)

**Comment by D4edalus** [comment]
apparently due to the missing certificate. for the enduser this shouldnt be a problem has he is required to download the server package from the website initially.

**Comment by T-Maxxx** [comment]
@D4edalus Then we have to notify user somehow.

**Comment by D4edalus** [comment]
the typical serverhoster shouldnt tamper with the xbase file imho. those who do see the certificate error in the console - sadly its not directly linked to the download issue. 

if the certificate error would show something like "error - failed to download xbase.iwd" it would be perfectly clear.

**Comment by IceNinjaman** [comment]
xbase_00.iwd does not get downloaded to prevent failing autoupate. At one time it will be included again. Certificates in xbase_00.iwd is not very smart. On client it uses the OS root certificate storage.
