### ISSUE TITLE
tomcrypt not building in travisci

### ISSUE THREAD

**Issue by D4edalus** [callofduty4x/CoD4x_Server#164]
ERROR: https://travis-ci.org/callofduty4x/CoD4x_Server/builds/237840275#L377
https://github.com/callofduty4x/CoD4x_Server/blob/master/src/tomcrypt/makefile

updating the build config for travis didnt cut it:
https://github.com/callofduty4x/CoD4x_Server/blob/master/.travis.yml#L30

so i've restored the previously used build scripts for libtomcrypt
https://github.com/callofduty4x/CoD4x_Server/blob/master/src/tomcrypt/compile_linux.sh
https://github.com/callofduty4x/CoD4x_Server/blob/master/src/tomcrypt/compile_win32.cmd

before removing necessary files check if everything is working next time please! i managed to fix the appveyor build myself (the botlib was another problem there).

**Comment by T-Maxxx** [comment]
Clearly because of "-Imath" flag. Not sure why `gcc` ignores this instruction.

**Comment by D4edalus** [comment]
dont know either. travisci swallowed it after installed libtommath-dev:i386 .. but that shouldnt be necessary. 

its still not running but one step closer ..

**Comment by T-Maxxx** [comment]
Not a problem. Makefile produces lib called "libtomcrypt.a" no matter what OS. Try with `makefile2`

**Comment by D4edalus** [comment]
isnt that _win32 _linux suffix wrong?
https://github.com/callofduty4x/CoD4x_Server/blob/master/makefile#L6

compare to this
https://github.com/callofduty4x/CoD4x_Server/blob/master/src/tomcrypt/makefile#L1

might also be wrong with limbedtls then ..

**Comment by T-Maxxx** [comment]
I made mbedtls and tomcrypt makefiles produces libraries according to makefile for incremental building (to lower build time in case of debugging).
https://github.com/callofduty4x/CoD4x_Server/blob/master/makefile2#L34

**Comment by D4edalus** [comment]
so thats not even supposed to work with the makefile? sigh

should we maybe move such coding adventures to new branches in future :p ? it kinda stalls everyone else on the mainbranch otherwise

**Comment by T-Maxxx** [comment]
Coding in different branches is like keeping project code clean, justified and bugless :P
Now, when I'm executing `mingw32-make -fmakefile2` in root directory, new makefile firstly invokes make utility inside mbedtls and tomcrypt dir producing both `libmbedtls.a` and `libtomcrypt.a` with some nice build process output. Then it compiles server binary and links these two libraries. At this point I have fully working server binary (as usual).
Old makefile, `makefile` just seeks `libtomcrypt_<OS>.a` (or something like this) which has been produced by old build scripts (which I was deleted and forgot). This name mismatch was the reason for second build fail whereas first was because of botlib.

**Comment by D4edalus** [comment]
thanks for explaining it, i tried it ( on linux ) and failed. the windows build ( for appveyor ci ) works, however its still using the old buildscript for now.

makefile2 isnt working on my local virtual machine for linux. 
make -f makefile2
anything special parameters i need?

https://pastebin.com/1Wi33cGC

**Comment by T-Maxxx** [comment]
Lol. Saw same weird `cdecl` warning response from user some time ago under one of my commits.
What is your GCC version?

**Comment by D4edalus** [comment]
4.9.2

**Comment by D4edalus** [comment]
looks similar with 4.6.2 on travisci
https://travis-ci.org/callofduty4x/CoD4x_Server#L546

**Comment by T-Maxxx** [comment]
https://gist.github.com/T-Maxxx/9c6a845b893ec9bf218ef30aa0725647
I'm a bit pissed off now because I'm using 5.4.0...

**Comment by D4edalus** [comment]
on another note .. appveyor also doesnt like your makefile2 for windows

https://ci.appveyor.com/project/D4edalus/cod4x-server/build/1.0.343#L713

what does that line do?
https://github.com/callofduty4x/CoD4x_Server/blob/master/makefile2#L134

**Comment by T-Maxxx** [comment]
Just echoing current operation. I'm trying to figure out best way to determine OS now...

**Comment by D4edalus** [comment]
i believe its just ./comp.cmd instead of comp.cmd ... but i cant test it as appveyor refuses to read my config file now lol

**Comment by T-Maxxx** [comment]
I'm on `makefile2` branch now testing...

**Comment by D4edalus** [comment]
appveyor is building again

**Comment by AlexanderCurl** [comment]
Yeah, that's fine, but travis fuckedup again :(

**Comment by D4edalus** [comment]
appveyor with a small problem as it seems .. 
@T-Maxxx https://ci.appveyor.com/project/D4edalus/cod4x-server/build/1.0.352#L833 
any idea if thats relevant?

**Comment by T-Maxxx** [comment]
Must be used as `cod4x18_dedrun.exe` but I'm following makefiles' `dir/target.extension: dir/source.extension` rule. This is just a warning, not a error. That's fine, I'm getting it on Windows too.

**Comment by AlexanderCurl** [comment]
The windows bin looks good.

**Comment by T-Maxxx** [comment]
Got it working! :D
https://ci.appveyor.com/project/D4edalus/cod4x-server/build/1.0.353#L713

**Comment by AlexanderCurl** [comment]
Nice, but what about the travis build then? :)

**Comment by D4edalus** [comment]
@T-Maxxx as i said in that message 15 minutes ago i got it working already back then.
./comp.cmd was my solution

**Comment by T-Maxxx** [comment]
Oh... Are you sure it places .o files in correct directory?

**Comment by D4edalus** [comment]
well .. it wouldnt build on appveyor otherwise i guess

**Comment by AlexanderCurl** [comment]
Thank you your commit @T-Maxxx :D :D :D :D
https://ci.appveyor.com/project/D4edalus/cod4x-server/build/1.0.354#L697

**Comment by T-Maxxx** [comment]
@AlexanderCurl That was supposed to be a commented out line, but my VSCode decided to justify it *facepalm*

**Comment by AlexanderCurl** [comment]
yes, that's what I though, why is it commented out, that's neccesary libs before compile the whole source.

**Comment by AlexanderCurl** [comment]
Waow, I'm so confused now then :D We managed to compile it in the morning with @D4edalus, and it was commented out before, but still failing as I seen.

**Comment by D4edalus** [comment]
we are able to compile it everywhere, but decided to update it right away to the latest buildscripts.

**Comment by AlexanderCurl** [comment]
Fine, check it out then. 🤦‍♂️

**Comment by T-Maxxx** [comment]
Got both CI systems working. Merge `master` with `makefile2` whenever you ready.
https://ci.appveyor.com/project/D4edalus/cod4x-server/build/1.0.361
https://travis-ci.org/callofduty4x/CoD4x_Server/builds/238129324

**Comment by AlexanderCurl** [comment]
Yupii :) 💯

**Comment by D4edalus** [comment]
nice :)

**Comment by D4edalus** [comment]
i was also looking for the problem and found it a bit after you

make -n ( to show the executed commands by make ) was my key to success

**Comment by T-Maxxx** [comment]
I'm using `make -prRn` :)
