### ISSUE TITLE
deprecation of PlayerCmd_GetSpectatorClient 

### ISSUE THREAD

**Issue by D4edalus** [callofduty4x/CoD4x_Server#165]
https://github.com/callofduty4x/CoD4x_Server/blob/6c8a207b4eb59c0089dd8e4a024e038782a7da7b/src/scr_vm_functions.c#L3134

this change will break some peoples scripts if released like this, should at least be deprecated before removed fully!

**Comment by T-Maxxx** [comment]
Did not get your point. There will be script error with specified message instead of "error: unknown function".

**Comment by D4edalus** [comment]
nvm
