### ISSUE TITLE
IPv6 port conflict when running two server at IPv4 on same ports

### ISSUE THREAD

**Issue by IceNinjaman** [callofduty4x/CoD4x_Server#171]
IPv6 port conflict when running two server at IPv4 on same ports.

**Comment by Kingwolf123** [comment]
You mean to say that if 1 server is binded to ipv6 and another to ipv4, (both the same port) they will conflict?

**Comment by icekobrin** [comment]
http://puu.sh/w8Mb9/6df2815867.png

**Comment by T-Maxxx** [comment]
OSI model, layer 2. If both IPv4 and IPv6 addreses are bound to same physical interface (assuming same 28960 port), you may get packet overlapping so OS shows you warning (address in use).

**Comment by IceNinjaman** [comment]
When I run a server for example on 164.132.116.108:28960 and a second server on 164.132.116.109:28960 so I have different IPv4 addresses but share the same IPv6 address and use the same port. Unless I configure ipv6 also to use two addresses or 2 different ports. Most won't do that and will just complain.

**Comment by T-Maxxx** [comment]
Just use different ports for servers and everything will be ok.

**Comment by T-Maxxx** [comment]
There's no issue from my point of view and I think it can be closed.

**Comment by Kingwolf123** [comment]
Ideally servers on ipv4 and ipv6 should be treated separately.

**Comment by T-Maxxx** [comment]
@Kingwolf123 
One interface with both IPv4 and IPv6 adresses.
Server A - IPv4
Server B - IPv6
Both servers are belong to same interface. Give me answer - how to detect if packet was addressed to server A and not to server B and vice verse?

**Comment by IceNinjaman** [comment]
Well the only solution is to let the server just try different ports on the IPv6 address until one is working. This results weird unpredictable auto-port configurations as the IPv6 port goes random. Servers saved as favorite would change name or goes up and down depending on restarts. However it just stops admins from complaining that CoD4X shit doesn't work or is buggy.

**Comment by D4edalus** [comment]
so in the end only one of the two servers is reachable via ipv6. not a big deal, is it? to fix it both servers should manually set net_ip6. i dont think thats a big deal.

**Comment by T-Maxxx** [comment]
@D4edalus Nope. If two different IPv6 points to the same interface - OS will not be able to differ destination of packet. (for same ports). So my suggestion is use anything you want but make sure it's on different ports.

**Comment by T-Maxxx** [comment]
Closed because this is not an IP issue but issue with ports. And changing ports will become a solution.
