### ISSUE TITLE
Master->Server IP:Port feedback

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/CoD4x_Server#174]
I suppose anyone behind NAT met situation when your friends can't connect through steam to your lobby. Or directly to your server by IP.
Custom master server has static IP so theoretically it can function like STUN server. When a heartbeat packet received from server, master adds source ip:port to its list and sending this list to each client with `getServersResponse`. Why not send some kind of "heartbeat response" contains ip:port back to server? If admin has dynamic IP, even if behind different types of NAT admin will see that his server registered on master successfully. Using this IP client can connect to server for the first time.

**Comment by Kingwolf123** [comment]
The ability for cod4x servers behind NAT to reach public clients.... sign me up dude.

**Comment by proxict** [comment]
Discussion moved to #412
