### ISSUE TITLE
My hud is gone.

### ISSUE THREAD

**Issue by Acedoni** [callofduty4x/CoD4x_Server#175]
When i play the game i dont have the map or crosshair etc

**Comment by cyberplant** [comment]
You're probably playing on hardcore servers. It's normal and not related to cod4x. 

Check here: http://callofduty.wikia.com/wiki/Hardcore

**Comment by T-Maxxx** [comment]
@Acedoni type "/devmap mp_backlot" in console after launching game and confirm there's no hud for you.
