### ISSUE TITLE
/usr/bin/ld: cannot find -lbot

### ISSUE THREAD

**Issue by Alirezaies** [callofduty4x/CoD4x_Server#177]
Hello
I have followed the intstructions for compiling, after using `make linux32` I get `/usr/bin/ld: cannot find -lbot`

I'm using Ubuntu 16.04 LTS and latest CoD4x from github

**Comment by T-Maxxx** [comment]
Please, use `make -fmakefile2`. We're still testing and improving new makefile.

**Comment by k4r3l01** [comment]
when i use make -fmakefile2 and i try to run builded server so server downloads official version of server

**Comment by k4r3l01** [comment]
So i have news about that problem is makefile2 ignore args debug=true i must edit makefile2 and force build type without official and now everything works

**Comment by T-Maxxx** [comment]
`DEBUG=true` is case sensitive.

**Comment by k4r3l01** [comment]
I know i writed this via mobile i writed this like you write

**Comment by T-Maxxx** [comment]
Makefile updated, please read "How to compile" information.
