### ISSUE TITLE
"makefile2" Ignoring "DEBUG" command

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/CoD4x_Server#178]
@k4r3l01 

* when i use make -fmakefile2 and i try to run builded server so server downloads official version of server
* So i have news about that problem is makefile2 ignore args debug=true i must edit makefile2 and force build type without official and now everything works
* DEBUG=true is case sensitive. debug and DEBUG is different variables. Try again.
* I know i writed this via mobile i writed this like you write

Please, provide information about `make` utility, used OS and exact command line you're using to build server.
On my side everything is fine (Windows, mingw, `mingw32-make -fmakefile2 DEBUG=true`).

**Comment by k4r3l01** [comment]
I using os debian for building and i tried make - fmakefile2 DEBUG=true and i also tried to rename makefile2 to makefile and use make DEBUG=true and its same for me build is still official

**Comment by D4edalus** [comment]
DEBUG=true worked for me
