### ISSUE TITLE
GSC Json support?

### ISSUE THREAD

**Issue by MichaelHillcox** [callofduty4x/CoD4x_Server#179]
### Feature request
Just a nice idea for things like caching or storing large data outside of the games internal arrays. There is more benfits from having Json support :) You've already got the open, read, write, etc for files so adding json support would be pretty simple, from what I can remember Json has a C lib you could use.

Basic functions in GSC a bit like PHP.
`jsonEncode(<array>) // converts an array struct to a json format`
`jsonDecode(<json>) // converts a json string to a array struct`

You'd also need to be able to read an entire file into the `<json>` part and thats not something you can currently do with the `FS_` stuff.

**Comment by T-Maxxx** [comment]
Purpose? Using JSON for large data is not good thing actually. There's base64 en-/decoding already there.

**Comment by MichaelHillcox** [comment]
Caching was the better of the two given use cases.

**Comment by D4edalus** [comment]
i'm sure it would have its use. comparing json with base64 is apples and oranges. this seems more like something that should be done in a plugin. personally i prefer mysql and rest interfaces to gsc, as that holds the possibility open to distribute your servers across multiple machines (versus holding it in local files). 
@MichaelHillcox what usecases do you have in mind? "caching" is very general, and i think you mean "storing".

**Comment by MichaelHillcox** [comment]
Caching, Storage, Basically the same thing. I would for my use case be using it to store our post request calls data to a json file to temp store the data for that specific game. As you well know when the round changes the whole game does a basic restart so storing data like ViP Status, Rank, etc would mean having X players * rounds * games to the server and thats too many to have so I'd cache the result so it turns into players * game. Much nicer :P 

But other use cases would be as you said, Storage, So you could store player data server side. Something like this.
```json
[
      "<player guid>": {
             "rank": "123",
             "xp": "321123",
             "pres": "2",
             "unlocks": [...]
      }
]
```
Thats just one thing I could think of using it for. You could use it as a better way to store server settings like the .cfg ( most games are now using .json instead of .cfg ). Etc, etc. It's just a much better way of storing and getting data then saving it to a raw file and then looping over every line is. You could throw the json file back through the encoder / decoder and have a ready to use built array of data of your storage. 

I think what I'm trying to say is that .json would be a much better way to store data in general. Super happy to have file ability at all but the next logical step is to give it a deeper integration with better storage types. Hell, if you want to really make the storage of the game powerful then use something like SQLlite or any other flat file based SQL langs that are out there. Very powerful storage that can all be done on the game level and not having to contact your mysql server. Etc.

**Comment by D4edalus** [comment]
thats exactly what databases are for. we dont need to reinvent the wheel for that. if you dont like the rigidity of sql use a no-sql database like mongodb. using a database is much more flexible as it gives you the opportunity to do non trivial queries and the flexibility of concurrent access - thats not funny with files.
if you think that this is much too complicated for your use, and you just want to cache some values use a redis server, its pretty much made for that purpose.

**Comment by MichaelHillcox** [comment]
How do you suggest I do any of those things when CoD4x does not support anything but mysql of which me and a friend where the creators of until one of your team made it a cod4x18 plugin. 
Sure I'd love to use redis and mongodb but cod4x has no support for it. Thanks for suggesting an impossible solution. Although, mysql is a possibility but something like mongodb would be much preferred.

**Comment by D4edalus** [comment]
https://github.com/callofduty4x/cod4x_plugin_http

there is also a http plugin that lets you access anything that speaks http. use any language of your choice to wrap a webservice with it. it even has a json store to access rest apis easily.

**Comment by MichaelHillcox** [comment]
This just allows for a bottleneck. You can't compare a shitty http ( which also doesn't support ssl ) plugin to having direct access to a mangodb or mysql intergration and the same goes with json.

**Comment by D4edalus** [comment]
not that i'd care, but what do you need ssl for if your gameserver and webservice run on the same system?
well then .. start coding.
