### ISSUE TITLE
Falling back to the latest update server provided bin.

### ISSUE THREAD

**Issue by AlexanderCurl** [callofduty4x/CoD4x_Server#183]
If you compile the binary yourself, the updater "update" the bin to the updater latest present all the time.

**Comment by D4edalus** [comment]
thats the expected behaviour. 
https://github.com/callofduty4x/CoD4x_Server/blob/master/makefile#L7

**Comment by AlexanderCurl** [comment]
ive tried with the debug as well, didn't work.

**Comment by T-Maxxx** [comment]
@AlexanderCurl Updater can not work in debug version as it contains no code to download something.

**Comment by D4edalus** [comment]
my bad, its NOT working. my vm simply wasn't able to contact the update server. 
building with `make DEBUG=true` still autoupdates the server on startup

**Comment by D4edalus** [comment]
https://github.com/callofduty4x/CoD4x_Server/blob/master/src/sec_update.c#L788 this is working
but the OFFICIAL define is not (un)set by the makefile with DEBUG=true

**Comment by AlexanderCurl** [comment]
@T-Maxxx yeah i've used the debug switch wrong at the first time. Solved.
