### ISSUE TITLE
cod 4 server crash!!!

### ISSUE THREAD

**Issue by beast321khan** [callofduty4x/CoD4x_Server#191]
hi everyone...

i am having some prob with my cod 4 game v1.8...
The prob is that my game crashes whenever i try to join a server giving an error saying cod4 stopped working...

The game works fine with 1,7 patch but crashes when updated to 1.8 when  joining a server

HELP PELEASE

**Comment by Kingwolf123** [comment]
Stop using hacks .

**Comment by T-Maxxx** [comment]
Not a forum
