### ISSUE TITLE
Game Binary Initialization Failed

### ISSUE THREAD

**Issue by RedMist1201** [callofduty4x/CoD4x_Server#192]
Is it typical error that is supposed to happen? Because when I typed in console "extract" it gave 
" Bad command or cvar: extract "
https://gyazo.com/ab6abdbf8e42fcd131875ca0f7ed9ddb
I am attaching link to original mod so you can open that mod yourself and if you are more lucky, then could send the outcome to me :)
https://goo.gl/u6YVTN

**Comment by T-Maxxx** [comment]
Missing main/xbase_00.iwd or no reading rights for this file on this account.
Redownload pack from forum main page.  https://cod4x.me/downloads/cod4x_server-windows.zip

**Comment by RedMist1201** [comment]
https://goo.gl/Z1ZWuC Still doesnt like the console command
