### ISSUE TITLE
steam_api + plugins == crash at exit

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/CoD4x_Server#195]
Windows.
I'm using `Sys_LoadLibrary` function to load plugins. The problem happened when I'm loading plugin dll after steam_api.dll and shutting down server. Result is:
![image](https://user-images.githubusercontent.com/7836454/32792287-1081ff6a-c974-11e7-8754-2ff759f04063.png)
"Very" informative isn't it?
My bet is steam_api not properly unloaded at server shutdown. Why steam_api? I tried to load and unload plugin without this library and everything was fine. 
What is this file? What is this purpose? Where I can get its source code?

I will patch Sys_*Library functions to properly handle multiple libraries a bit later.

**Comment by T-Maxxx** [comment]
Nope, unloading steam_api.dll not helped at all. Worth mention that loading 2 plugins worked properly.

**Comment by T-Maxxx** [comment]
@callofduty4x/dev Any response?

**Comment by D4edalus** [comment]
next to the client repo

**Comment by D4edalus** [comment]
works just fine with single and multiple plugins + steam_api.dll
