### ISSUE TITLE
Bots' improvemed movement.

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/CoD4x_Server#20]
Made it while ago for 1.2 version. I can make it there but it'll take some time for me to disassemble required functions. What do you think? Is it a good idea or not?
[Youtube](https://www.youtube.com/watch?v=XPdf4L6p_Cc)

**Comment by PureTryOut** [comment]
That is cool, it's stupid that bots couldn't do that in the first place. Could we see general bot AI  improvement overall in Cod4X? It would be good to not need Pezbots anymore in the future for proper bots.

**Comment by T-Maxxx** [comment]
It is hard to write bots AI using gsc, even harder with C. And this movement under control of gsc scripts.

**Comment by T-Maxxx** [comment]
So? You want these features or not?

**Comment by D4edalus** [comment]
Sorry i was offline this week :)
So this would be functions that can be executed on a player via gsc to
perform all the possible movement styles? Leanleft/leanright, crouch, jump
whatever?

2016-07-11 5:56 GMT+02:00 Max <notifications@github.com>:

**Comment by T-Maxxx** [comment]
Yes. You spawn bot as usual using command line or gsc scripts and then you use something like "self moveforward()" and bot begin move. Unfortunately, this commands will not work for players.

**Comment by D4edalus** [comment]
sounds like a nice feature. i haven't yet experimented with bots in any way. but i always disliked that i need pezbots mod to test the simplest features. guess it would be nice to have the option to improve the AI :)
maybe somebody is motivated to develop an AI plugin in the future. :+1:

**Comment by PureTryOut** [comment]
Is this confirmed to be implemented in the future? Currently seems to be a bit dead as there is no confirmation yet

**Comment by T-Maxxx** [comment]
I don't know. Still waiting for confirmation...

**Comment by IceNinjaman** [comment]
How are you going to do that? Emitting usercmd packets into the SV_ClientThink() function every frame? That is what I'd prefer here so it looks like a real player moves them. I think Quake3 bots work over the same function.

**Comment by T-Maxxx** [comment]
Yes.

**Comment by IceNinjaman** [comment]
Would be nice if you could do it then.

**Comment by IceNinjaman** [comment]
Okay I have commited the functions IW used to move bots. So you should have it easier now.

**Comment by T-Maxxx** [comment]
Just tested movement. Its ok.
From the other hand, function called each server frame(20 times per second) so its impossible to make smooth bot rotation. Smooth like its 250 FPS ofc.

**Comment by T-Maxxx** [comment]
There is something weird with angles in usercmd. I can't identify its units. On screenshot you can see its value in integer and there should be rotation for 180 degrees from current origin but in fact there is <10 degrees actually in game.
The game shows extremely small numbers(XXe-41) when i'm grabbing values from player usercmds.
![image](https://cloud.githubusercontent.com/assets/7836454/17552567/51f52f98-5f09-11e6-8b8c-9baaeac24402.png)

**Comment by T-Maxxx** [comment]
Its direction is not constant and somehow related to spawn direction. (Sometimes 0 its west sometimes its not).

**Comment by IceNinjaman** [comment]
Well in the alpha xbox version of CoD4 its a 3 dimensional int vector.
I can examine the binary again and see if that offset in usercmd_t struct is making sense.

**Comment by IceNinjaman** [comment]
Well I am quite convinced that it is right as it is:
http://img.i-g.ninja/489ccdd8471eadb9d7732187112809c6

angles starting at offset 0x8

**Comment by T-Maxxx** [comment]
Yes, its 3 dimensional short int vector but only LOWORDs are in use.

**Comment by T-Maxxx** [comment]
Wasted 2 or 3 days because of wrong 65535-0 and 0-65535 ucmd angles transitions.
[Youtube](https://www.youtube.com/watch?v=Kxg4Noip-uI)

**Comment by IceNinjaman** [comment]
Nice you got that to work!

**Comment by PureTryOut** [comment]
That looks awesome! Soon we can have proper bot matches lol

**Comment by T-Maxxx** [comment]
I just added function for prediction player movement so bots looks a bit overpowered now ^^.
[Youtube](https://www.youtube.com/watch?v=1nUkB7rkLl4)

**Comment by PureTryOut** [comment]
Except for the horrible desync you seem to be having, that is amazing! Maybe eventually a setting could be added for bot difficulty, ranging from very easy to hard like this. That would make proper bot matches possible.

Do you know what is up with that desync though?

**Comment by IceNinjaman** [comment]
Any idea why in killcam it looks like he is so much time off? Do you really use the current servertime and not something old when sending usercmds?

**Comment by T-Maxxx** [comment]
ucmd.serverTime zeroed [at line 10](https://gist.github.com/T-Maxxx/27be7d47c060018673849785a652b066), I'm not touching it. Scripts and killcam are from vanilla CoD. 
Thats everything I'm doing for bots for now. (And looks like thats all I need.)

**Comment by T-Maxxx** [comment]
ucmd.serverTime = Sys_Milliseconds() didn't help.
Maybe this is because game still thinks its 1k ping for bot? (lag icon present) And all actions looks like 1 second faster than actual shots fired.

**Comment by IceNinjaman** [comment]
ucmd.serverTime = svs.time; 

I am wondering how you can hit at all when you provide a so much wrong server time.

**Comment by T-Maxxx** [comment]
It hits perfect but impacts on demos and killcams.
Done. No desync anymore.

**Comment by IceNinjaman** [comment]
Whole time server is running for in milliseconds. Most stuff uses it as base. It's resolution is only serverfps however. Time is constant during each frame where Sys_Milliseconds() isn't.

**Comment by IceNinjaman** [comment]
Does it still show the disconnected icon?

**Comment by T-Maxxx** [comment]
No.

**Comment by T-Maxxx** [comment]
So, don't you want to accept #45? It's ready and I want to focus on something more important.

**Comment by PureTryOut** [comment]
Do you have a video of the bots without desync btw? Or what commands would I need to run to get such a bot in a private game running your PR?

**Comment by T-Maxxx** [comment]
No, I haven't.
You can use my [_globallogic.gsc](https://gist.github.com/T-Maxxx/ee3303fbff02bdcbc1873872aa91105d#file-_globallogic-gsc-L3967) with empty mod.

**Comment by D4edalus** [comment]
that is very cool stuff! i have pulled it to a separate branch for now as it is a lot to look over.
