### ISSUE TITLE
upgrading a rent 1.7 server??

### ISSUE THREAD

**Issue by Dave-Dean** [callofduty4x/CoD4x_Server#201]
Hey guys,

tried now for 2 weeks to update/upgrade my rent 1.7 server (rent on g-portal.com) to 1.8 from cod4x and maybe I just cant but I refuse to believe that. First I did not know that I have to get the CoD4x Server Modification "https://github.com/callofduty4x/CoD4x_Server#setting-up-a-call-of-duty-4-server-with-cod4x-18" but in the process while compiling it just gets me an error. Now am I even able to update to 1.8 if g-portal may not support it? And if so how? I dont know any thing about scripts, code or else. I just wanna have a cod4\-x Server for me and my friends with final killcam, new hardpoints and playercards without using mods :/

If this is the wrong place to ask for help, I am sorry :(

**Comment by D4edalus** [comment]
cod4x.me is our forum. questions like this one belong there. If you have ftp access to your server you might be able to exchange the executable. there is no point in compiling it on your own, get it here: https://cod4x.me/ -> Linux Server. 

closed. go to the forum, there might be even people having a g-portal server themselves if you are lucky.
