### ISSUE TITLE
Remove Antinamechange,antinamesteal,clan-tag plugins from tree

### ISSUE THREAD

**Issue by Kingwolf123** [callofduty4x/CoD4x_Server#203]
Since the functionality is implemented in the base server. there is no need for these plugins.
Pull them from the source tree ?
As for clan-tag , we have steam groups, so we don't need it anymore.

**Comment by D4edalus** [comment]
yeah i'd say they are rather useless now. are they even compiling still?

**Comment by Kingwolf123** [comment]
Have not tried.
But doesnt matter i guess. since they dont offer anything new .

**Comment by Kingwolf123** [comment]
Yeah.
name stealing is not alllowing the namechanger hack people use to avoid being banned.
The hack frequently changes the name of the player to other players.

**Comment by D4edalus** [comment]
oh, from that point of view you are right yes :)

**Comment by D4edalus** [comment]
https://github.com/callofduty4x/CoD4x_Server/issues/205

**Comment by Kingwolf123** [comment]
Move the clan Protection to deprecated, but the other two really have function at all.. unless you just want them there.
