### ISSUE TITLE
Plugin Maintenance

### ISSUE THREAD

**Issue by D4edalus** [callofduty4x/CoD4x_Server#205]
- [x] Check if all plugins are compiling
- [x] Rename "cpp test" to "example plugin" or something else more expressive
- [x] Compile the Plugins with Appveyor CI service
- [x] Compile the Plugins with Travis CI service
- [x] Move deprecated Plugins to /plugins/plugins_deprecated

**Comment by Kingwolf123** [comment]
I actually had the same thought about moving plugins to deprecated, but when i read the code,  i realized this is just part of the server.. so the plugin should be removed.
The first 4 points are valid tho.

**Comment by D4edalus** [comment]
antinamechange plugin is clear, that was against namechanging bots and can be removed. 
antinamesteal also works against namechanger bots, but can also just prevent duplicate names on the server.
you can also use clantag protection plugin for clan tags written into the names if you prefer that. i mean why not. hence why i'd move antinamesteal and clantagprotection to deprecated.
legacybanlist could be moved to deprecated as well i think

**Comment by Kingwolf123** [comment]
@D4edalus Check pull request.

**Comment by D4edalus** [comment]
https://github.com/callofduty4x/CoD4x_Server/commit/8396128c8deca8a524567016a099723fb22706cc

**Comment by Kingwolf123** [comment]
1- PChat plugin has missing windows compile script. Compiles on windows with added script.
2- warn has missing windows compile script . When i compile on windows, has missing function error(does not compile as well ).
3- webapibanlist has missing linux compile script. Does also not compile for me on linux.

**Comment by Kingwolf123** [comment]
@D4edalus You cant compile antispam plugin because i noticed in travis you are using makedll.sh. The file compile script is named makeSO.sh . Other than that its pretty standard.

**Comment by D4edalus** [comment]
@Kingwolf123 no worries, this is not a problem with your plugin code. The problem are compiler versions. Your plugin requires c++17 which has limited support on older distros. The build server for example uses Ubuntu 12, I can install gcc 6 on the fly, but not the gcc multilibs (which are required on a x64 system, as the server is 32bit). 
i am sure there is a solution to that problem, but i am not willing to currently invest time into it. Also just solving the problem and switch everything to gcc 6 doesn't make much sense as cod4 servers often run on much older OSes. 
If you want to target that problem try to solve it in a pull-request please, because those are built by the CI system too, and you will see if your build script is working. For that just edit the travis.yml, seeing what to change to build your plugin inside that file should be straight forward for you to see.

**Comment by Kingwolf123** [comment]
Ok yeah its nothing big. Leave it as be.
