### ISSUE TITLE
Add ban function for new plugin system

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/CoD4x_Server#213]
- [x] ~Add support for `RemoveBanByIP`~
- [x] ~Add support for `AddBanByIP`~
- [x] ~Add support for `IsPlayerBannedByIP`~
- [x] ~Add support for `GetBanInfo`~

~Please, remember that some plugins can be made as proxy for ban system. So all this (original) functions must also invoke other plugin's events. Double check for potential loops. (function - dispatcher - event - function - dispatcher - ...)~

Right now I don't see any reason to add ability to invoke ban functions from plugins. Events (response to actions) - yea, definetely must be included. Then plugin can act like a ban list.

**Comment by volkv** [comment]
@T-Maxxx Макс, а можно ли добавлять бан из скриптов от имени конкретного админа? (альтернатива "exec(permban...", где бан идет от консоли. у меня просто админы банят через игровое самописное меню). Нужно плагин писать через который передавать всю инфу?
