### ISSUE TITLE
Add doxygen support

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/CoD4x_Server#215]
- [x] ~Learn how to use doxygen.~ I was tired when wrote that lol.
- [x] Add comments to trap_* plugin functions.
- [x] ~Make generated docs deployable to wiki page.~
- [ ] Prepare description of toolchain used to generate git book
- [ ] Place git book to a github page (master branch + docs directory)
- [ ] Add rule to makefile to generate docs.

**Comment by D4edalus** [comment]
i suppose that would make sense for everything thats usable in plugins
i haven't ever used doxygen with travis-ci, but if we have doxygen autodeploying the docs to github pages might be worth looking at https://gist.github.com/vidavidorra/548ffbcdae99d752da02

**Comment by D4edalus** [comment]
having a c++ docs to markdown (as our other docs are in markdown too) would be dope for commands and variables. if any of it should be generated automagically it should probably go into a seperated repository (or branch). 

https://sourcey.com/generating-beautiful-markdown-documentation-with-moxygen/

**Comment by D4edalus** [comment]
https://gist.github.com/vidavidorra/548ffbcdae99d752da02
