### ISSUE TITLE
Cannot watch old cod4x16 demos

### ISSUE THREAD

**Issue by Xdar** [callofduty4x/CoD4x_Server#222]
When trying to watch old cod4x demos with the new client the following error appears:
Can not playback demo. Demo support for protocol version 16 not installed. Maybe you can install a DemoPlayPack to gain support for this control.

Please fix this error or provide an old cod4x18_v16_0_client download so people can watch old demos.

Thanks.

**Comment by Kingwolf123** [comment]
This is not a forum.
Report on [(https://cod4x.me/index.php?/forums/forum/3-cod4x-client/)] Forums

**Comment by Xdar** [comment]
Yes, I would if cod4x forum registration would work.
I tried both gmail and hotmail, got not verification E-Mail.
I also wrote you an E-Mail on the contact us form on the site but no reply or anything.

**Comment by AlexanderCurl** [comment]
Did you check your "SPAM" directory?
