### ISSUE TITLE
Cod4x forum registration not working.

### ISSUE THREAD

**Issue by Xdar** [callofduty4x/CoD4x_Server#223]
I tried both gmail and hotmail, got not verification E-Mail.
I also wrote  an E-Mail on the contact us form on the site but no reply or anything.
Probably don't see the answer on the closed issue so I try contact you guys so here.

**Comment by Kingwolf123** [comment]
Have you checked the spam folder?

**Comment by Xdar** [comment]
Yes, I did. No E-Mail. I also tried the send verification option again after 15 minutes and still didn't get any E-Mail.

**Comment by AlexanderCurl** [comment]
Confirmed, the MTA doesn't work boiz.

**Comment by AlexanderCurl** [comment]
Working, can be closed now.

**Comment by D4edalus** [comment]
magically started working again
