### ISSUE TITLE
Turn on Size And speed optimizations for compiler

### ISSUE THREAD

**Issue by Kingwolf123** [callofduty4x/CoD4x_Server#225]
I looked at makefile today. Saw that debugging flags -g are enabled.
When i disabled those, my executable went from 4.002 MB to 1.7MB. Quite a difference.
Why are they on anyway?

Also the optimization flags were -O0, i turned them to O3 and noticed some warnings in the build process, but none the less when i tested the exe it was working pretty good.

Using i686-7.2.0-release-posix-dwarf-rt_v5-rev1 i was also able to significantly reduce the size of the plugin libraries. Sourcebans moved from 140kb to 97kb.
Also plugins compiled with MinGW become large in size when c++ standard library is used (due to static linking of the library).

The antispam plugin on MinGW is 855kb, on the newer compiler i was able to achieve a neat 180kb file size.Similarly, trueskillplugin went from 900kb to 226 kb.

I think we should standardize use of a version of mingw-64 for compilation of release builds,
And prohibit use of older compilers(in case of plugins)

**Comment by D4edalus** [comment]
to have debug information when they crash (which the master branch does, alot)

**Comment by Kingwolf123** [comment]
I know that. Im saying cant we do this for the next release build..
And for plugins.

**Comment by D4edalus** [comment]
we could, yes. but errors are much harder to track then.

**Comment by Kingwolf123** [comment]
Okay.
What about making newer compilers mandatory, because of the difference in sizes.

**Comment by D4edalus** [comment]
so we break compilation on distros that dont have gcc 7 for the gain of a few megabytes .. which are pointless anyways because the gamedata has multiple gigabytes to put that in perspective.

**Comment by Kingwolf123** [comment]
Im talking about windows...(Mingw-64). Linux doesnt need this. And no we dont have to use gcc 7. we can use older versions 5.4 as well(whatever suites you) They also have this size advantage. Otherwise.. well this thread was just supposed to be a discussion anyways. Cheers
