### ISSUE TITLE
GSC interpreter

### ISSUE THREAD

**Issue by myuce** [callofduty4x/CoD4x_Server#234]
I've been wondering if it's possible for you to release a seperate version of the GSC interpreter since it is more advanced than other GSC-like script interpreters and i would like to embed it on different software and maybe games (q3 possibly).

**Comment by shit-ware** [comment]
I would be interested in a GSC interpreter.

**Comment by D4edalus** [comment]
The original gsc interpreter is not modified, and not even reversed. Recently some preprocessor directives have been added (on code level), but I think that's it. What are you interested in specific? All we have on this topic can be found in this repository.

**Comment by T-Maxxx** [comment]
I believe LUA is better solution. Open source, easy to implement, [easy to learn](http://tylerneylon.com/a/learn-lua/).

**Comment by D4edalus** [comment]
for a new project there is definitively better choices to be made than using gsc.
