### ISSUE TITLE
brush

### ISSUE THREAD

**Issue by k4r3l01** [callofduty4x/CoD4x_Server#240]
Its will be possible to make brush or something solid blockade for fixing bugs on custom maps via gsc scripting

**Comment by T-Maxxx** [comment]
Brush must exist on both server and client to prevent desync (small flickering when you stand on top of it - client thinks there's nothing here when server blocks movement). So it requires massive client patch including server-to-client brush position update (like using configstrings).

Right now you can use `cloneBrushmodelToScriptmodel` script function with bombsite entity - the most known script_brushmodel which exist on most of custom maps.

https://www.youtube.com/watch?v=efp6wbwbdPo

**Comment by k4r3l01** [comment]
i know about spawn  trigger_radius that works to be solid by setcontents(1) but its circle :( i need block with custom dimensions :(

**Comment by T-Maxxx** [comment]
Sorry, but adding a collideable brush will require massive hooks to internal map storage (where lumps are located) from both server and client. I guess, only guys from aIWNet team knows how to achieve that.
