### ISSUE TITLE
Add testclient SwitchToWeapon functionality

### ISSUE THREAD

**Issue by ineedbots** [callofduty4x/CoD4x_Server#243]
Currently, testclients cannot switch to any weapons (gsc SwitchToWeapon).

There is a workaround for this by using SetSpawnWeapon(), but this ignores the pull up and down anims.

**Comment by T-Maxxx** [comment]
Confirmed

**Comment by ineedbots** [comment]
I wrote a workaround for IW4x

https://github.com/XLabsProject/iw4x-client/pull/40/commits/f8a1c649ccfe5fe0a816df002444b65087df870f



Looks like this might be the reason
https://github.com/callofduty4x/CoD4x_Server/blob/master/src/sv_main.c#L4090
