### ISSUE TITLE
Not able to Login or register an new account.

### ISSUE THREAD

**Issue by BestNoob** [callofduty4x/CoD4x_Server#269]
https://cod4x.me/index.php?/register/

Sorry, there is a problem

Something went wrong. Please try again.
Error code: EX0

**Comment by wkuzma** [comment]
i cannot even get to https//cod4x.me for the past two days. Is the web site down?

**Comment by wkuzma** [comment]
also the http://cod4master.cod4x.me/ gives this error 
2019 Copyright. All Rights Reserved.

The Sponsored Listings displayed above are served automatically by a third party. Neither Parkingcrew nor the domain owner maintain any relationship with the advertisers.

Privacy Policy

**Comment by k4r3l01** [comment]
probably yes because i have same issue

**Comment by AlexanderCurl** [comment]
Can be closed now @T-Maxxx

**Comment by BestNoob** [comment]
Not really, i still get:

Sorry, there is a problem
Something went wrong. Please try again.

Error code: EX0

**Comment by Thurrax** [comment]
Yep same here.

**Comment by BestNoob** [comment]
@T-Maxxx wtf ? Why do you close issues that are **NOT** solved ? I tracked your history and you closed a lot issues that are not solved, also in forums xD ? Is this a obsessive compulsive disorder ?

**Comment by T-Maxxx** [comment]
"also in forums". Can you provide proofs? Please.

**Comment by T-Maxxx** [comment]
Still EX0
