### ISSUE TITLE
Why no PunkBuster and stream to GGC & PBBans ?

### ISSUE THREAD

**Issue by BestNoob** [callofduty4x/CoD4x_Server#270]
PunkBuster, GGCStream & PBBans support also modded games because it doesnt matter as long as PB is fully integrated into the mod and not modified/blocked by it.

So tell me why dont you host your Servers with Streaming to catch cheaters ?

**Comment by k4r3l01** [comment]
i think its probably because punkbuster for cod4 not exist anymore and force players to install 3rd app is stupid idea this will kill this great game

**Comment by T-Maxxx** [comment]
Not exactly. CoD4X client itself works exactly like a hack. So if we will give PB/GGCStream ability to scan user games - all our players would be banned because they're "cheaters".
