### ISSUE TITLE
Can´t run openwarfare mod

### ISSUE THREAD

**Issue by merj4n** [callofduty4x/CoD4x_Server#272]
Hi, i compile the last version and i can't run this mod, when i put the server.cfg file in mod folder, server can´t load this file, but when i put the file in main folder, this work but the rest of the mod dosn't work, can be possible that this mod is not compatible?

**Comment by kreator-eb** [comment]
Do you have a correct startup command line, is your server configured properly first, the config location doesnt matter as long as it in the cod4 root files and is named the same as the name.cfg in the startup of the server. You need to describe more so we can help, does the mod launch on the server, where are the issues and so on.

**Comment by merj4n** [comment]
> Do you have a correct startup command line, is your server configured properly first, the config location doesnt matter as long as it in the cod4 root files and is named the same as the name.cfg in the startup of the server. You need to describe more so we can help, does the mod launch on the server, where are the issues and so on.

Thanx for your answer, i fix it the problem, i realized later that my server is Linux and is case sensitive and when i put the command line "fs_game mods/xxxx" i need "fs_game Mods/xxxx", finally openwarfare mod work fine.
