### ISSUE TITLE
Error in `./cod4x18_dedrun': double free or corruption (!prev): 0x1812a238 ***

### ISSUE THREAD

**Issue by dulkith** [callofduty4x/CoD4x_Server#274]
-----------------------------
 CoD4X Auto Update
 Current version: 1.8
 Current subversion: 17.8
 Current build: 962
-----------------------------

New subversion 17.8
Downloading file: "main/xbase_00.iwd"

Successfully downloaded file "main/xbase_00.iwd".
Writing file to /home/ogp_agent/OGP_User_Files/mod_support/main/xbase_00.iwd.new
Failed to open /home/ogp_agent/OGP_User_Files/mod_support/main/xbase_00.iwd.new
Error: Opening "/home/ogp_agent/OGP_User_Files/mod_support/main/xbase_00.iwd.new" for writing! Update aborted.
]*** Error in `./cod4x18_dedrun': double free or corruption (!prev): 0x188f5238 ***                                                                This program has crashed with signal: Aborted
The current Gameversion is: CoD4 X - linux-i386 type 'e' build 962 Mar 12 2019
File is ./cod4x18_dedrun Hash is: 07375141faf7048aadf125bb7fa8b93bca871715b84d4b68297ed30aa970ecfa
---------- Crash Backtrace ----------
   17: ./cod4x18_dedrun(Sys_PrintBacktrace+0x31) [0x809a893]
   16: ./cod4x18_dedrun(Sys_DumpCrash+0x92) [0x809a96e]
   15: ./cod4x18_dedrun(Sys_SigHandler+0x24) [0x809a9e4]
   14: [0xf7786410]
   13: [0xf7786440]
   12: /lib/i386-linux-gnu/libc.so.6(gsignal+0x47) [0xf73f0687]
   11: /lib/i386-linux-gnu/libc.so.6(abort+0x143) [0xf73f3ab3]
   10: /lib/i386-linux-gnu/libc.so.6(+0x68fd3) [0xf742afd3]
    9: /lib/i386-linux-gnu/libc.so.6(+0x734ca) [0xf74354ca]
    8: /lib/i386-linux-gnu/libc.so.6(+0x741bd) [0xf74361bd]
    7: ./cod4x18_dedrun() [0x80a0bf0]
    6: ./cod4x18_dedrun(FileDownloadFreeRequest+0x12) [0x80a4735]
    5: ./cod4x18_dedrun(Sec_Update+0x522) [0x81066a3]
    4: ./cod4x18_dedrun(Com_Init+0x30f) [0x80df89a]
    3: ./cod4x18_dedrun(Sys_Main+0x51) [0x80a6657]
    2: ./cod4x18_dedrun(main+0xf9) [0x809a69c]
    1: /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0xf73dbaf3]
    0: ./cod4x18_dedrun() [0x8099063]

**Comment by AlexanderCurl** [comment]
Remove your xbase_00.iwd and start cod4x server, it will be fine.
