### ISSUE TITLE
Hit registration off on win servers build 983.

### ISSUE THREAD

**Issue by efinst0rm** [callofduty4x/CoD4x_Server#278]
Hey,

Since I updated our servers from 2055 to the 938 all my players are reporting awful hit registration on the server. Is there anything I can use to help debug the issue.

**Comment by IceNinjaman** [comment]
Look at this thread please: https://cod4x.me/index.php?/forums/topic/3408-hit-detection-registration-issues/

**Comment by efinst0rm** [comment]
Thanks. I'm the one that started the thread.

**Comment by proxict** [comment]
Is this issue still relevant?

**Comment by efinst0rm** [comment]
Yup issue was fixed.
