### ISSUE TITLE
screenshot sender plugin issue

### ISSUE THREAD

**Issue by erfanasbari** [callofduty4x/CoD4x_Server#288]
Hello, yesterday i downloaded cod4 status and installed it on my web server.

i setup everything but when i used **loadplugin nehoscreenshotuploader** it says:
**Error: Init failure. Cvar nehoscreenshot_identkey or nehoscreenshot_url is not set
Error in plugin's OnInit function!
Plugin load failed.**

but i set both of them in my server.cfg

then i saw this
https://github.com/callofduty4x/CoD4x_Server/blob/14d0a7cc5233a09bfd765fba2b50b1102d3dfbdc/plugins/screenshotsender/main.c#L30

and in next line it was:
https://github.com/callofduty4x/CoD4x_Server/blob/14d0a7cc5233a09bfd765fba2b50b1102d3dfbdc/plugins/screenshotsender/main.c#L31

i checked some other plugins and i realized that it must be like this:    **static cvar_t *identkey;**. not this _static cvar_t* identkey;_

so i downloaded the https://github.com/callofduty4x/CoD4x_Server/blob/master/plugins/screenshotsender/ plugin and fixed main.c file.

but i dont know how to compile it.
please someone compile this https://ufile.io/hsri7keo plugin and upload it for me
pleeeeeeeeeeeeeeeeeeeeease

**Comment by K-Faktor** [comment]
https://mega.nz/#!lSZ3UKII!zaLvbKGu60pNA0_x5g61DaXTwwwBvfD2EWACPBzpIuY

**Comment by proxict** [comment]
Not a server issue.
