### ISSUE TITLE
Limit vote types

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/CoD4x_Server#292]
Add feature to disable certaing voting types using dvars.

**Comment by proxict** [comment]
Already possible with `g_voteVoteGametypes`, `g_voteKickMinPlayers`, `g_voteMaxVotes`, `g_voteAllowMaprotate`, `g_voteAllowKick`, `g_voteAllowGametype`, `g_voteAllowMap`, `g_voteAllowRestart`.
