### ISSUE TITLE
Sourcebans NOT working misspelled﻿ in xbase_00.iwd 

### ISSUE THREAD

**Issue by BestNoob** [callofduty4x/CoD4x_Server#295]
SOURCEBANS is NOT usable because the PLUGIN inside xbase_00.iwd is misspelled "sourecbans" instead of "sourcebans"﻿

> No such file found: plugins/sourcebansplugin.dll. Can not load this plugin.
> Error: Init failure. Sourcebans backend script said: Error: Empty rcon value
> Error in plugin's OnInit function!
> Plugin load failed.

Doesnt work when i write "loadplugin sourecbansplugin" and also when i rename the plugin inside xbase_00.iwd

**Comment by T-Maxxx** [comment]
> Error: Empty rcon value

**Comment by BestNoob** [comment]
> 
> 
> > Error: Empty rcon value
> 
> Set "rcon_password" dvar in you config file before loading plugin.

Nope dude nope ..... didnt solved it .. =(

**Comment by Koajakins** [comment]
https://github.com/callofduty4x/CoD4x_Server/pull/298 - Filename fixed.
