### ISSUE TITLE
cod4x18_dedrun_dbg.exe is NOT usable

### ISSUE THREAD

**Issue by BestNoob** [callofduty4x/CoD4x_Server#296]
cod4x18_dedrun_dbg.exe is NOT usable it just crashes all the time, doesnt matter i load a standard server.cfg or not, while execing server.cfg 

> Problemsignatur:
>   Problemereignisname:    BEX
>   Anwendungsname:    cod4x18_dedrun_dbg.exe
>   Anwendungsversion:    0.0.0.0
>   Anwendungszeitstempel:    5c87f775
>   Fehlermodulname:    StackHash_5861
>   Fehlermodulversion:    0.0.0.0
>   Fehlermodulzeitstempel:    00000000
>   Ausnahmeoffset:    PCH_1F_FROM_ntdll+0x0003C8EC
>   Ausnahmecode:    c0000005
>   Ausnahmedaten:    00000008
>   Betriebsystemversion:    6.3.9600.2.0.0.272.7
>   Gebietsschema-ID:    1031

**Comment by T-Maxxx** [comment]
Suffix "_dbg" points to debug build. Where did you get that file?

**Comment by BestNoob** [comment]
> 
> 
> Suffix "_dbg" points to debug build. For debug build crashes are normal. Where did you get that file?

Inside the official CoD4x Windows Server .... so this is a suicide .exe file ? Just creating a log and "dies" ?

**Comment by T-Maxxx** [comment]
Most likely its continue execution until breakpoint reached. And since you have no debugger attached - crash is a result.
Use release version.
