### ISSUE TITLE
pleace fix/update sourcebans for actual version

### ISSUE THREAD

**Issue by BestNoob** [callofduty4x/CoD4x_Server#297]
Would be nice if you can update the fork or actual sourcebans version to work with CoD4x as example the IMPORT of banlist doesnt work =(

https://github.com/callofduty4x/CoD4x_Server/wiki/Banlists-in-version-15.9--and-other-changes

https://sbpp.dev/docs/inquiries/

> 
> Web I accidently locked myself out by having Steam only login, how can I fix this?
> 
> Using a database query tool (Ex: PHPMyAdmin), goto _settings table and modify config.enablesteamlogin setting and set the value to 1

**Comment by Koajakins** [comment]
https://github.com/callofduty4x/CoD4x_Server/pull/298

**Comment by Koajakins** [comment]
Above has been merged @BestNoob for now, you can manually rename the sourcebansplugin so that it is named correctly. Next build it will be resolved for all
