### ISSUE TITLE
Server Violation: Extra IWD Files Detected

### ISSUE THREAD

**Issue by bbashy** [callofduty4x/CoD4x_Server#302]
Getting "Server Violation: Extra IWD Files Detected" with Promod and latest cod4x files.

This happens locally and dedicated servers. How do I fix this? It didn't happen when there was just the xbase_00.iwd but there's also the jcod4x_00.iwd file now and it looks like pure checks were added back https://github.com/callofduty4x/CoD4x_Server/commit/dd8d6372e89679caf065e0c98d95ffb6ec88f975 but that shouldn't affect it?

![screenshot_2020-05-31_15-53-21-597](https://user-images.githubusercontent.com/1149200/83355163-8a88f300-a355-11ea-9b08-007e66bc341f.jpg)

**Comment by IceNinjaman** [comment]
Fixed on masterbranch for now. Thank you Bashy.
