### ISSUE TITLE
relocation error GLIBCXX_3.4.15 not defined in libstdc++.so.6

### ISSUE THREAD

**Issue by Orthus** [callofduty4x/CoD4x_Server#308]
I'm trying to run the dedicated server on the following device:

4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

and getting this error during startup:

./cod4x18_dedrun: relocation error: ./steam_api.so: symbol _ZNSt8__detail15_List_node_base7_M_hookEPS0_ version GLIBCXX_3.4.15 not defined in file libstdc++.so.6 with link time reference

This is very odd as I was able to run the dedicated server less than 4 months ago with no issues and no apt-get upgrade or apt-get dist-upgade.

I have attempted the solution from 4 years ago of removing libstdc++ but doing so would cause issues and break commands like apt-get.

Edit: I also noticed after this error, I get a lot of ctrl + H spam in my screen.

**Comment by AlexanderCurl** [comment]
Server version? Did you try to put the runtime folder contents into the cod4 server root folder?

**Comment by Orthus** [comment]
It is running server version 18 I believe. But I was able to get it running, as I noted a copy of libgcc in the server folder, I renamed it via adding .disable (to see if it was an issue due to conflicting local version and system version) to the end of file name and verified my system copies of libgcc and libstdc++ were up to date and the server started fine.

**Comment by Orthus** [comment]
Just to ensure the steps for my solution are documented for anyone who has this issue in the future.

Verify You do not have copies of libgcc or libstdc++ as they may conflict with versions from your distro, or in-general cause issues with server.

**Comment by D4edalus** [comment]
hi, thanks for sharing your experience. in the past we've had issues with some linux distros not providing valid installation candidates for libstdc++ with the required GLIBXX version. as you found out, the file can be safely removed from the server directory for most distros.
