### ISSUE TITLE
cod4x.me is down again

### ISSUE THREAD

**Issue by Davy1992** [callofduty4x/CoD4x_Server#318]
Website has been down for a while now, which prevents users from installing the patch.

**Comment by CaptainFrostty** [comment]
I can second this.

**Comment by UsmanTariq2** [comment]
Yup. Coudnt install it on a new pc and cant find the zip file for the patch. Can someone upload it and link it ?

**Comment by Davy1992** [comment]
Closing you can find more info here #320
