### ISSUE TITLE
Status about the site and infrastructure is unreachable

### ISSUE THREAD

**Issue by IceNinjaman** [callofduty4x/CoD4x_Server#320]
Since this seems to be the only way now to give you some information I will try it on this way now:

As you all know the site cod4x.me is down and not reachable. It isn't the case I have given up onto the project. Just the domain is expired on the domain registrar. Normally I would just renew the domain. However it isn't going to work as usual. The domain registrar has added 2-factor authentication for sign in, asking for a code he sends in an email. However the email account (powered by Google) can not be accessed by me anymore although I have all the informations like username and password. Basically Google says I hack the account and they don't let me in. Also the deny account recovery by saying they don't have ever got enough information to do any account recovery.
So at this point I can only wait in hope it does maybe get accessible again for me. Only Google knows if I can access it maybe again at a later time. Losing the domain entirely would have terrible consequences as the whole update system does reley onto it.

**Comment by Davy1992** [comment]
Did you try talking to NameCheap yet? I have a domain with them as well, and I remember the customer service being really good.

They have your personal information (Name, Address, Payment Method) so they should be able to recover your account even without access to your email.

It's worth a try here is a link to their [live chat](https://www.namecheap.com/help-center/live-chat/).

In the meantime is there a way to update CoD4x manually?

**Comment by IceNinjaman** [comment]
I tried it today, but it looks like it isn't gonna work. I have provided made up informations to them on domain registration. This made up informations I seem to not have anymore. The livechat was asking me for the phone number I could not provide. Then I was asked to make a ticket in their risk management department. I feel like this will lead to nothing.

**Comment by Davy1992** [comment]
Well this is quite the predicament, the domain expired 6 days ago so if you're not able to regain access you can always buy it back after it's been released, but that will take time.

Regarding the manual update I am guessing that the [CoD4x_Client_pub](https://github.com/callofduty4x/CoD4x_Client_pub) repo is outdated, so compiling that won't solve my issue. Is there a way you could release the current client for manual update?

**Comment by ZedanDredal** [comment]
Hi Comrade! How can this process be accelerated?
Do you need some help with this issue?

**Comment by ZedanDredal** [comment]
> Поскольку сейчас кажется, что это единственный способ дать вам некоторую информацию, я сейчас попробую это сделать следующим образом:
> 
> Как вы все знаете, сайт cod4x.me не работает и недоступен. Это не тот случай, когда я отказался от проекта. Просто у домена истек срок действия на регистраторе домена. Обычно я бы просто продлил домен. Однако это не будет работать как обычно. Регистратор домена добавил двухфакторную аутентификацию для входа, запрашивая код, который он отправляет по электронной почте. Однако учетная запись электронной почты (на базе Google) больше не доступна для меня, хотя у меня есть вся информация, такая как имя пользователя и пароль. В основном Google говорит, что я взламываю учетную запись, и они не пускают меня. Также отказывают в восстановлении учетной записи, говоря, что у них никогда не было достаточно информации, чтобы выполнить восстановление учетной записи.
> Так что на данный момент я могу только ждать в надежде, что он, возможно, снова станет для меня доступным. Только Google знает, смогу ли я получить к нему доступ, возможно, снова позже. Полная потеря домена будет иметь ужасные последствия, поскольку вся система обновлений полагается на это.

****

> Since this seems to be the only way now to give you some information I will try it on this way now:
> 
> As you all know the site cod4x.me is down and not reachable. It isn't the case I have given up onto the project. Just the domain is expired on the domain registrar. Normally I would just renew the domain. However it isn't going to work as usual. The domain registrar has added 2-factor authentication for sign in, asking for a code he sends in an email. However the email account (powered by Google) can not be accessed by me anymore although I have all the informations like username and password. Basically Google says I hack the account and they don't let me in. Also the deny account recovery by saying they don't have ever got enough information to do any account recovery.
> So at this point I can only wait in hope it does maybe get accessible again for me. Only Google knows if I can access it maybe again at a later time. Losing the domain entirely would have terrible consequences as the whole update system does reley onto it.

Hi Comrade! How can this process be accelerated?
Do you need some help with this issue?

**Comment by wkuzma** [comment]
Since the  registrar has added 2-factor authentication for sign in, asking for a code he sends in an email.  is it possible to change the email to get the code? (just a thought)
Hopefully you will get it up and running

**Comment by wkuzma** [comment]
Just another thought: When my domain expired and before I renewed it I was able to get to my web site by it's direct ip address
is that possible with your web site?

**Comment by AlexanderCurl** [comment]
> is that possible with your web site?

No is not possible, that is for security reasons.

**Comment by Davy1992** [comment]
> Just another thought: When my domain expired and before I renewed it I was able to get to my web site by it's direct ip address
> is that possible with your web site?

Like @AlexanderCurl mentioned you can't access the website directly, but you can circumvent the DNS by adding
`194.67.202.194 cod4x.me` to your Windows [hosts file](https://www.freecodecamp.org/news/how-to-find-and-edit-a-windows-hosts-file/).

Just understand that as long as that record exists in your hosts file, your computer will bypass DNS for that record so if the IP of cod4x.me ever changes you will have to update it manually or remove it.

**Comment by wkuzma** [comment]
It was a stupid though on my part since even if I bypassed the dns I more then likely would be the only one or one of very few that would be on the web site. 
I did notice the when I start my server and it gets to the end of the loading it stated registered on the master server. Also the in game internet cod4x loads servers so at lest the master servers are still working. 
I also have a copy of the cod4x_client which shows in game as 19.1 available for download on my web site and hopefully is helping some.

**Comment by wkuzma** [comment]
sorry the copy of the cod4_client is the wrong version on my web site.

**Comment by k4r3l01** [comment]
here you have link to download client version 19.3 https://uloz.to/file/mAwQeZun8UWG/cod4x-client-19-3-zip

**Comment by wkuzma** [comment]
Thank you I will place a copy of it on my web site also.

**Comment by AlexanderCurl** [comment]
cod4x.me is back, can be closed.
