### ISSUE TITLE
Compilation fails on windows

### ISSUE THREAD

**Issue by lumotroph** [callofduty4x/CoD4x_Server#326]
19.4 release, trying to compile under windows 10

compilation goes fine until `tommath`

```
gcc math/bn_fast_mp_invmod.o
math/bn_fast_mp_invmod.c:1:10: fatal error: tommath.h: No such file or directory
 #include <tommath.h>
          ^~~~~~~~~~~
compilation terminated.
mingw32-make.exe[1]: *** [math/bn_fast_mp_invmod.o] Error 1
mingw32-make.exe[1]: Leaving directory `[REDACTED]/cod4server/CoD4x_Server-19.4/src/tomcrypt'
[REDACTED]\mingw\bin\mingw32-make.exe: *** [tomcrypt] Error 2
```

![image](https://user-images.githubusercontent.com/12592541/124983823-c3a39480-e038-11eb-8535-13693d541143.png)

Any ideas?

Can't wait to play this with my old high school friends again :)

**Comment by lumotroph** [comment]
latest fresh `mingw32 `and `nasm`, by the way

**Comment by K-Faktor** [comment]
No problem, the compilation went without errors. Win 8.1 x64  MinGW i686-8.1.0-release-posix-dwarf-rt_v6-rev0
![Снимок](https://user-images.githubusercontent.com/27491186/125014587-6daa0d80-e087-11eb-8b9f-b9b454710ee0.JPG)
[cod4x18_dedrun.zip](https://github.com/callofduty4x/CoD4x_Server/files/6788291/cod4x18_dedrun.zip)

**Comment by lumotroph** [comment]
Alright - must have been on my side, then. I was only doing this while the main site was down :) so we're all good now. 
Thank you!
