### ISSUE TITLE
cod4x 20 update won't work

### ISSUE THREAD

**Issue by gihanrangana** [callofduty4x/CoD4x_Server#329]
after update cod4x 19 to 20 game is getting not responding when start

**Comment by IceNinjaman** [comment]
What has been your game version before this update?

**Comment by Tomtam21** [comment]
Helo
It doesn't work for me.   I had version 19.3 of cod4

**Comment by Tomtam21** [comment]
ups.

helo
It doesn't work for me.  I had version 19.3 of cod4

**Comment by zrbrochnn** [comment]
@IceNinjaman What's new in 20.0? Enlighten us.

**Comment by Tomtam21** [comment]
Helo
With the update, the new device does not work.  Fix: I deleted all updatts from the hidden folder.
 then I copied my backup back.  That's the only way I could solve it.

TomTam

**Comment by zrbrochnn** [comment]
At the moment, there is a problem right now. Several players (who have 19.3) reported that they do not have an Auto-Update button. In addition, they also tried to update the client manually, after which a black screen appeared..

**Comment by Vlad44442323** [comment]
Сука, ты долбоеб конченный, нахуй ты родился на этом свете. Удались нахуй, и пусть тебя ебут программисты. Отсталое хуйло конченное...

**Comment by Vlad44442323** [comment]
Пидарас! Пидарасина...

**Comment by Vlad44442323** [comment]
Idiot, fuck you, dolbaeb

**Comment by Vlad44442323** [comment]
https://youtu.be/KiejQPW8gWY

**Comment by IceNinjaman** [comment]
20.1 should fix it.

**Comment by gihanrangana** [comment]
after update to the 20.1 all issues are fixed
