### ISSUE TITLE
Unable to join server after updating to 20.0 from version 19.3

### ISSUE THREAD

**Issue by sarimmehdi** [callofduty4x/CoD4x_Server#330]
When I try to join a server, I get the  following message:

![cod4x](https://user-images.githubusercontent.com/36595832/127776095-3ff072b7-8860-4282-a092-eaa2f446a9fe.png)

I deleted cod4x_020 in  C:\Users\sarim\AppData\Local\CallofDuty4MW\bin and my version reverted back to the previous one:

![cod4x_my_old_version](https://user-images.githubusercontent.com/36595832/127776114-a4549b48-508b-4b76-afa6-695e205b28c3.png)

But now I get the following error when I try to join a server:

![cod4x_delete_20](https://user-images.githubusercontent.com/36595832/127776126-e15583f5-2e0b-42a2-af8f-f4c18bcc3261.png)

**Comment by IceNinjaman** [comment]
Just join for now any of the available servers. You have to wait. You would need the old cod4x_patchv2.ff that is kinda lost now.

**Comment by zrbrochnn** [comment]
I wanted to ask something. Previously, there was no such problem with ammo in 19.3 (for example in RotU Zombie), but as soon as the server was updated to 20.0, this problem already began.
https://youtu.be/9RP3DaiFjmo

**Comment by GKid94** [comment]
Same
![Call of Duty Modern Warfare Multiplayer_2021 08 03-12 51](https://user-images.githubusercontent.com/18757054/128004152-fe9740b0-d48d-4b6e-9aab-2b14edf3e896.png)

**Comment by diamante0018** [comment]
> Same ![Call of Duty Modern Warfare Multiplayer_2021 08 03-12 51](https://user-images.githubusercontent.com/18757054/128004152-fe9740b0-d48d-4b6e-9aab-2b14edf3e896.png)

Same what? Don't you see you have a different error message? 🤦
