### ISSUE TITLE
error during initialisation. Tried to use a player profile before it was set.

### ISSUE THREAD

**Issue by loboy14** [callofduty4x/CoD4x_Server#334]
after installing cod4x I get this message whenever I try to launch cod 4 multiplayer
error during initialization .tired to use a player profile before it was set. probably a menu bug
![image](https://user-images.githubusercontent.com/89892718/131610171-bb19f5c2-808b-4aea-96a1-2489ec9b969e.png)

**Comment by proxict** [comment]
Not a server issue.
