### ISSUE TITLE
Some Commands crash the Server

### ISSUE THREAD

**Issue by Bladeinio** [callofduty4x/CoD4x_Server#343]
Some Commands I made for the Admin System crash the server via timeout without showing any error in the logfiles. No matter how I write the command it crash's it any time.
Similar commands which have a Similar code but different function work. 

Im using a CoD4 Deathrun Mod.
Commands that are mainly the problem are the following ones:

Spawn
Spawnall

case "spawnall":
            players = getallplayers();
            for(i=0;i<players.size;i++)
            {
                if(isdefined(players[i].pers["team"]) && players[i].pers["team"] == "allies" && players[i].sessionstate != "playing")
                    players[i] thread braxi\_mod::spawnplayer();
                else if(players[i].ghost)
                {
                    players[i] suicide();
                    wait 0.1;
                    players[i] thread braxi\_mod::spawnplayer();
                }
                wait .05;
            }
            iprintln("All ^5Players^7 have been ^5respawned");
            break;

Spawn Command is pretty much the same. Obviously for one player that gets called out by player = getplayerbynamepart(arguments);

Would be amazing if there is a solution.
If needed message me on discord for more information.

Blade #6504

**Comment by leiizko** [comment]
Any error from using script commands will only get outputted to invokers console. You can use cvar "logrcon 1" to output it to server log instead while testing.
