### ISSUE TITLE
Compiling with mingw 11.2 gives the following error 

### ISSUE THREAD

**Issue by UsmanTariq2** [callofduty4x/CoD4x_Server#350]
`src/sys_net.c:111:13: error: conflicting types for 'inet_pton'; have 'int(int,  const char *, void *)'
  111 |         int inet_pton(int af, const char *src, void *dst)
      |             ^~~~~~~~~
In file included from src/sys_net.c:25:
m:\mingw\mingw64\x86_64-w64-mingw32\include\ws2tcpip.h:408:32: note: previous declaration of 'inet_pton' with type 'INT(INT,  const CHAR *, void *)' {aka 'int(int,  const char *, void *)'}
  408 | WINSOCK_API_LINKAGE INT WSAAPI InetPtonA(INT Family, LPCSTR pStringBuf, PVOID pAddr);
      |                                ^~~~~~~~~
mingw32-make: *** [makefile:217: obj/sys_net.o] Error 1`

This some tool problem?

**Comment by UsmanTariq2** [comment]
This message does not occur with [[i686-win32-dwarf](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/8.1.0/threads-win32/dwarf/i686-8.1.0-release-win32-dwarf-rt_v6-rev0.7z)]([i686-win32-dwarf](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/8.1.0/threads-win32/dwarf/i686-8.1.0-release-win32-dwarf-rt_v6-rev0.7z))

But does occur with [GCC 11.2.0 + MinGW-w64 9.0.0 (UCRT) - release 4   (LATEST)](https://github.com/brechtsanders/winlibs_mingw/releases/download/11.2.0-9.0.0-ucrt-r4/winlibs-i686-posix-dwarf-gcc-11.2.0-mingw-w64ucrt-9.0.0-r4.7z) on www.winlibs.com which i was using.

**Comment by AlexanderCurl** [comment]
That is expected, we use older release to compile the code on Windows.
You will need this version instead: https://downloads.sourceforge.net/mingw-w64/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z
And NASM version: 2.15.05
And pexports: https://github.com/callofduty4x/CoD4x_Server/raw/master/tools/pexports-0.47-mingw32-bin.tar.xz

**Comment by UsmanTariq2** [comment]
> Take a look here: https://github.com/callofduty4x/CoD4x_Server/runs/5101692739?check_suite_focus=true Follow the logs, replicate the steps, and you will good to go.
Yeah i did look at that. Just expected it to compile with 11.2 as well lol. I guess not
