### ISSUE TITLE
[Suggestion] Add development environment for vscode and VS

### ISSUE THREAD

**Issue by UsmanTariq2** [callofduty4x/CoD4x_Server#351]
Hey, It would be great help to configure intellisense gdb and other stuff directly with VS code for better coding facility
I can work on this if u want since i am already having great difficulties browsing through the project on vs code etc
Ill update this thread once i have a more compiled list of stuff

**Comment by Kevin-Delnoije** [comment]
I am in the same boat, also got a link error see #357. If you have any progress would love to know.

**Comment by proxict** [comment]
I'd be highly against this. Development environment shouldn't be part of projects. In fact, when excluding them from a project, they should not even be listed in `.gitignore` (usually part of a project to ignore artifacts produced by the project) but in `.git/info/exclude` (not part of projects, used to ignore DE files, and other local settings). There is not only one development environment and maintaining dozens of them doesn't make any sense.
