### ISSUE TITLE
The plugin is not loading

### ISSUE THREAD

**Issue by K-Faktor** [callofduty4x/CoD4x_Server#353]
The antispam plugin does not load on the Windows server

Error: Failed to load the plugin d:\games-cod4\cod4x-server\.callofduty4\plugin.antispam.tmp!
![Без имени](https://user-images.githubusercontent.com/27491186/153708271-9f1d9e83-a5b0-443e-ac80-7a4a4a308cc5.jpg)

**Comment by UsmanTariq2** [comment]
Hey @K-Faktor 
Try deleting the .tmp files that are mentioned and rerun the server.

**Comment by UsmanTariq2** [comment]
Also, This is not a development Issue
So please post issues like this in the plugin section on cod4x.me 

Thanks

**Comment by K-Faktor** [comment]
> Hey @K-Faktor Try deleting the .tmp files that are mentioned and rerun the server.

How to delete it if it is not there, the server did not create it.
