### ISSUE TITLE
Problem with promod

### ISSUE THREAD

**Issue by cjsimo** [callofduty4x/CoD4x_Server#360]
Hello, i tried to build server with standard installation of linuxgsm .

I installed successfully other mods like cj and i can join normally.
For promod i set +set fs_game mods/pml220c

But when i try to install Promod Live 2.20 i can't join for this error:
`Impure client detected. Invalid .IWD files referenced!`

I can join without any problems in others promod server so i think it's a server side problem but i can't fix issue.
Putting sv_pure 0 didn't fix issue , but other servers have sv_pure 1 normally.

Any idea ?

Thank you.

**Comment by uGiFarukh** [comment]
Same problem here. Any idea how to fix this issue?

**Comment by proxict** [comment]
You need to use the original iwd files, not the ones from a random cod4 installation like e.g., the aviara_ro version.

**Comment by TheBinaryShadow** [comment]
This persists for me. Clean files. Checked multiple times.

**Comment by TheBinaryShadow** [comment]
[https://cod4x.ovh/](https://cod4x.ovh/uploads/short-url/59kvOM9hBabZjPJRlLX029BcskI.zip)

I was missing the rest of the files from the zip file!

Warning go to https://cod4x.ovh/ and download the latest release with all the files in the! Releases on GitHub only contain the server executable!

**Comment by proxict** [comment]
@TheBinaryShadow Glad you solved it :)
