### ISSUE TITLE
undefined reference to `gmtime_s' 

### ISSUE THREAD

**Issue by BraXi** [callofduty4x/CoD4x_Server#362]
> gcc bin/cod4x18_dedrun.exe
> lib/\libmbedcrypto.a(platform_util.o):platform_util.c:(.text+0x44): undefined reference to `gmtime_s'
> collect2.exe: error: ld returned 1 exit status
> makefile:198: recipe for target 'bin/cod4x18_dedrun.exe' failed

Using gcc version 6.3.0 (MinGW.org GCC-6.3.0-1) with -fpermissive

**Comment by BraXi** [comment]
#350 fixed problem

**Comment by Muayyad1999** [comment]
glad to see you active again.
