### ISSUE TITLE
Cannot Join Server After Updating To 21.1

### ISSUE THREAD

**Issue by Sampo2910** [callofduty4x/CoD4x_Server#363]
Cannot Join Server After Updating To 21.1 with latest client version 20.6
![2022-05-01 07_21_17-Latest 21 0 - General  - CoD4X Mod Community](https://user-images.githubusercontent.com/62912187/166132105-1ed94297-7cff-4510-9747-87dd02edab0e.png)

Also noticed that the gametype (set as FreezeTag) kept changing to DM. This stops when I revert back to 20.1 So it is nothing 'else'

**Comment by K-Faktor** [comment]
We need to wait until the client is updated to 21 protocols
