### ISSUE TITLE
Expired certificate at https://cod4master.cod4x.ovh/

### ISSUE THREAD

**Issue by maciejwalendziuk** [callofduty4x/CoD4x_Server#368]
Certificate has expired 3 days ago. I would suggest renewing it ASAP.
![image](https://user-images.githubusercontent.com/15122746/168835037-26f71d93-f618-401f-85e1-0dc6e0dd51e5.png)

**Comment by diamante0018** [comment]
This has nothing to do with this repository

**Comment by maciejwalendziuk** [comment]
Still not fixed btw. 2 minute job
