### ISSUE TITLE
help-how to add bots

### ISSUE THREAD

**Issue by rootgithubbeta** [callofduty4x/CoD4x_Server#370]
Hello Can anyone tell me how to add bots without using a mod 

and can anyone tell me how to send server messages

Thank you.

**Comment by lambdagit101** [comment]
technically, without using a mod, you could make a local cod4x server and install bot warfare
otherwise no

**Comment by proxict** [comment]
Not a development issue, please, use the [cod4x forum](https://cod4x.ovh/c/cod4x-server/) to get help with server configuration and modding.
