### ISSUE TITLE
Cod4x Bots Not Functioning

### ISSUE THREAD

**Issue by exeLocates** [callofduty4x/CoD4x_Server#374]
Hello, I'm trying to add bots using cod4x 21.1 to my server
I do addtestclient(); and can put them on a team and spawn them great, but when they spawn they will not use weapons.

Their weaponList() contains many weapons and even force giveWeapon and switchToWeapon will not work, they will never take out a weapon, they just have nothing in their hands.

I see other cod4x servers using bots with weapons and am wondering is there a line of code that enables weapons? I see no difference in my testclient code than in other bot mods that work when i look at their code.

Please help, 

Thank you

**Comment by ineedbots** [comment]
https://github.com/callofduty4x/CoD4x_Server/blob/master/src/sv_bots.cpp#L189

You want to use `bot botWeapon(<weapon_name>)` to have bots use weapons,

Ideally, a patch to playerCmd_setSpawnWeapon and playerCmd_switchToWeapon should be made that sets the bot's weapon correctly there. (but this is currently not the case, you'll have to use `botWeapon`)

**Comment by exeLocates** [comment]
> 

Holy crap thank you so much! you're a life saver!!
