### ISSUE TITLE
Error: Steam library is too old 

### ISSUE THREAD

**Issue by dgibbs64** [callofduty4x/CoD4x_Server#375]
I am trying up update the COD4x build for LinuxGSM since the domain name change requires a manual update. but I am getting the following issue when running the server. Does anyone know where I can get hold of the correct steam_api.so? as it is not very clear.

Thank you

```
Error: Steam library is too old and causes incompatibilities with players who are using Steam with a cod4 license.
```

**Comment by K-Faktor** [comment]
https://cod4x.ovh/downloads/cod4x_server-linux_21.2.zip
