### ISSUE TITLE
log sync is not working

### ISSUE THREAD

**Issue by vikumkbv** [callofduty4x/CoD4x_Server#376]
when we add the log sync option it is not working and automatically overrides to g_logsync 0

Add the following to the server cfg
// Log Settings
set g_logsync "2"
set logfile "1"
set g_log "promod_mp.log"
set sv_log_damage "1"

But this is the config that presents in the q3config_server.cfg (auto-generated file)
seta g_log "games_mp.log"
seta g_logsync "0"

Please fix this b3 is not working due to this

**Comment by AlexanderCurl** [comment]
There is nothing to do with the server, it is scripted in promod to disable logs.

**Comment by K-Faktor** [comment]
All settings are stored in the promod_ruleset/custom_public.gsc script
![custom_public](https://user-images.githubusercontent.com/27491186/172759278-aecf8b22-e6a4-4955-b780-324613f720a0.jpg)

**Comment by K-Faktor** [comment]
The topic can be closed

**Comment by vikumkbv** [comment]
this is with match mode "match_mr12" in mod pml220

**Comment by K-Faktor** [comment]
provide a mod if it doesn't bother you
