### ISSUE TITLE
new web site

### ISSUE THREAD

**Issue by wkuzma** [callofduty4x/CoD4x_Server#377]
This has nothing to do with cod4x  and I am posting it here since I cannot post it anywhere else.
I have tried 6 or 7 times to register on the new web site but have not received an activation email from the new web site.
hopefully someone can look into that problem

**Comment by AlexanderCurl** [comment]
Which profile you want us to activate, as now you having 2. wjkuzma or wkuzma? I can do it for you.
Probably your email provider (comcast) does not like our e-mail solution. I've tested with google, there works fine.

**Comment by wkuzma** [comment]
wkuzma  you can delete the wjkuzma and thank you

**Comment by AlexanderCurl** [comment]
Done, please close the issue. 😊👍
