### ISSUE TITLE
Text animation

### ISSUE THREAD

**Issue by Daxy7** [callofduty4x/CoD4x_Server#384]
Since the first CoD4x version (18), there's been this issue of text playing a broken animation when it fades out.

CoD4x 21.1: 

https://user-images.githubusercontent.com/91396482/185711391-20356c3a-cf78-4060-a6fb-a269a93dff6f.mp4

CoD4 1.7:

https://user-images.githubusercontent.com/91396482/185711378-3ccaac86-2fc6-4137-9f43-4540a1759a9a.mp4

**Comment by K-Faktor** [comment]
Maybe this is a client error

**Comment by Daxy7** [comment]
> Maybe this is a client error

It might work on Win 10 or I need to reinstall the game

**Comment by Daxy7** [comment]
Missing entire feature on loading screen (game tips/INTEL). Text on v21.1 is also slightly bolder.

CoD4x 21.1:
![iw3mp 2022-08-31 17-12-32-31](https://user-images.githubusercontent.com/91396482/187728541-5be7ae7f-d521-4b1c-955b-9aa9f5773812.jpg)
CoD4 1.7:
![iw3mp 2022-08-31 17-13-47-03](https://user-images.githubusercontent.com/91396482/187728548-6612d0dd-4f2b-4084-920b-4124d34fca43.jpg)

**Comment by Iswenzz** [comment]
> It might work on Win 10 or I need to reinstall the game
i think its a problem with the new cod4x client version

**Comment by proxict** [comment]
Not a server issue.

**Comment by ObelardO** [comment]
PR with fix on client side: https://github.com/callofduty4x/CoD4x_Client_pub/pull/29 @proxict
