### ISSUE TITLE
.ff different from server help

### ISSUE THREAD

**Issue by exeLocates** [callofduty4x/CoD4x_Server#388]
![image](https://user-images.githubusercontent.com/106768358/190888480-323f4e82-6f68-48ae-b59c-d461f5a8ff5c.png)

I uploaded the exact same .ff and load.ff to fast dl and to server file usermaps. then I try to go into the server and it says this? this happens with no other maps on the server, and previously this map use to work for everyone and just recently stopped.

any ideas? please lmk

**Comment by bbashy** [comment]
Delete your local version of the file.

**Comment by exeLocates** [comment]
> Delete your local version of the file.

uploaded my exact local file to server. but yes i already tried that.

**Comment by bbashy** [comment]
Was the file in-use when you copied it? Sometimes it can cause issues depending on the OS you copied from/to.
