### ISSUE TITLE
Problems with downloads

### ISSUE THREAD

**Issue by gasofa** [callofduty4x/CoD4x_Server#390]
Hello guys.
My name is Gasofa and I am from the SPS clan.
We have recently returned to call of duty 4 and the new version of the cod4x mod is giving me a problem that I cannot solve.
I have players who enter the game and download at 2 and 3 Mb/s while others redirect fails and download at 10 Kb/s
Is there any way to solve this?

Greetings and thanks.

**Comment by bbashy** [comment]
Do they download faster using the URLs in a web browser?

**Comment by gasofa** [comment]
if i use this redirection

http://www.readyandplay.com/cod4-1

It works for me and a few others but there are people who don't

Why some yes and others no?

**Comment by bbashy** [comment]
Says 403 for me.

```
$ curl -IL http://www.readyandplay.com/cod4-1
HTTP/1.1 301 Moved Permanently
Server: aruba-proxy
Date: Sat, 01 Oct 2022 12:06:36 GMT
Content-Type: text/html
Content-Length: 168
Connection: keep-alive
Location: https://www.readyandplay.com/cod4-1
X-ServerName: ipvsproxy99.ad.aruba.it

HTTP/2 301
server: aruba-proxy
date: Sat, 01 Oct 2022 12:06:36 GMT
content-type: text/html; charset=iso-8859-1
location: http://www.readyandplay.com/cod4-1/
x-servername: ipvsproxy99.ad.aruba.it

HTTP/1.1 301 Moved Permanently
Server: aruba-proxy
Date: Sat, 01 Oct 2022 12:06:36 GMT
Content-Type: text/html
Content-Length: 168
Connection: keep-alive
Location: https://www.readyandplay.com/cod4-1/
X-ServerName: ipvsproxy99.ad.aruba.it

HTTP/2 403
server: aruba-proxy
date: Sat, 01 Oct 2022 12:06:36 GMT
content-type: text/html; charset=iso-8859-1
vary: Accept-Encoding

```

**Comment by gasofa** [comment]
Hello bbshy.
I don't understand that mistake?

It can be fixed?

thanks for your help

**Comment by bbashy** [comment]
You need a working 'public' URL for fastdl.

What happens when you view that link in your web browser?

**Comment by gasofa** [comment]
Makes me
Forbidden
You don't have permission to access this resource.

if i give above the url

**Comment by bbashy** [comment]
Actually, you can do that but the full URL to the files should be working.

Do you have a URL to a mod file?

Like; `https://www.readyandplay.com/cod4-1/mods/pml220/mod.ff`

**Comment by gasofa** [comment]
try this link:
here if you download the file
www.readyandplay.com/cod4-1/mods/sps_x4/mod.ff

**Comment by gasofa** [comment]
when I put https:// in my server.cfg it doesn't work for me it only works with http://

**Comment by bbashy** [comment]
HTTPS is not supported for the URL.

Make sure there's no force HTTPS redirect on the web server because I can't download it via HTTP;
```
$ curl -I http://www.readyandplay.com/cod4-1/mods/sps_x4/mod.ff
HTTP/1.1 301 Moved Permanently
Server: aruba-proxy
Date: Sat, 01 Oct 2022 14:40:08 GMT
Content-Type: text/html
Content-Length: 168
Connection: keep-alive
Location: https://www.readyandplay.com/cod4-1/mods/sps_x4/mod.ff
X-ServerName: ipvsproxy99.ad.aruba.it
```

Seems like a problem not relating to CoD4x.

**Comment by gasofa** [comment]
https://user-images.githubusercontent.com/24795933/193416085-801fb3f5-f6dc-448f-9893-7f4992821f8f.mp4

**Comment by bbashy** [comment]
HTTPS doesn't work.

![](https://d.code.im/hhdAwXcJA1MLXJNtKn092dlv8SQkMUUKHPR4uoRLth.jpg)

**Comment by gasofa** [comment]
If I put it in https it works for me, if I put it in http it works for me, it's weird that there are people who don't work in http or https

https://user-images.githubusercontent.com/24795933/193430724-8f7d967f-b0a8-4e3b-820f-4bbc69d68320.mp4

**Comment by gasofa** [comment]
This is the error it gives the user:

Hitch warning: 1986 msec frame time
clientDownload: 0 : file "usermaps/mp_sps_old_west/mp_sps_old_west.iwd" completed
clientDownload: 0 : beginning "mods/sps_x4/mod.ff"
Redirecting client 'Shupeinator' to http://www.readyandplay.com/cod4-1/mods/sps_x4/mod.ff
Client 'Shupeinator' reported that the http download of '' failed, falling back to a server download

**Comment by gasofa** [comment]
Hello bbashy.
We have modified some parameters on our website and now it downloads at 30 mb/s.
Thanks for everything

**Comment by proxict** [comment]
Hello, to make it more clear why it didn't work for you in the first place is because on your download server (apache/nginx/etc.), you had a redirect from HTTP to HTTPS. The CoD4 client can only work with HTTP redirects, HTTPS redirects are not supported.
To solve it, remove the HTTPS redirect. I suggest creating a subdomain for the download server (http://www.cod4dl.readyandplay.com/cod4-1/mods/sps_x4/mod.ff).
