### ISSUE TITLE
problem starting bots with my mod

### ISSUE THREAD

**Issue by gasofa** [callofduty4x/CoD4x_Server#393]
Hi guys.
I'm trying to add the cod4x bots to my mod
When I start my server it gives me this error
I don't know if it can be solved?

Grettings

File Handles:
----------------------
24644 files in iwd files
Adding fastfile 'mp_crossfire' to queue
Loading fastfile 'mp_crossfire'
used 42.96 MB memory in DB alloc
Waited 219 msec for asset 'maps/mp/mp_crossfire.d3dbsp' of type 'col_map_mp'.
------- Game Initialization -------
gamename: Call of Duty 4
gamedate: Feb 12 2009
fs_ignoreLocalized is cheat protected.
fs_ignoreLocalized is cheat protected.
Loaded fastfile 'mp_crossfire' in 326ms (1ms waiting)
Error: 
Error: ******* script compile error *******
Error: unknown function: @ 50210
************************************
----- Server Shutdown -----

With the reason: Server fatal crashed: script compile error
unknown function

(see console for details)

Resolving cod4master.activision.com 
Sending master heartbeat from 192.168.1.41:28969 to 84.21.7.14:20810
Sending master heartbeat from 192.168.1.41:28969 to 188.165.57.239:20810
cod4master.activision.com resolved to 185.34.107.159:20810

**Comment by gasofa** [comment]
I keep seeing and starting the server in developer it gives me this

Waited 179 msec for asset 'maps/mp/mp_crossfire.d3dbsp' of type 'col_map_mp'.
------- Game Initialization -------
gamename: Call of Duty 4
gamedate: Feb 12 2009
----------------------
Game: G_SetupWeaponDef
----------------------
fs_ignoreLocalized is cheat protected.
fs_ignoreLocalized is cheat protected.
Loaded fastfile 'mp_crossfire' in 289ms (1ms waiting)
Mistake:
Error: ******* script compile error *******
Error: unknown function: (file 'maps/mp/bots/_bot_internal.gsc', line 424)
  if ( maps\mp\gametypes\_missions::getWeaponClass( weap ) != "weapon_sniper" )
       *
************************************
----- Server Shutdown -----

With the reason: Server fatal crashed: script compile error
unknown function
  if ( maps\mp\gametypes\_missions::getWeaponClass( weap ) != "weapon_sniper" )
(see console for details)

**Comment by gasofa** [comment]
Can somebody help me??

**Comment by ineedbots** [comment]
![image](https://user-images.githubusercontent.com/751729/203644570-7b076182-2c8a-474d-bee7-6fefe4844fd0.png)
Should exist unless you have another GSC that overrides the _mission script and removes this function

**Comment by ineedbots** [comment]
ModWarfare
![image](https://user-images.githubusercontent.com/751729/203644834-a6001d63-b0b2-4007-9745-37b979851ce0.png)

**Comment by gasofa** [comment]
Hi friend.
Thanks for your answer.

I'm not exactly sure how to do it?

**Comment by ineedbots** [comment]
Remove mods that modify _missions

**Comment by gasofa** [comment]
ok modify in my mod the file _missions.gsc

and add these lines

init()
{
}

lastManSD()
{
}


still if it works

**Comment by gasofa** [comment]
now I this

Game: G_SetupWeaponDef
----------------------
fs_ignoreLocalized is cheat protected.
fs_ignoreLocalized is cheat protected.
Loaded fastfile 'mp_crossfire' in 357ms (3ms waiting)
Mistake:
Error: ******* script compile error *******
Error: unknown function: (file 'maps/mp/bots/_bot_internal.gsc', line 424)
  if ( maps\mp\gametypes\_missions::getWeaponClass( weap ) != "weapon_sniper" )
       *
************************************
----- Server Shutdown -----

With the reason: Server fatal crashed: script compile error
unknown function
  if ( maps\mp\gametypes\_missions::getWeaponClass( weap ) != "weapon_sniper" )
(see console for details)

**Comment by exeLocates** [comment]
> ok modify in my mod the file _missions.gsc
> 
> and add these lines
> 
> init() { }
> 
> lastManSD() { }
> 
> still if it works

no you misunderstood what @ineedbots said. in your mod you need to replace your mods _missions.gsc with the _missions.gsc in raw\mp\gametypes aka the original cod4 _missions.gsc

**Comment by gasofa** [comment]
If finally elmod starts, you are the best !!!

The bots come out without a weapon, is that fixed?

thank you very much to all

**Comment by exeLocates** [comment]
since whatever mod your using modified _missions.gsc its entirely possible it is modifying other vanilla GSC's aswell, BotWarfare is built to run with vanilla gsc, beyond that you will have to modify it to your mod.

most likely if the bot is spawning but with no weapon, the classes menu is modified somehow.

Is the pick a class menu different in your mod? what mod are you using here?

**Comment by gasofa** [comment]
Hi, thanks for your response
The mod I use is the extreme in version 2.0

I don't know which files to modify, could you help me? I would greatly appreciate it
Cheers

**Comment by gasofa** [comment]
no one can help me??

**Comment by gasofa** [comment]
After a few days I managed to solve it.

Thank you very much for your help

**Comment by slimline33** [comment]
Hi, I have the same problem. Also that my bots have no weapons. Can you possibly tell me what exactly you did?

**Comment by slimline33** [comment]
I tried already 😅 the compiling is not the problem. But now my server run for 10 minutes, then stops with "Server received signal: Segmentation fault"

**Comment by proxict** [comment]
Your issue isn't related to the server but rather to the mod. Please, open an issue at the relevant repository, which I believe is [here](https://github.com/ineedbots/iw3_bot_warfare).
