### ISSUE TITLE
CL_CGameNeedsServerComand:a reliable command was cycled out

### ISSUE THREAD

**Issue by gasofa** [callofduty4x/CoD4x_Server#395]
Hi guys.
When I change the map it gives me this error
CL_CGameNeedsServerComand: a reliable command was cycled out

Can this error be fixed?

Cheers

**Comment by gasofa** [comment]
Thanks friend, I don't know how to fix it I've been looking and trying things but when the map changes all the escapers go outside.
Can anybody help me ??
Thank you

**Comment by Iswenzz** [comment]
Hey, i think the packets are too big for the players when connecting (could be from too many setClientDvar, setStat etc)

**Comment by gasofa** [comment]
Hello friend, thanks for your answer. how could i fix it greetings and happy new year

**Comment by Iswenzz** [comment]
You can rewrite the GSC to send less setClientDvar and maybe wait a few seconds before sending them, happy new year too.
