### ISSUE TITLE
[BUG] AmbientPlay is crap since 20.X

### ISSUE THREAD

**Issue by FreddyHajas** [callofduty4x/CoD4x_Server#397]
Since the 20.0 release the AmbientPlay function is ONLY played on the first round that the client join the server, after that there’s no more. The only ambient sounds available are the ones in looping at some place of the maps, like flies, fire, etc… but no the main background sound of the game.

Is NOT related to any mod or server, I just installed 21.1 to test this and joined 3 random servers running S&D to test, all of them, same result, seams that is working fine with New Experience server ONLY.

Evidence at a random server online:
https://youtu.be/xE68Xp_fQrg

All my servers are 19.3 because this bug, but you can test at ANY server online easily.

This is a VERY annoying problem, I´m impressed that seams that everyone is not caring about that.

Cheers

please follow this topic with evidences and tests:
https://cod4x.ovh/t/bug-ambientplay-is-crap-since-20-x/1149/46

**Comment by Nukesor** [comment]
First and foremost:

This is an open-source project. People pour their free time into keeping stuff up-to-date.
Showing up on the project and ranting about broken stuff without showing even the slightest bit of grattitude for all the work these guys did is toxic af.

They probably stopped working on this project because of people like you. It's just no longer fun, if everyone is screaming around and one could just stop working on this annoying project and have a cold one in the garde instead.

Keep this in mind, Open-source is non-commercial. These are actual people who do work in their **spare time** for **free**.

If you want this fixed that badly, do it yourself! In the spirit of FOSS

**Comment by FreddyHajas** [comment]
What the hell are you talking about it? I just reported a bug in the bug report area. How much "toxic" is this? Are you nuts?

I'm helping COD4X reporting bugs and testing for several years now. I wouldn't do that if I didn't care.

Cheers

**Comment by Nukesor** [comment]
`[BUG] AmbientPlay is crap since 20.X `

`This is a VERY annoying problem, I´m impressed that seams that everyone is not caring about that.`

**Comment by FreddyHajas** [comment]
Do I need to explain to you then?

Theses are facts, also that most of players are not caring to play in complete silence. 

Did you changed your nick or are you new to COD4X?

**Comment by proxict** [comment]
@FreddyHajas You're not helping by stating how annoying the problem is. Helpful would be if you gave others pointers to how to address the issue, or better yet, fixing the issue yourself by creating a merge request.  
Your attitude is all but good.

**Comment by FreddyHajas** [comment]
> 

**proxict**, seams that you and the other guy that deleted his comments can't read. How I didn't "gave others pointers to how to address the issue"??? I spent hours in the tests, in several servers, made videos (did you saw the video before reply?), and also posted the forum thread about all the investigation process of this bug.

At least READ before reply my friend.

Cheers

**Comment by proxict** [comment]
@FreddyHajas I have read your post, I've even read your forum post and no, I haven't seen your video as you've made it _members only_.
That doesn't change the fact that nowhere in your post have you proposed a solution to the problem. You have only described the problem, stated how annoying it is for you (in a very impolite manner) and you haven't tried to fix it yourself.
The code is open source, which means even you can contribute.

**Comment by FreddyHajas** [comment]
Yeah, I put the video in members only last month, but you are very late on this... there's other videos on the forum which are still public. You STILL can watch them and also READ the problem in details in the entire post.

Seams that now you changed what you said, now I did show details about what is the problem, after each exact version started, and even more, but now the problem is that I didn't proposed a solution??? REALLY?

Funny, now I aside need to do all the work that I did to help, I still need to fix the problem by myself or someone will come up saying I did not made enough, bla, bla, bla... 

It's like someone reported a Error in Frontlines and I ask why they don't fixed by themselves the error that I did in my code.

If you don't want to fix that error? Whatever, it's your decision and I respect that, but you need to learn to respect when someone report a bug/error in your project. Simply as that.

At least in my vision, when someone report a error like that I would reply ASAP with a "sorry, I did a mistake but the error was fixed! download the new version here, enjoy!". But this is me, you are free to act as you think is best for you and the COD4X project.

I just tried to help. All the best!

Cheers

**Comment by FreddyHajas** [comment]
The video is now back to not listed. Enjoy

**Comment by proxict** [comment]
@FreddyHajas You've completely missed the point. It's about the attitude. I don't mind when someone just reports a problem without proposing a solution. What I do mind, however, is when someone needs to express how ANNOYED they are by the BUG by using CAPITALISED expressions. Who do you think you're _yelling_ at? If it's that annoying to you, you can invest time and effort in fixing it yourself. And if you don't have the necessary skill, at least look up how to properly write a bug report; your report is very sub-optimal - that's most likely the reason why it still hasn't been resolved.

This is an open-source, non-profit project and everyone works on it in their free time, for free. So when you talk about respect, please also consider this fact and act accordingly. It's not like you paid for a product where you can be rightfully annoyed that you're not getting what you paid for.

**Comment by FreddyHajas** [comment]
@proxict Did you closed without fix the problem? Tested today, still the same. :(

**Comment by K-Faktor** [comment]
Today, with client 21.1, I connected to the original v1.7 server with the mod and see the same problem that after changing the round there is no AmbientPlay sound. most likely, this is a bug in the client part.

**Comment by FreddyHajas** [comment]
Yeah, hope to get fixed ASAP. Cheers
