### ISSUE TITLE
Admins Entering Password Protected Servers without a password

### ISSUE THREAD

**Issue by Kingwolf123** [callofduty4x/CoD4x_Server#40]
Hello to Cod4x Developers. 
Admins should be able to enter password-protected Servers without a password. It would be a great pleasure if such a feature could be implemented. This issue has been discussed in cod4x forums as well https://cod4x.me/forum/thread-410.html
Regards
Kingwolf

**Comment by D4edalus** [comment]
yes, nice feature. if added there should be a dvar to explicitely activate or deactivate that feature. it's pretty easy for a hacker to see if somebody is in an admin slot. i also thought about adding a VIP feature for my servers such that VIPs can join admin slots too eventually

**Comment by IceNinjaman** [comment]
Its implemented in a different way now. Players who are members of a steam group you assigned to the server before can now enter the server without a password.

**Comment by Kingwolf123** [comment]
Thank you very much !
You mentioned this will work with the latest library and server edition. Where can i get the latest Library?

**Comment by IceNinjaman** [comment]
At the forum in server news section

**Comment by IceNinjaman** [comment]
Okay this should be implemented now with Steamgroups. Get the playerauth library to use
