### ISSUE TITLE
Torjan - Can't be false positive? 

### ISSUE THREAD

**Issue by faheem91** [callofduty4x/CoD4x_Server#402]
https://www.virustotal.com/gui/file/15d10d334744fe355e09835d279fee4abdf7cae86c160832297a74f516aca1ca

**Comment by IceNinjaman** [comment]
The name "Plugin_GetLevelBase" is a virus (If I am not mistaken).
Sorry but I don't feel responsible for detections on whatever crap-ware they make. It is their responsibility to avoid false detections. And when the whole detection works on scanning the export directory of a program, well then they didn't put much effort in their ("security")software.
