### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ProGameCro** [callofduty4x/CoD4x_Server#411]
] -----------------------------------

] This program has crashed with signal: Segmentation fault

] The current Gameversion is: CoD4 X - linux-i386-custom type 'e' build 1169 May 15 2023

] File is cod4x18_dedrun Hash is: c08c5c93179da0463014a0a3cd4f15ccf64614f36b2bd1fa2b26a7f6b0e710fe

] ---------- Backtrace ----------

]    21: cod4x18_dedrun(Sys_PrintBacktrace+0x31) [0x80a2b09]

]    20: cod4x18_dedrun(Sys_DumpCrash+0x92) [0x80a2be4]

]    19: cod4x18_dedrun(Sys_SigHandler+0x24) [0x80a2c5a]

]    18: linux-gate.so.1(__kernel_sigreturn+0) [0xf7fbe140]

]    17: plugin.gsclib.tmp(mysql_real_connect+0x64) [0xdc47bf74]

]    16: plugin.gsclib.tmp(GScr_MySQL_Connect+0xcb) [0xdc4631b4]

]    15: cod4x18_dedrun(pluginSc

riptCallStubs+0x9254) [0x80bc254]

]    14: cod4x18_dedrun() [0x81c159a]

]    13: cod4x18_dedrun() [0x81c1f5e]

]    12: cod4x18_dedrun() [0x81ce89c]

]    11: cod4x18_dedrun() [0x81ff1f1]

]    10: cod4x18_dedrun(SV_InitGameVM+0x6c) [0x81287c2]

]     9: cod4x18_dedrun(SV_InitGameProgs+0x22) [0x812880b]

]     8: cod4x18_dedrun(SV_SpawnServer+0x3c7) [0x8156de7]

]     7: cod4x18_dedrun(SV_LoadLevel+0x2b) [0x815705b]

]     6: cod4x18_dedrun(SV_Map+0xf0) [0x81571c0]

]     5: cod4x18_dedrun() [0x812c160]

]     4: cod4x18_dedrun(Cmd_ExecuteString+0x382) [0x80b15d9]

]     3: cod4x18_dedrun(Cbuf_Execute+0x19a) [0x80b179e]

]     2: cod4x18_dedrun(Com_Frame+0x64) [0x8120950]

]     1: cod4x18_dedrun(main+0x17c) [0x80a2874]

]     0: /usr/lib/libc.so.6(__libc_start_main+0xf6) [0xf7b97f36]

] 

-- Registers ---

] edi 0xffe1dee4

esi 0xffe1dd08

ebp 0xffe1df00

esp 0xffe1dd08

eax 0x0

ebx 0xdcd2b000

ecx 0x0

edx 0x1cb5

eip 0xdc47bf74

] -------- Backtrace Completed --------

] Received signal: Segmentation fault, exiting...

] Server received signal: Segmentation fault

Shutting down server...

] ----- Server Shutdown -----

] 

With the reason: 

Server received signal: Segmentation fault

Terminating server...

m

] ==== ShutdownGame (1) ====

**Comment by AlexanderCurl** [comment]
Remove mysql plugin and try again.
