### ISSUE TITLE
setPlayerNameString

### ISSUE THREAD

**Issue by florczakraf** [callofduty4x/CoD4x_Server#42]
Function `hud setPlayerNameString(<player entity>)` (http://www.zeroy.com/script/hud/setplayernamestring.htm) doesn't work in current build. It results in empty or broken strings across the menus. Works with latest stable release. 

Platform: linux (can't check others)

Example:
(tie on FFA)
![shot0097](https://cloud.githubusercontent.com/assets/9034451/17648703/31fc3fce-621f-11e6-8468-7508d211c4ca.jpg)
or lack of names in CodJumper voting menus.

**Comment by PureTryOut** [comment]
Aah I thought this was an issue in some of my own gsc code, clearly not. Thanks for reporting this

(so yes this is reproduceable, a Linux server in my case)

**Comment by IceNinjaman** [comment]
Can somebody explain please what this function is supposed to do and how its getting used? I have no glue what's up with that script method.

**Comment by florczakraf** [comment]
I think it worked a little bit like this:
```c
hud setText(player.name);
```
where `hud` is given hud we want to chage and `player` is player entity. I said _a little_ because I'm pretty sure it worked when you had `hud.label` set to string that included `&&1` and when you used `setPlayerNameString` it interpolated that string with player's name. Afair it's not possible to use `setValue` with strings. @PureTryOut please correct me if I'm wrong.

**Comment by PureTryOut** [comment]
If only I knew (I don't script stuff, I just use the scripts ;)), I'm just saying I have this problem as well, with a pretty much stock CoD4X server.

**Comment by florczakraf** [comment]
Alright, the screenshot I posted is from stock CoD4x as well.

**Comment by T-Maxxx** [comment]
I'm using "SetText" - always worked but may cause crash because of "string index overflow" or smth like that.

**Comment by IceNinjaman** [comment]
I am investigating it.

**Comment by IceNinjaman** [comment]
I am almost certain it is a client side issue. Client accessing the shortname it shouldn't do.

**Comment by IceNinjaman** [comment]
Well it is fixed for now but had some issues. Playernames will truncate to 15 chars.
https://github.com/D4edalus/CoD4x_Server/commit/baa14820b36f2be33bd5b1735c67be162cd5ce2b
Has to be removed when upgrade to version 16.x is released.

**Comment by florczakraf** [comment]
This build fails. https://travis-ci.org/D4edalus/CoD4x_Server
You have to fix your build script because it returns wrong code on compilation errors.

**Comment by PureTryOut** [comment]
(Ninja, maybe not the time to mention it, but this stuff is why everyone should have their PR's reviewed, even you, so we're sure it always works for everyone, on every platform)

Fails to compile for me as well, on Linux.

**Comment by D4edalus** [comment]
@florczakraf what commit exactly?

**Comment by IceNinjaman** [comment]
Should be fine now as we have version 16.0
