### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by raschedf** [callofduty4x/CoD4x_Server#425]
Hello,

are the current instructions (README) for compiling the CoD4x Server on Linux correct?
I have tried to compile it on Ubuntu 64-bit (22.04, 20.04) and Ubuntu 32-bit, but I encounter errors every time. Has anyone of you tried it and can confirm if it works? Could you also specify which distribution is used and which packages are required?

**Comment by k4r3l01** [comment]
i using for build server ubuntu 22.04 and its working without problems

**Comment by raschedf** [comment]
Hello,

I falsely downloaded the source code and tried to run instead of using git clone.
This fixed all the problems.
