### ISSUE TITLE
cannot execute: required file not found debug

### ISSUE THREAD

**Issue by Leproide** [callofduty4x/CoD4x_Server#426]
Hi all,
After a vps reset the cod4x server wont start.
After uplloading the backup folder this is the error:

./cod4x18_dedrun +exec server.cfg +map_rotate +sv_pure 1
-bash: ./cod4x18_dedrun: cannot execute: required file not found

How i can debug this?
Have a nice day

**Comment by bbashy** [comment]
Check the things discussed here https://unix.stackexchange.com/questions/721844/linux-bash-shell-script-error-cannot-execute-required-file-not-found

**Comment by Leproide** [comment]
Tnx, but not working

**Comment by D4edalus** [comment]
your system doesn't recognize that the file is an executable. you probably have a 64bit os and this is a 32bit binary. i haven't touched this in a very long time, but if you're on a debian based system you can check out the "Compiling on Linux" section in the readme.

`sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install gcc-multilib g++-multilib`

**Comment by Leproide** [comment]
Perfect, now run without need to recompile :D
Tnx m8 <3
