### ISSUE TITLE
[Website login Problem] No reset password email recieved

### ISSUE THREAD

**Issue by UsmanTariq2** [callofduty4x/CoD4x_Server#430]
I want to reset my password for my account, but i am not getting a reset email after clicking on send email and send again on the website

**Comment by Proximity77** [comment]
Hello @UsmanTariq2 , its best you reach out to the team on the discord. @AlexanderCurl would be the guy that should read this soon.

https://discord.cod4x.ovh/

**Comment by AlexanderCurl** [comment]
Is this sorted now? I can reset your password. Please consider changing to a well-known email provider, like gmail or some sort, that should work.

**Comment by AlexanderCurl** [comment]
Forgot what? Changing password, or trying out changing password?
Nonetheless, if you still have issues, hop on discord and we can help out, if still need.
As this is not strictly an issue with the server code, I'll close this one off for now.
