### ISSUE TITLE
Website is HACKED by CHINESE ?

### ISSUE THREAD

**Issue by BestNoob** [callofduty4x/CoD4x_Server#434]
On your website there are only CHINESE symbols ...

**Comment by fonix4000** [comment]
The old URL cod4x.me is no longer used by us, we have moved to https://cod4x.ovh/

If you could point out where the URL needs updated that would be great :)

**Comment by Khursipar** [comment]
Meri bhi koi halp Kar do

**Comment by Khursipar** [comment]
https://gold365.site/m/login isko hack karna hai
