### ISSUE TITLE
"Recieved Stats Although it was not requested from Client" Promod 220 Stock

### ISSUE THREAD

**Issue by Kingwolf123** [callofduty4x/CoD4x_Server#53]
Hello Everyone,

The issue has been plaguing Cod4x Promod Servers. Promod Used is Stock 2.20 From the Promod Website (official) and No custom maps are being used as well. Issue Persists on both 15.8 and source compiled 15.9 Cod4x Versions. This Message "Recieved Stats Although it was not requested from Client" appears when a map or game-type is changed. There are some things i have noticed regarding this issue :

1- Message appears when changing map by either In-game Adminship or Using Rcon (this bug behaves differently for the cod4x admin system and the rcon system repectively). 

2-When using map change command via rcon eg. /rcon map mp_crash, the message does not appear.When using Cod4x Admin System the message appears and clients are disconnected from server

3- After the server has been online for more than lets say 2 days or something, The message  appears only occasionaly when using Cod4x Adsys to change map (really weird). Sometimes the message Appears ,sometimes it doesnot.

4- When changing Map using Cod4x Adsys, as the map image is loaded ( The map mp_crash screen or of any other map), flickering of screen is observed by all clients ( people have told me this explicity and i have observed it myself as well). I believe this flickering is somehow related to the recieved stats message as when the server does-not kick clients on map change when using cod4x adsys, the screen flickering on map screen loading also dissapears.This Flickering Issue doesnot happen at map change or gametype change via rcon, but clients nevertheless get kicked when changing gametype only (map changing by rcon is pretty much problem free from this message, i think).

5- Changing maps via cod4x adsys does invoke this message, but when using rcon to change maps there is no issue.In the case of changing gametypes, Regardless of using cod4x adsys or rcon, the message appears

Any Help Regarding this issue would be appreciated. Thank you

**Comment by IceNinjaman** [comment]
Won't happen again.
