### ISSUE TITLE
Continuous Integration Deployment

### ISSUE THREAD

**Issue by D4edalus** [callofduty4x/CoD4x_Server#59]
Builds should automatically deploy on github releases when a gittag is pushed. This works fine with appveyor (windows builds), but doesn't work correctly for travis-ci (linux builds). If somebody could provide a working deployment startegy I would appreciate it. 

The optimal goal would be to have:
- automatic builds and a github release on each gittag we make, for example on major releases
- store the latest build on master in a github release

i'm also open to switch to another (free for opensource) ci service

**Comment by AlexanderCurl** [comment]
Try this: https://circleci.com/docs/

**Comment by AlexanderCurl** [comment]
Or https://jenkins.io/

**Comment by AlexanderCurl** [comment]
Or https://jenkins.io/

**Comment by AlexanderCurl** [comment]
Try this: https://circeci.com
Or: https://jenkins.io/

**Comment by AlexanderCurl** [comment]
Otherwise I vote to try jenkins first.
First of all, you got thousands of plugins for that, open-source, got a GitHub plugins as well.
Second thing is, you can administrate your own automation services.

Negative thing is you have to use your own resources, but it just only a 3 MB binary, so doesn't need too much resource for the build.

**Comment by D4edalus** [comment]
jenkins would need me to host the jenkins server and also build slaves.
setting all that up is not an option i fear.

i have got the travis ci to work in an near-acceptable manner ... it's not
automatically uploading the release binary when the tag isn't pushed with a
commit ... still sux, but at least it is working now if i care torestart
the build on the travis website  manually.

if somebody cares to create a circle-ci config that compiles the server and
uploads the binary with tags created directly on github i will gladly take
it.

2016-09-09 10:09 GMT+02:00 Sándor Fodor <notifications@github.com>:

**Comment by AlexanderCurl** [comment]
https://circleci.com/docs/configuration/

It's nearly the same as the travis-ci works, just got some extra features, like braches deploy separte with regex, etc.. :) 👍

**Comment by D4edalus** [comment]
i will consider switching if travis goes to shit again. i think its fixed for now.
