### ISSUE TITLE
Join Leave Log & Admin Actions

### ISSUE THREAD

**Issue by utakerkhan** [callofduty4x/CoD4x_Server#61]
1. Proper dvars need to be added for custom naming adminactions.log and enterleave.log. Useful incase of multiple servers as well.
2. The log creation and logging behaviour currently is very strange, sometimes it does not create those files, sometimes it creates files. Proper dvars for its enabling and disabling needs to be added
3. also , these logs to have long guid, nick, ip of both people admins and join leave people

**Comment by IceNinjaman** [comment]
1. You are asked to use different fs_homepath for each server.
2. It turns on when you have logfile 1 or 2
3. I don't know atm.

**Comment by PureTryOut** [comment]
1. Why though @IceNinjaman? As long as you use the correct launch parameters and the correct config files, multiple servers work fine from 1 directory. Log files are the only thing I can think off that might mess up using multiple servers from 1 directory.

**Comment by florczakraf** [comment]
@PureTryOut ​Why not just create separate directories for each server and
link common files?

**Comment by IceNinjaman** [comment]
Also config-files and the banlist are conflicting.

**Comment by PureTryOut** [comment]
@florczakraf because running from the same directory has so far not giving me any problems ;)

**Comment by utakerkhan** [comment]
@florczakraf sym-link method is not safe, same directory method is pretty much smooth for now
@IceNinjaman please reconsider as everyone runs his own way Also, additional information to be appended in logs which was suggested in post which is currently missing. Also sometimes even admin actions log logging all actions of admins (missing sometimes) but unable to reproduce it as to what was causing it

**Comment by florczakraf** [comment]
Actually I was talking about hard-links but I don't see a problem in such
approach. Could you please elaborate on that? You made me curious right now
:)​

**Comment by D4edalus** [comment]
https://github.com/callofduty4x/CoD4x_Server/issues/64
