### ISSUE TITLE
My server crashed .. help

### ISSUE THREAD

**Issue by OrigiTosko** [callofduty4x/CoD4x_Server#63]
Error:
Server fatal crashed
Sys_Error: G_FindConfigstringIndex: overflow (309): 'laurie.ek'
Player "laurie.ek" was playing in my server.

**Comment by T-Maxxx** [comment]
Stop using SetText() with dynamically generated strings.

**Comment by D4edalus** [comment]
@T-Maxxx is there a solution to it? 
i assume the problem is that each hud settext(dynamicStuff) creates a new string reference. once all configstring handles are used that error pops up. 
is there a way to manually free a unused string handle?

**Comment by D4edalus** [comment]
i think that shows how to use it correctly .. but im not sure :)

self.hudhs.label = &"^5Headshots :^0 &&1";
self.hudhs setValue(self.headshots);

source: http://files.hiperz.com/cod4/%5E5myf_%5E1v1/promod/_huds.gsc

**Comment by T-Maxxx** [comment]
This list cleared each map change. On pure server without scripts available about 400 configstrings.
I'm not sure about "&&1" in label string but setValue works only with decimal or float values. There should be concatenation, not format parsing for label and value. And OrigiTosko using player names as strings.
If you set "a" as configstring, it will be used instead of new configstring when called settext("a") again.

**Comment by D4edalus** [comment]
oh i see .. not a solution then. however the same placeholders are visible here https://github.com/callofduty4x/CoD4x_Server/issues/42 so i would assume there is a way to do it.

**Comment by T-Maxxx** [comment]
It will also consume configstring.
CS is a way to send text from server to client.

**Comment by D4edalus** [comment]
solved it i think. 

```
setHudTextSafe(hudelem, txt)
{
	if(!isDefined(hudelem))
		return;
	hudelem setText(txt);
	hudelem clearAllTextAfterHudElem();
}

testhud()
{
	
	if(!isDefined(self.hudkillstreak))
	{
		self.hudkillstreak = newClientHudElem(self);
		self.hudkillstreak.x = 110;
		self.hudkillstreak.y = 13; 
		self.hudkillstreak.alignx = "left";
		self.hudkillstreak.horzAlign = "left";
		self.hudkillstreak.fontscale = 1.4;
		//self.hudkillstreak.label = &"^5Killstreak :^0 &&1";
		self.hudkillstreak fadeOverTime(.5);
		self.hudkillstreak.hidewheninmenu = true;
		self.hudkillstreak.alpha = 1;
		self.hudkillstreak.glowAlpha = 1;
		self.hudkillstreak.glowColor = (0.3, 0.3, 0.3);
	}
	
	while(1)
	{
		level.counter++;
		text = "str:" + level.counter;
		
		setHudTextSafe(self.hudkillstreak, text);
		wait 0.5;
	}
}
...
self thread testhud(); // ran this after spawn (dont know if that is relevant)
```

note: it appears that it is enough to run clearAllTextAfterHudElem() on just one hudelement. so if you use multiple elements at once, you just need to clear one. i have no idea if that is anyhow relevant to performance. also clearing a dummy hudelement once a second might provide a more general solution to the problem.

altough there are some weird warnings in the console :S
Warning: abandoning const config string model slot for string §Overflow on 1335
Warning: abandoning const config string model slot for string §str:591

**Comment by D4edalus** [comment]
i also haven't tested this with multiple players ...

@OrigiTosko you could try to replace all `hud setText(text)` calls with the `setHudTextSafe(hud, text)` function i posted above. i think it's worth giving it a shot.

**Comment by T-Maxxx** [comment]
This is not a solution! It clears ALL configstrings for all hudelems whether used or not!
But! I have an idea :) I will make pull request soon.
