### ISSUE TITLE
write a how to on setting up multiple servers

### ISSUE THREAD

**Issue by D4edalus** [callofduty4x/CoD4x_Server#64]
- explain how to use fs_basepath, fs_homepath, fs_game, (maybe fs_cdpath if its working correctly)
- show how to use the above to prevent duplicating files
- show how to use the above to prevent interfering logs 
- show where to put custom gsc scripts
- include an example configuration

**Comment by florczakraf** [comment]
I've already covered point 4. in [script reference](https://github.com/callofduty4x/CoD4x_Server/blob/master/scriptdocumentation/script_functions_reference.md#how-to-load-new-scripts).
