### ISSUE TITLE
Server in LAN mode (violation issues - totally offline mode)

### ISSUE THREAD

**Issue by utakerkhan** [callofduty4x/CoD4x_Server#66]
Server running in LAN mode on a machine which has internet connection works fine. If that machine does not have internet connection and server is running on LAN mode, it spams the game Client Consoles with Server Exception Violation errors to ruin the experience unless server is started with machine being connected to the internet.
We sometimes run LAN tournaments and face this issue. Of course default Promod Live 220 is used with it

**Comment by D4edalus** [comment]
what is Lan mode? how do you activate it? 
running a dedicated server in Lan works fine for me

**Comment by utakerkhan** [comment]
@D4edalus by using set dedicated command
as for working fine with you, is your LAN server machine also able to use internet access? since it will work fine if internet access is enabled on that machine. If you disable internet access it gives such errors on client machines

**Comment by T-Maxxx** [comment]
Screenshot of error from server console or game client, please.

**Comment by IceNinjaman** [comment]
I think you better create this issue at the Promod forum. Case closed.
