### ISSUE TITLE
Log writing path overwritten?

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/CoD4x_Server#67]
`+set fs_game "mods/tests" +set logfile 2` now opens logfile in "main" directory.
Hey, I know about issue with multiple servers, but you have changed default game logic ("you can always find your logs inside fs_game dir"). I don't like it. This may cause some bugs with GSManager or B3 which looks at "fs_game" variable and seek for log there.
Its better to set up some variables to force server write logs to different locations or with different names.

**Comment by D4edalus** [comment]
My logs are actually on the respective mod folder.

Am 07.09.2016 9:06 nachm. schrieb "Max" <notifications@github.com>:

**Comment by D4edalus** [comment]
i guess your mod is an empty "fake" mod?

2016-09-07 23:50 GMT+02:00 Dominik Shorkhuber <oggs91@gmail.com>:

**Comment by T-Maxxx** [comment]
Yes, without mod.ff.

**Comment by D4edalus** [comment]
it works correctly with a regular mod, and with an empty mod to run custom
maps i actually see it  as an advantage to use the homepath/basepath instead

2016-09-08 0:03 GMT+02:00 Max <notifications@github.com>:
