### ISSUE TITLE
Error de puerto???? o soy yo!!!

### ISSUE THREAD

**Issue by saigrax** [callofduty4x/CoD4x_Server#70]
Hola soy nuevo y no se nada de programacion, sin enbargo tengo un servidor en linea para mi clan y he notado que cuando el servidor cambia la IP en ocaciones me tira un puerto que no es el asignado 

EJ; xxx.xxx.xxx.xxx.:28960 seria el correcto y aveces cambia a xxx.xx.xxx.xx:1339 por poner un caso, 

lo tengo asignado con el 28960 pero en ocaciones lo cambia, y le dificulta la visibilidad a los usuarios y obviamente tambien la coneccion. 
Cuando le asigno el puerto que corresponde segun http://cod4master.cod4x.me/ lo reinicio y me tira otro distinto no se como solucionarlo 

Ayuda plisss!!!! alguien sabe como solucionarlo??????

**Comment by T-Maxxx** [comment]
What arguments you using when starting server?

**Comment by PureTryOut** [comment]
@T-Maxxx you understand any of this? Could we require people to ask in English here, as not many people here speak Portugese or Spanish (whatever this language is).

**Comment by T-Maxxx** [comment]
@PureTryOut https://translate.google.com

**Comment by saigrax** [comment]
EJ: map p_crash o map_rotate lanzo cualquier mapa para iniciar el servidor

**Comment by saigrax** [comment]
EL puerto que  he asignado es el 28960, el nombre del servidor HostMasterServer , es de uruguay, cuando ben un puerto de  4 dígitos es que algo anda mal y no tengo como solucionarlo, el puerto cambia solo

**Comment by wkuzma** [comment]
si se utiliza una línea de comandos añadir este

+Set net_port 28960

**Comment by saigrax** [comment]
if you already had done and gave me the same problem

**Comment by T-Maxxx** [comment]
Do you have any mods running on your server?

**Comment by saigrax** [comment]
yes openwarefare

**Comment by MichaelHillcox** [comment]
+set net_ip +set net_port although you should have both of these set anyway. If your running this on a vps or a shared hosting config then that could be the issue for the odd port and or the odd ip. I would suggest changing net_ip to your main ip and the net_port to something other than 28960 maybe 28961 and see if that resolves your issue.

**Comment by saigrax** [comment]
I'll try and see how it reacts, and I tell you. thanks
