### ISSUE TITLE
Cod4x client bug

### ISSUE THREAD

**Issue by Nicky012** [callofduty4x/CoD4x_Server#71]
Sorry if I put this in the wrong section.

When I install the client (it does automatically when I join an cod4x enabled server), after restarting the game, it freezes automatically. Only background sound is on and everything else freezes. When I start the task manager, it says "Cod4x not responding"

**Comment by bykidi** [comment]
OS and version?

**Comment by Nicky012** [comment]
My OS is Windows 7 Ultimate and the version of Cod4x is the latest one which is 16.1 or something.  Pls help!!

**Comment by PureTryOut** [comment]
This is indeed the wrong section, it should be put on [the forum](https://cod4x.me/forum/forum-10.html) instead.

**Comment by D4edalus** [comment]
https://cod4x.me/forum/thread-572-page-2.html

closed as OP stopped replying
