### ISSUE TITLE
Error on loading default Plugin - 2 Issues

### ISSUE THREAD

**Issue by utakerkhan** [callofduty4x/CoD4x_Server#72]
1st issue is that if you load a plugin like loadplugin simplebanlist , it gives error of libgcc-s-dw2-1 missing. On your test machine it might work as all files are there but as one uses the files available on download link it doesnt.
Please check following link which gives idea how to make it re-distributeable.
http://stackoverflow.com/questions/4702732/the-program-cant-start-because-libgcc-s-dw2-1-dll-is-missing

2nd, an option is required so when a plugin is loaded, it isnt locked, so users having multiple servers from one directory don't have a problem of loading plugins where they create plugins abx1 abx2 to load same plugin

**Comment by IceNinjaman** [comment]
2. Use unique fs_homepath for each server.

**Comment by utakerkhan** [comment]
what about 1st issue? it isnt loading the plugin

**Comment by wkuzma** [comment]
I had the same problem with problem number 1 
I downloaded the missing file and placed it in the cod4x directory to prevent the error 
but it gives a new error when shutting the server down.
error. the application has requested the runtime to terminate in an unusal way 
Please contact the application's support team for more assistance

**Comment by D4edalus** [comment]
statically linked now
