### ISSUE TITLE
2D arrays?

### ISSUE THREAD

**Issue by Sharpienero** [callofduty4x/CoD4x_Server#74]
Hi there,

I was just wondering if there was a possibility of adding 2D arrays (that work similarly to Scr_AddArray). It would be very helpful for a plugin I am making.

Thanks.
Sharpienero

**Comment by T-Maxxx** [comment]
You can add as much (almost) elements in array as you want. Just look how's that used.
Also, you can use vec3_t but keep 'z' component unused. There's no reason to add something else.

**Comment by Sharpienero** [comment]
I'm not really concerned about how many elements I can add, just returning the structure as Array[i][j]. When you're working with SQL databases, it's somewhat crucial that you are able to return:

`Array[rows][columns]`

I'm looking at vec3_t, but isn't that only capable of returning a single paired element. I.E Array[0][0].
What if I need to return an array of size [15][25]?

**Comment by MichaelHillcox** [comment]
@Sharpienero @T-Maxxx He's talking about have an gsc array looking like this. 
`myArray[0][1][1]` 2D array in gsc. You would end up doing something like this
```c++ 
myArray = [];
myArray[0] = [];
myArray[1] = [];
 ```
We know you can do it through raw C but we aren't sure how we would return one back into the gsc code. `Scr_AddArray` works perfectly for a single array `myArray[0]`.

Just making sure you understood the question correctly.
If there is a way to do this already then could you give a small example?

Thanks,
Michael.

**Comment by T-Maxxx** [comment]
@Sharpienero @MichaelHillcox Oh, sorry, I just messed definition of vector and array :D

**Comment by Sharpienero** [comment]
@T-Maxxx No worries! The reason this is needed because I am currently working on deploying SQL functionality to cod4x. When querying a database and selecting multiple rows, passing that information to GSC is very helpful. Otherwise sorting the data would be very difficult and painful.

Any possibilities of having this happen?

**Comment by D4edalus** [comment]
i dont think this needs its own implementation as its very simple to do it already

very simple to simulate as you can just address a one dimensional array such that it simulates a n-dimensional array.
imagine an array with 4x3 elements. indexing as follows: (you can also transpose it)
width: 3
height: 4

y
^
|
0 1 2 -> x
3 4 5
6 7 8
9 10 11

indexing the position (x = 1, y = 3):
arr[y * width + x]
3 * 3 + 1 = 10

**Comment by T-Maxxx** [comment]
@Sharpienero Why not? It's better to sort data using C code than sorting using game virtual machine. And you always can query filtered info. With complex request but still ;D

**Comment by MichaelHillcox** [comment]
@T-Maxxx when working with sql you need to have dynamic management of the content on both ends. C to get the content for you and then gsc to sort it for you. Using c to do it would be awful. 

@D4edalus Not quite sure how that would work out. You got any code that might show it off a little?

**Comment by MichaelHillcox** [comment]
@T-Maxxx @D4edalus You understand what we mean by a 2d array right? and then handing it back to gsc?

**Comment by T-Maxxx** [comment]
@MichaelHillcox The virtual machine speed will be awful if you will try to sort a lot of data using scripts.

**Comment by MichaelHillcox** [comment]
@T-Maxxx I understand that but there is not much that we can do to avoid that. It less sorting and more writing the write query and being able to get all the data it returns. It's less about being able sort the data. its about being able to get the data. 

One query under something like `SELECT * FROM mytable WHERE status = 1 SORT BY DESC Limit 0, 20`

Using that I should be able to fill a 2d array with the response data. the first index being the row and the second being the field containing the data. so `array[0][1]` row 1 field 1.

whilst on this topic of arrays. How would I go about returning a string as the array index. So `array["gun"]` using something like `Scr_AddArray`

**Comment by T-Maxxx** [comment]
@MichaelHillcox For now, there's no support for that in plugin system.

**Comment by MichaelHillcox** [comment]
@T-Maxxx Any look at having it added? or do you know happen to know of the right offset so I and do it myself and make a pull request?

**Comment by T-Maxxx** [comment]
@MichaelHillcox I did it already.

**Comment by Sharpienero** [comment]
@T-Maxxx You've gone ahead and added the code? Could you share the commit since I don't see it in your repo or as a pull request.

**Comment by MichaelHillcox** [comment]
@Sharpienero Looks like that is for the array key. Its a little different. Very handy if that also gets 2d array support then that will be amazing. It looks like he's added support to do this `myArray["awesomeIndex"]` instead of `myArray[0]`

**Comment by T-Maxxx** [comment]
#75

**Comment by Sharpienero** [comment]
@T-Maxxx  - That's kind of a completely different issue. What are the chances of 2D arrays being added?

**Comment by T-Maxxx** [comment]
@Sharpienero I don't want to do that because I don't know how exactly VM stack works. You can ask @IceNinjaman, but @D4edalus already closed this issue with good explanation.

**Comment by MichaelHillcox** [comment]
@Sharpienero Still very handy for me :D 

Although @T-Maxxx thats not really what we meant. Thank you for adding that. Very handy :) but the thing we need more importantly is support for 
( in gsc )
```c++
thing = getMy2DArrayFromC(); // CoD4x C function 
iPrintLn( thing[0] ); // some text
iPrintLn( thing[0][0] ); // some more text.
iPrintLn( thing[0]["this"] ); // if you support it with your #75 pull
```

**Comment by Sharpienero** [comment]
@T-Maxxx His explanation was not very good (in my mind) due to the fact that traversal of that single element array, then manipulating the data would not be very nice at all.

I understand that in theory, it's "technically" the same thing, but in practice, 2D array would be a much more efficient and practical approach. 2D arrays are a part of C and they're also a part of GSC. Passing the 2D array shouldn't be that complicated, I just don't know where to start since my experience with cod4x is very inferior to this teams.

**Comment by T-Maxxx** [comment]
@Sharpienero Sorry, guys, I messed with function names. 'Scr_MakeArrayKey' now 'Scr_AddArrayKey' cuz 'MakeArray' is to create array variable and 'AddArray' is to add variable to array variable.

**Comment by T-Maxxx** [comment]
@Sharpienero Found a way. But you have to code that by yourself or with some helper functions.
```
// Called from script by 'test_multidimensionalarray()'
static void Scr_test_multidimensionalarray_f()
{
	/*
	Example 2 dimensional array

	a[0][0] = 1
	a[0][1] = 2
	a[0][2] = 3
	a[1][0] = 4
	a[1][1] = 5
	a[2] = 6
	*/
	
	Scr_MakeArray();         // This variable will be returned.
		Scr_MakeArray();     // First component as array.
			Scr_AddInt(1);
			Scr_AddArray();  // [0] = 1
			Scr_AddInt(2);
			Scr_AddArray();  // [1] = 2
			Scr_AddInt(3);
			Scr_AddArray();  // [2] = 3
		Scr_AddArray();      // Add first component.
		Scr_MakeArray();     // Second component as array.
			Scr_AddInt(4);
			Scr_AddArray();  // [0] = 4
			Scr_AddInt(5);
			Scr_AddArray();  // [1] = 5
		Scr_AddArray();      // Add second component.

		Scr_AddInt(6);       // Third component as int.
		Scr_AddArray();      // Add third component.
	// End here.
	// Yep, no additional pushes to stack required after first 'Scr_MakeArray' call
}
```
And script usage:
```
a = test_multidimensionalarray();
self iprintln(a[0][0]);
self iprintln(a[0][1]);
self iprintln(a[0][2]);
self iprintln(a[1][0]);
self iprintln(a[1][1]);
self iprintln(a[2]);
```

**Comment by MichaelHillcox** [comment]
@T-Maxxx That seems to have some what solved my issue. I have put in your function my local version of CoD4x and I've run the same debugging as you have with the self iPrintln.

To shorten down my debug I decided to put the array into a `for loop`. Got the size of the first array and then inside that `for` set up another `for loop` and got the size of `myarray[i].size` although for some reason it would seem that the function you showed me does not allow `.size` to could the array correctly. It counts 1 up.

here is my error:
```c++
size cannot be applied to int: 
  for( b = 0; b < thing[a].size; b++ )
```


```c++
	thing = scr_test_2d(); //shortened your function name down

	for( a = 0; a < thing.size; a++ ) { 
		for( b = 0; b < thing[a].size; b++ )
			consoleprint(thing[a][b]); // console print just uses Com_printf 
	}
```

**Comment by MichaelHillcox** [comment]
@T-Maxxx Even running a much simpler function to try and print out the first item from the second array like this 
```c++
	for( a = 0; a < thing.size; a++ ) { 
		consoleprint(thing[a][0]);
	}

```
causes this issue 
```c++
int is not an array, string, or vector: 
  consoleprint(thing[a][0]);
```

**Comment by T-Maxxx** [comment]
@MichaelHillcox `thing` has type int. Must be error in you code.

**Comment by MichaelHillcox** [comment]
@T-Maxxx you can see the code i've used. Can you use an error?

**Comment by T-Maxxx** [comment]
Code, not in script.

**Comment by Sharpienero** [comment]
@T-Maxxx  It's an issue with bounds. .size returns 3 (which is OOB, since our bounds are 0-2)

**Comment by T-Maxxx** [comment]
@Sharpienero What issue? Don't you know how size value for array calculated?

**Comment by Sharpienero** [comment]
@T-Maxxx Yes, I'm aware. I was simply saying for his logic above.
`a < thing.size;` should be `a < thing.size-1;`

**Comment by D4edalus** [comment]
@Sharpienero @MichaelHillcox 
i assumed numerical indexing before. sorry for closing so fast :) let us know if you are successful with the solution provided by tmax.

on another note: personally i prefer to cover database requests by a rest interface. (not yet completed) http plugin: https://cod4x.me/forum/thread-546.html

@T-Maxxx 
awesome solution :D .. i guess i can also use this to transform http/json requests like that into nice arrays (for the plugin shown above).

do you know more about the limits that can be stored on the vm stack / heap? ( i have no idea how those variables are stored actually )

**Comment by T-Maxxx** [comment]
@Sharpienero @MichaelHillcox Guys, don't you know its 0-based? first element == 0 index. If you want to iterate whole array, use
`for(i = 0; i < array.size; i++)`
or 
`for(i = 0; i <= array.size - 1; i++)`
There's no issues. It's common practice. I know, LUA using indexes from 1 to n, but C, C++, C#, java, python, ruby it starts from 0.

I have discovered some issues with dynamic iterating (using `.size` its not applied to int, float or string) through array. I am implementing [isArray](http://zeroy.com/script/variables/isarray.htm) function now.

**Comment by MichaelHillcox** [comment]
@T-Maxxx thats literally what I was about to say. I needed a better way to check for arrays. My issues here what that I was trying to print [a][b] when on array[a] equaled to an int not an array and therefor isDefined( array[a][0] ) does not work because its looking for an array, string, or vector. If is defined function was to work correctly it would understand this issue `int is not an array, string, or vector:` and return false instead of bitching.

an `isArray` function is the way forward :)

**Comment by MichaelHillcox** [comment]
@T-Maxxx just tried. isArray seems not to work. Is that a cod5 functions?

**Comment by T-Maxxx** [comment]
@MichaelHillcox IDK, its not exist in cod4 1.7. I just added and tested it. I'll push it now.

**Comment by Sharpienero** [comment]
@T-Maxxx awesome. Can't wait to see that function.

**Comment by MichaelHillcox** [comment]
@T-Maxxx yeah. looks like it isn't. I also updated my comment.

**Comment by T-Maxxx** [comment]
@Sharpienero Here you go.

**Comment by MichaelHillcox** [comment]
@T-Maxxx the `isArray` function worked perfectly :)
