### ISSUE TITLE
Auto Restart

### ISSUE THREAD

**Issue by MichaelHillcox** [callofduty4x/CoD4x_Server#77]
Would be nice to have the server auto restart on fatal errors in map code. Not in mod code. Not sure if you will be able to tell the difference. Might be as simple as looking at the servers uptime and if its been up for a while then it would have been a map to cause the crash.

It would also be very handy to have a dedicated crashreports dir and have what crashed the server outputted to there instead of the qconsole.log

**Comment by D4edalus** [comment]
auto restarting would be nice yes
why would we differentiate between mod and map code? how would looking at the uptime help to differentiate between mod and map code?

**Comment by MichaelHillcox** [comment]
Basically when running a mod with custom maps. You will find you have a stable mod and unstable maps. So it would be much better to have a auto restart on map crashes and not on mod crashes. Mod crashes are likely to continually happen and people would likely just go "oh its that map. I will just take it out." when in reality its the mod. 

You can ignore that of course and just add auto restart and just make it stop auto restarting if the server is continually crashing.

**Comment by T-Maxxx** [comment]
You have scripts. You have scripts in mod and you have scripts in map. Script error happens. How can you detect where is this script located?

**Comment by MichaelHillcox** [comment]
You can't but a usual thing is that if the servers been up for a while then it's unlikely to be the mod.

**Comment by T-Maxxx** [comment]
Uhm... Do you know difference between `runtime` and `compile` errors?

**Comment by T-Maxxx** [comment]
The only way I suppose it can be implemented is to iterate through each loaded fastfile, through each fastfiles' assets table but there's one problem - you can't do that if you don't know exact fastfile asset count. Its not saved during .ff loading and obtainable only by external decompression (all of this requires a lot of time).

**Comment by MichaelHillcox** [comment]
@T-Maxxx I think your over thinking this. By default an auto restart function would be logical. Just program it in. Keep an eye on the crash logs. Make a new one for each crash and if 3 have been made with in the last 60 seconds then stop trying to auto restart ( hard shutdown ). That would be the simplest form. The server also watches for its uptime and ticks it up every minute or so. You can see this from the xml that it creates. The best way you can tell if it is a map issue would be to just look at the uptime. If its more than the match time ( meaning the map would have changes once or twice ) then it can't be the mod. The mod would have crashed. Either way thats near here nor there. Look at the crashlogs creation date would work just as well to see if the crash is happening continually on start up or around the servers start up time. 

The main thing I am asking for is crash reports being created in a different dir and for the server to auto restart but not to continually do it if the server has a mod error or is running something that is crashing it. The crashlogs would be all that is needed to find out what is going wrong. I was simple suggesting a way to see if it is continually crashing. The last thing you want is a server restarting 8 times in a minute every minute. 

I currently just have a bash file watching for the the servers screen is down. If it is then it will put the server back down and make a crash report. if there is more than 3 crash reports made within the last minute then it will stop restarting and email me the last 3 crashlogs and some relative information so I can go in and fix the issue quickly. But... not everyone knows bash or how to use bash correctly so having that same functionality ( excluding the email ) would be a widely expected thing.

**Comment by MichaelHillcox** [comment]
@callofduty4x any update?

**Comment by D4edalus** [comment]
@MichaelHillcox Please make a pull request if you want this feature. For now it's postponed to "wontfix" unless somebody decides on doing it. You could share you bashscript, maybe others find it useful to have a quick solution to restart a crashed server.

**Comment by iznogod** [comment]
Why not make a cvar (seta sv_exitoncrash "1") which will actually kill the process if a script error (or any other error) occurs? Then wrapper scripts can restart the process without it "hanging" in "hey here's your error, go read it"-mode.

Would be the quickest way to resolve this in a decent manner.

**Comment by MichaelHillcox** [comment]
That's a good idea :) just something to tell the server to execute a bash file or something like that to restart it.  @D4edalus what do you think?

**Comment by florczakraf** [comment]
Why don't you just run a cod server as a `systemd` unit?

**Comment by iznogod** [comment]
Because not all of us are on a recent-enough linux version to have systemd. Aside from that, if the service itself hangs, systemd cant do shit either.
