### ISSUE TITLE
I Can't use fullbright on any server

### ISSUE THREAD

**Issue by Pixeladu** [callofduty4x/CoD4x_Server#79]
I can't activate eullbright using r_fullbright 1 or using the bind "SelectString... FPS FPS r_fullbright 1" ..  
this is a bug or a new restriction from the developers?

**Comment by D4edalus** [comment]
good! don't hack :) "SelectString... FPS FPS r_fullbright 1" did actually circumvent sv_cheats. so yes that is intended. idk if you know what else was possible with this command .. but it ranges from bad to horrible :dancers:
