### ISSUE TITLE
Couple of problems noticed

### ISSUE THREAD

**Issue by wkuzma** [callofduty4x/CoD4x_Server#80]
I posted about the new version 16.1 breaking external programs using rcon in the forums.
I cannot find that post.
external programs that use rcon return an invalid password when trying to connect to version 16.1 cod4x
however when connecting to version 16.0 cod4x there is no password problem.
php_rcon is the program I have been using for 4 years without a problem until I installed 16.1.

Also I noticed this in the cod4x logs
16.0 log
 16:07 say;f5ff0923aa8e05d0e02ee5ddeb9b5e0f;2;Stranger-KAB;!help
 16:41 say;f5ff0923aa8e05d0e02ee5ddeb9b5e0f;2;Stranger-KAB;!rules
 22:04 say;f5ff0923aa8e05d0e02ee5ddeb9b5e0f;2;Stranger-KAB;!admins
 22:17 J;35cb58b5d1a3bc63bc227d9553e8c075;3;JAVIER
 22:42 Q;35cb58b5d1a3bc63bc227d9553e8c075;3;JAVIER

16.1 log
 0:46 J;0;2;Stranger-KAB
  1:09 say;0;2;Stranger-KAB;!help
  5:51 say;0;2;Stranger-KAB;!help
  6:11 say;0;2;Stranger-KAB;!help
  6:55 say;0;2;Stranger-KAB;!help

notice the guid is missing in the 16.1 log
the guid is needed by b3 without it b3 does not work

**Comment by IceNinjaman** [comment]
First you have not the auth library installed. That why its empty.

**Comment by wkuzma** [comment]
this is what I get with auth library installed
  0:23 J;2310346613455718322;2;Stranger-KAB
  0:39 say;2310346613455718322;2;Stranger-KAB;with auth installed

completely different than 16.0 
16:07 say;f5ff0923aa8e05d0e02ee5ddeb9b5e0f;2;Stranger-KAB;�!help

**Comment by MichaelHillcox** [comment]
@wkuzma I wouldn't know but I am pretty sure thats because this `0:39 say;2310346613455718322;2;Stranger-KAB;�with auth installed` is using the Steam 32 || 64 bit UID instead of the crappy guid system. Thats why it requires the auth library.

**Comment by wkuzma** [comment]
also one other thing 
cod4 and cod4x version 16 server rcon query returns
 ????print map: mp_crash num score ping guid name lastmsg address qport rate --- ----- ---- 
-------------------------------- --------------- ------- 
---------------------------------------------------- ----- ----- ~

version 16.1 returns

????print hostname: ^5KAB^3 Knife^5 test version : CoD4 X 1.8 win_mingw-x86 build 1458 
Sep 9 2016 udp/ip : 73.29.175.138:28960 os : win_mingw type : dedicated server map : mp_crash 
num score ping playerid steamid name lastmsg address qport rate --- ----- ---- 
----------------- ----------------- -------------------------------- ------- 
---------------------------------------------------- ----- ----- 

is it possible  that the output can be returned to what 16 was putting out
which is the same as what cod4 puts out.

I am not sure yet but searching why 16.1 interferes with b3 rcon  but it may be related to the above.

**Comment by MichaelHillcox** [comment]
@wkuzma Just edit your parser to support the different format

**Comment by efinst0rm** [comment]
@wkuzma With the 16.1 the guid gets changed around as you seen they added playerid , steamid the b3 parser would have to be worked. Or the temp fix you can use this in the command line and it will bring back the old style status responds. "+set sv_legacyguidmode 1" I've tested it and works great, and with the new update you will need the new b3hide plugin crazy posted on the forums.

**Comment by wkuzma** [comment]
Thank you  lol I spent hours tring to fix that problem and all it took was +set sv_legacyguidmode 1

all is working perfectly  even without the b3hide plugin
