### ISSUE TITLE
Sorting & Management

### ISSUE THREAD

**Issue by MichaelHillcox** [callofduty4x/CoD4x_Server#81]
This is not an actual issue but something I though I should point out seeing as I have personally had it happen :P.

Github updated to add a mini project management system into every repo. I would suggest you set one up and add all tickets for the things being worked on and the things that are still needing to be done so that other contributors know whats needing to be done and what is being worked on. 

Plus assigning tags and people to tickets helps resolve things a lot faster. ( ish ). I would be happy to do this for you by the way. I can help manage any documentation and sorting for this project. Its sort of ma thing. I love to make things tidy and sorted. 

:)

**Comment by MichaelHillcox** [comment]
@callofduty4x any update? / Opinions?

**Comment by D4edalus** [comment]
thx for the suggestion, we will try to work in a more organized way.
