### ISSUE TITLE
GSC get OS

### ISSUE THREAD

**Issue by MichaelHillcox** [callofduty4x/CoD4x_Server#83]
In case a plugin or something requires a specific OS to run then it would be highly useful to have a GSC function to return the OS. Either windows or linux. Helps for testing mods. I know a lot of devs make mods on windows and then run them on a linux server.

**Comment by T-Maxxx** [comment]
All GSC functions are non-os specific and plugin loading system adds correct file extension depending on OS.
Devs simply have no choice - theres no linker_pc available for linux but through wine.

**Comment by MichaelHillcox** [comment]
Ah, okay that's fine. Wasn't a 100% on that.
