### ISSUE TITLE
Command to reload mod .gsc files during the game

### ISSUE THREAD

**Issue by MichaelHillcox** [callofduty4x/CoD4x_Server#84]
Not sure if this is possible but damn would it be helpful. Even if it was just implemented in fast_restart instead of having to map_restart. Would make testing code so much faster.

**Comment by MichaelHillcox** [comment]
Would it be possible to have it work just for a single file. I know when a new round begins it basicallt restarts the game anyway. So surely there is a a way to work something there?

**Comment by T-Maxxx** [comment]
It restarts game, but not reloading scripts. Server kills all virtual threads and calls it from beginning.

**Comment by MichaelHillcox** [comment]
ReloadScripts maybe a new functional. Combinds script reloading with a fast restart?

**Comment by T-Maxxx** [comment]
I'm not sure but there `exitlevel(true)` script command should do fast restart for sd rounds, without scripts reloading. Looks exactly like `fast_restart` console command. I'll take a look, but I'm not promising anything.

**Comment by MichaelHillcox** [comment]
Hmm. Not sure about exit level. Ideally it would be a console command line fast_restart that will quickly reload scripts. If you use map_restart it has to completely reload the map. I want something where it will only reload the scripts. Hopefully :) thanks for looking into it.

**Comment by T-Maxxx** [comment]
Looks like script reloading happens exactly when .ff loads. Pure internal script restart can not trigger script reloading.

**Comment by T-Maxxx** [comment]
I can not find required loader code.
