### ISSUE TITLE
GSC function to get players Dvars 

### ISSUE THREAD

**Issue by MichaelHillcox** [callofduty4x/CoD4x_Server#85]
Just like `setclientdvar(string<dvar name>)` but it would be `getclientdvar(string<dvar name>)`. I'm not 100% sure if this has already been added but I looked through the script docs and couldn't find it.

**Comment by T-Maxxx** [comment]
Required tweaks on client side.

**Comment by MichaelHillcox** [comment]
@T-maxxx ah. Really? Damn that's annoying. 

Any chance of being able to make things like `getclientfov` and `getclientfovscale`

**Comment by T-Maxxx** [comment]
Setu and getcvaruserinfo (or smth like that) with some menu scripts (setfromdvar) in some cases will allow you to grab any client dvars.

**Comment by MichaelHillcox** [comment]
Will setu work in a menu file?

**Comment by T-Maxxx** [comment]
Menus are clientside. There ypu have 'exec' script menu command. All inside of it will be executed as client console command.

**Comment by MichaelHillcox** [comment]
@T-Maxxx Does that mean you're able to get them server side or not?

**Comment by T-Maxxx** [comment]
That's not a shame but some kind of protection (with this server admins will be able to stole client cdkey for example).

**Comment by MichaelHillcox** [comment]
Stealing cdkey has been possible before. Just like its super easy to steal the rcon_password on a server. In the most stupid way possible.
