### ISSUE TITLE
SRV support

### ISSUE THREAD

**Issue by MichaelHillcox** [callofduty4x/CoD4x_Server#86]
No clue if this is even handled through the game but logic would dictate that it is. Could you add in SRV support so that people can set up SRV records that point towards a server running a custom port.

https://en.wikipedia.org/wiki/SRV_record what they are 

Means I could be running 3 servers. One on port 28961 the other on 28962 and the other on 28963. Using a SRV record I could set up subdomains so I could connect through dr.example.com pm.example.com and cj.example.com. 

Not sure if this is something you can do but damn with it be fucking useful

**Comment by D4edalus** [comment]
i don't see how the server itself could influence routing. i think this
needs to be configured inside the dns records. ( but you discovered that
already )

what would be left to be implemented into the cod4x server?

2016-09-25 15:48 GMT+02:00 Michael Hillcox <notifications@github.com>:

**Comment by D4edalus** [comment]
https://pxg.me/ has it, you could ask how they did it :)

2016-09-25 16:08 GMT+02:00 Dominik Schörkhuber <dschoerk@gmx.at>:

**Comment by IceNinjaman** [comment]
It has to be a client side feature and not really server feature. The most complicated part to do this is that we need our own DNS resolver for it.

**Comment by MichaelHillcox** [comment]
Ah. Some how I thought It would be a client thing.. :(
