### ISSUE TITLE
IPv6 Support?

### ISSUE THREAD

**Issue by MLWALK3R** [callofduty4x/CoD4x_Server#88]
I've seen that  IPv6 was added a while ago but I don't see no servers via the server browser or able to connect to any from the cod4master.cod4x.me server list, is this currently supported? Also  I'm correct in thinking that \connnect [::]1337 should connect to an IPv6 server?

**Sorry if this should be in the client section**

**Comment by IceNinjaman** [comment]
Well it has this support. Masterserver did not list servers on IP6 addresses for few weeks as it got moved and was improperly configured. Also atm. the client does still prefer IP4 if available. Probably I am going to change that in future. However I can't to really extensive test out it my self as I don't have IP6 connectivity at home.

**Comment by MLWALK3R** [comment]
Thanks for the info, if you want to test with IPv6 you can setup a [HE tunnel ](https://tunnelbroker.net/ )It would be really great if the client and servers had IPv6 support even if its defaulted to v4; if a users can connet via V6 would be turly amazing ;D

**Comment by IceNinjaman** [comment]
Well from my knowledge it works. Just test it. cod4master.cod4x.me lists ip6 addresses again.

**Comment by MLWALK3R** [comment]
I tested several servers with the connect command either you get awaiting connection or bad challenge for address

**Comment by IceNinjaman** [comment]
Oh that makes sense. I guess it works only on 1.7a servers. There is a fault in a facility which calculates something which is similar to a syncookie. I came across it yesterday as Server player list queries fails after I added an AAAA record for my servers.

**Comment by MLWALK3R** [comment]
Any chance this could be looked at getting fixed ;)

**Comment by IceNinjaman** [comment]
Well it is fixed in the server release you can download compile from here. But it is not deployed yet on all servers.

**Comment by MLWALK3R** [comment]
Ah cool, if it's fixed and will get release soon im happy ;D
