### ISSUE TITLE
Can not compile new build

### ISSUE THREAD

**Issue by efinst0rm** [callofduty4x/CoD4x_Server#89]
Hey,

I was trying to compile new build for windows from source and get this error.
![xqpjnj9q406lhtzhlsyd](https://cloud.githubusercontent.com/assets/7751074/19667354/0c17c380-9a16-11e6-9bef-278a574ba51c.png)

And also if i used the exe provided from
https://ci.appveyor.com/project/D4edalus/cod4x-server/build/1.0.53

It will break the the screenshotsend plugin.

Thanks

**Comment by T-Maxxx** [comment]
Iphlpapi has to be linked?

**Comment by efinst0rm** [comment]
Also here is the error when try to load the screenshotsender plugin.

```
HTTP_SendReceiveData: mbedtls_ssl_handshake returned UNKNOWN ERROR CODE (0045)
Receiving data has failed
^1Error: Init failure. Couldn't connect to server
Error in plugin's OnInit function!
```

**Comment by IceNinjaman** [comment]
Well yes iphlpapi has to be linked now. Isn't it in the build script added?

**Comment by IceNinjaman** [comment]
Maybe you run wrong buildscript? You have to run the updateable one.

**Comment by T-Maxxx** [comment]
@IceNinjaman It was in 'updateable' but not in dev script.

**Comment by efinst0rm** [comment]
@T-Maxxx i added the Iphlpapi  to bat file and it worked. Only issue now is that the screenshotsender plugin doesn't get loaded from the server.cfg.  But when you are in game and use loadPlugin then it will work.

**Comment by IceNinjaman** [comment]
I have fixed prior introduced TLS bug.
