### ISSUE TITLE
geteye()

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/CoD4x_Server#90]
Script function `geteye()` returns origin + (0,0,40) for _any_ entity and it looks unfinished. Need check for player and return vector according to current player stance (maybe getting eye positon but it seems to be a bit complicated).
Its original code:

```
void __cdecl scr_geteye(scr_entref_t ent_num)
{
  gentity_t *ent; // eax@2
  vec3_t vec; // [sp+Ch] [bp-Ch]@3

  if ( ent_num >> 16 )
  {
    Scr_ObjectError("not an entity");
    ent = 0;
  }
  else
  {
    ent = &svs_entities[(unsigned __int16)ent_num];
  }
  vec[0] = ent->r.currentOrigin[0];
  vec[1] = ent->r.currentOrigin[1];
  vec[2] = ent->r.currentOrigin[2] + 40.0;
  Scr_AddVector(vec);
}
```

**Comment by IceNinjaman** [comment]
Can people not add the z+40 in their script if they want it? Also probably doesn't work for models of different size(Dogs, monsters, ...) I assume.

**Comment by T-Maxxx** [comment]
Then getting pos of tag_eye should do the trick. But I'm not sure if viewheight == tag_eye pos

**Comment by D4edalus** [comment]
i can't really think of a situation where i'd need a more accurate player position than origin or origin+(0,40,0)

**Comment by T-Maxxx** [comment]
I always can reopen it again ^.^
