### ISSUE TITLE
steam_api relocation error

### ISSUE THREAD

**Issue by armyboylegend** [callofduty4x/CoD4x_Server#92]
I added sauth server files for linux server in root directory of cod4 and gave error

"].: relocation error: ./steam_api.so: symbol _ZNSt8__detail15_List_node_base7_M_hookEPS0_, version GLIBCXX_3.4.15 not defined in file libstdc++.so.6 with link time reference"

kindly tell me how to fix it

**Comment by D4edalus** [comment]
on most systems you can just delete the libstdc++.so.6 and it works
