### ISSUE TITLE
Multiple Process 1.8 and not in 1.7

### ISSUE THREAD

**Issue by OrigiTosko** [callofduty4x/CoD4x_Server#93]
I would like to know and find a solution to the next problem..
when i started a server on my host (linux) in version 1.7 there was a process on the server 
But with your version 1.8 the process duplicates x6.. or x7...

I have 2 servers on version 1.8 .. and they are duplicated
http://prnt.sc/d603zc

And 4 servers on 1.7, this photos are from the command htop on ssh linux.
http://prnt.sc/d604az

They are not duplicated.

**Comment by IceNinjaman** [comment]
htop shows every thread like that..

**Comment by OrigiTosko** [comment]
Only when are we talking about servers 1.8? See images pls..

**Comment by D4edalus** [comment]
those aren't duplicates, 1.8 just uses multiple threads per server
