### ISSUE TITLE
nvconfig_v2.dat

### ISSUE THREAD

**Issue by wkuzma** [callofduty4x/CoD4x_Server#99]
Note - I use the pre-compiled windows version of cod4x
I noticed that in the log when starting a server nvconfig_v2.dat is loaded twice, Is that the way it works or is it a bug?

CoD4 X 1.8 win_mingw-x86 build 1711 Nov 16 2016
--- Crypto Initializing ---
Testing sha1 hash function - positive.
rest deleted until I reached here
QUERY LIMIT: Querylimiting is enabled
[S_API] Initialization completed
loading nvconfig_v2.dat
Loaded nvconfig_v2.dat 0 errors
--- Common Initialization Complete ---
--- Game binary initialization ---

rest deleted until I reached here in log

"sv_mapRotationCurrent" is: ""

loading nvconfig_v2.dat
Loaded nvconfig_v2.dat 0 errors
------ Server Initialization ------
Server: mp_convoy
rest deleted  
Note two times the nvconfig_v2.dat is loaded

**Comment by D4edalus** [comment]
it is loaded the first time directly after the server is started, and it is loaded again before loading a new level. it might not be necessary to load it at server initialization. @IceNinjaman might know if there is a reason for that.

**Comment by IceNinjaman** [comment]
Not really sure why it works like this. Maybe it was to get HL2-Rcon running without having a map loaded. No other idea why this would make sense.

**Comment by T-Maxxx** [comment]
I don't think thats critically impacts server performance.
